### ISSUE TITLE
Alter email

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#100]
We have a few add-on resign commands and they all send an email to developers. The email isn't very helpful and we need something better. Let's do that and explain to them why their add-on is being resigned.

Supports #99

**Comment by brampitoyo** [comment]
What’s the current email like? I can try to rewrite it, if you like.

**Comment by brampitoyo** [comment]
In relation to the above, is it helpful to look at our repository of emails – I’m not sure if this exists – and try to make sure that our messages are consistent?

**Comment by andymckay** [comment]
Please see the attached pull request for an example.

**Comment by brampitoyo** [comment]
The rewrite is a bit long, but it clearly explains:

* What is the problem
* What the problem means for the add-on
* What is the fix
* What the fix will mean for developers and their end users

What do you think?

**Subject**
Mozilla Add-ons: {addon} has been re-signed on AMO

**Body**
We discovered an error in our auto-signing infrastructure, which caused your add-on to be signed with an expiry date of 1 year. This means that, if you signed your add-on at this time last year and haven’t updated it, it will stop working very soon.

The permanent fix for this problem is going to take a few weeks to land.

As a temporary fix, we are re-signing your add-on to extend its expiry date to 5 years. This process involved repackaging the add-on files and adding the string '.1-signed' to its version number.

This process does not change your add-on’s review status, so your add-on is still published. This process will also not interrupt your user in any way, as Firefox will automatically update to the newly re-signed version.

There’s nothing you need to do at this point, but if you have any questions or comments, please reply to this email or join #addons on irc.mozilla.org.

You're receiving this email because you have an add-on hosted on https://addons.mozilla.org

**Comment by jvillalobos** [comment]
I wrote another version here: https://public.etherpad-mozilla.org/p/re-re-re-sign before noticing this other thread. I left out the permanent fix in Firefox because that hasn't landed yet and I wouldn't want us to send yet another message backtracking on it or making corrections.

**Comment by brampitoyo** [comment]
@jvillalobos Your version looks good to me, as well. Let’s go with that.

**Comment by wagnerand** [comment]
Can we please use something else than "signed" as suffix, this time? It
caused a lot of confusion and a huge amount of extra support efforts last
time. I think, even just "resign" or "re-sign" should do it.

Am Dienstag, 26. April 2016 schrieb Jorge Villalobos :
