### ISSUE TITLE
Unable to install unsigned addon on Firefox ESR with configs changed to false

### ISSUE THREAD

**Issue by oraculorafa** [mozilla/addons#1007]
I am using Firefox 52.0 and I want to keep using this version. I used an old version of uBlock Origin for a long time, 1.17.4.

https://addons.mozilla.org/pt-BR/firefox/addon/ublock-origin/versions/

Suddenly, the extension was disabled saying it was unsigned. I removed it and tried to install again, same version, downloading from Mozilla. I couldn't download it. Tried to download from GitHub, it said I couldn't install it because it was unsigned. 

https://github.com/gorhill/uBlock/releases/tag/1.17.4

about:config

services.sync.prefs.sync.xpinstall.whitelist.required;false
xpinstall.signatures.required;false
xpinstall.whitelist.required;false
![Configs](https://user-images.githubusercontent.com/50266270/57179083-280eac00-6e50-11e9-855e-b1a683e6f0c6.jpg)

Then I downloaded Firefox 52 ESR, same configs, same error when trying to install the extension.

https://ftp.mozilla.org/pub/firefox/releases/52.0esr/
![Blocked Installation on ESR](https://user-images.githubusercontent.com/50266270/57179087-2e048d00-6e50-11e9-80fe-1adf2a078b6a.jpg)

Please, I don't want to update my Firefox. I just want to keep using it the way it was before, with uBlock Origin.

**Comment by wagnerand** [comment]
We rolled-out a fix for release, beta and nightly users. The fix will be automatically applied in the background within the next few hours, you don’t need to take active steps.

In order to be able to provide this fix on short notice, we are using the Studies system. You can check if you have studies enabled by going to Firefox Preferences -> Privacy & Security -> Allow Firefox to install and run studies.

You can disable studies again after your add-ons have been re-enabled.

We are working on a general fix that doesn’t need to rely on this and will keep you updated.

**Comment by oraculorafa** [comment]
2 days later, I'm still unable to reinstall the extension. Is the fix you mentioned work for Firefox 52, which I'm currently using?

**Comment by wagnerand** [comment]
Please see the latest updates here > blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox
