### ISSUE TITLE
Add-ons 

### ISSUE THREAD

**Issue by 71benc** [mozilla/addons#1008]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
![Capture123](https://user-images.githubusercontent.com/50266546/57179067-bf661480-6ecd-11e9-85f6-cbfeeef711f6.PNG)

### What happened?
Whatever updated broke most of my add-ons, and I cannot download add-ons from the website
### What did you expect to happen?
I was expecting the site that delivers add-ons to not be broken.

**Comment by wagnerand** [comment]
We rolled-out a fix for release, beta and nightly users. The fix will be automatically applied in the background within the next few hours, you don’t need to take active steps.

In order to be able to provide this fix on short notice, we are using the Studies system. You can check if you have studies enabled by going to Firefox Preferences -> Privacy & Security -> Allow Firefox to install and run studies.

You can disable studies again after your add-ons have been re-enabled.

We are working on a general fix that doesn’t need to rely on this. Sorry for the inconvenience.
