### ISSUE TITLE
define user interaction for Omnibox API 

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#101]
see [Bug 1166831](https://bugzilla.mozilla.org/show_bug.cgi?id=1166831) for details.

**Comment by brampitoyo** [comment]
Quoting Marco Bonardo:

> The scope of the API is to provide custom suggestions when a very specific keyword is typed,

There are many user experience as well as privacy implications to letting an add-on access the URL bar and its search result. But one way that we can move forward and potentially solve some of the issues is by clearly labelling which entries belong to the add-on.

Taking Marco’s comment on comment 9 as an example:

I have an add-on called “cats-finder”. This add-on registers the word “cats” in the URL bar. When the user types “cats [something]”, the awesomebar fetches suggestion for this “[something]” from the “cats-finder” add-on.

Practically, what are the rules that we should have, and what’s the user interaction like?

* No more than one entry per add-on is allowed
  * Question: what happens if I have “cats-finder”, “cats-locator” and “cats-radar” all using the word “cats” to display result in the awesomebar?
  * A potential solution is to give developers the ability to set a secondary keyword. Firefox will automatically pick this secondary keyword if the first one was already taken by another add-on
* If the entry comes from an add-on, the source should be clearly labeled
  * For example, when an awesomebar entry leads to a search engine, we show a magnifying glass icon
  * So when the awesomebar entry is a keyword registered by an add-on, we label it with the add-on’s icon. Then, to the right of the keyword, we caption the entry with something like “provided by [addon_name]”.

I’ve debated on whether to give add-on keywords its own visually distinguished area, but this seems more complicated than just including it in the awesomebar result.

Thoughts?

**Comment by andymckay** [comment]
Given that most of this is happening in https://bugzilla.mozilla.org/show_bug.cgi?id=1166831, we can probably close this.
