### ISSUE TITLE
FireFox Add-Ons Website Blocking Downloads

### ISSUE THREAD

**Issue by Petros606** [mozilla/addons#1046]
It appears that the only browser capable of downloading add-ons at the website https://addons.mozilla.org/en-US/firefox/ is FireFox 66.0.4, which is the latest after the terrible bug that shut down add-ons for almost all users after security signing expired. I have not been able to download any add-ons with older versions of FireFox, nor with latest version of WaterFox.

When you try to download with a browser other than FireFox 66.0.4, you get an error that says "Download failed. Please check your Internet connection."

Is this being implemented so that only users who have updated to latest FireFox can download add-ons from the Mozilla website?

**Comment by jvillalobos** [comment]
You can follow this blog post for updates: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/. I believe there are some options that will become available for users of older versions of Firefox soon.

As for forks like Waterfox, they may need to deploy their own updates to fix this problem. It's up to them, however.

**Comment by Petros606** [comment]
There is no new information at the FireFox blog for two days, and as I said it looks like the only people who can download add-ons are only users who have FireFox 66.0.4, and everyone else including those using older versions of FireFox are being blocked. It is unclear if FireFox intends it to stay this way, perhaps as incentive for everyone to use only the latest version of FireFox.

**Comment by willdurand** [comment]
@Petros606 sorry for the inconvenience, really. We're looking into it, that's all I can tell you right now unfortunately.

**Comment by SylwesterZarebski** [comment]
I wonder why this bug report is closed. This issue is not for addon signature disaster which disables addons, but inavailability of installing/downloading **any addon** from https://addons.mozilla.org/ when not using latest Firefox browser.
This is serious bug, which prevent all users of previous Firefox versions from installing **any addon**.

On the side, it looks like developers are so desperate to force users to use new versions, which are way worse than previous.

**Comment by SylwesterZarebski** [comment]
Edit: As older versions i mean also older Quantum ones. On Firefox 60 i can't download or install any addon (even webext) - button directs me to download newest version of Firefox - something is really wrong.

**Comment by caitmuenster** [comment]
Hi there folks. I am going to ask that we move this thread over to our [community forum](https://discourse.mozilla.org/c/add-ons) and then gently close this thread. 

We do plan to provide a fix for Firefox v. 52/56. The patch has been written and is currently in testing. Since it's been quite some time since these versions were supported, it's been a little bit more complicated -- and taken a lot more time -- to develop this fix. 

A fix has been made for Firefox v. 60. If you are able to, please check for an updated dot release, which should address the issue. If you are at a company where an IT department manages which version you are on, please kindly ask them to deploy the updated version 60.
