### ISSUE TITLE
Pagination on recommended add-ons with sort=random buggy

### ISSUE THREAD

**Issue by Lusito** [mozilla/addons#1074]
### Describe the problem and steps to reproduce it:
- visit https://addons.mozilla.org/en-US/firefox/search/?page=1&recommended=true&sort=random&type=extension
- click on next page and see add-ons appearing multiple times.

### What happened?

Each page served random entries

### What did you expect to happen?

The whole list should be random, but when I step through the pages, they should be constant in their random order.

### Anything else we should know?
No

**Comment by AlexandraMoga** [comment]
I can reproduce this. You can indeed find the same add-on recommended on multiple pages when navigating through https://addons.mozilla.org/en-US/firefox/search/?recommended=true&sort=random&type=extension

**Comment by bobsilverberg** [comment]
This is the expected behaviour with the current implementation. Each time you page through the results the query is re-executed, and therefore the randomness is also re-executed which can result on the same extension appearing on multiple pages.

I believe the intent in having these "See more..." links point to a search with `random` as the sort order was to have those links not point to the exact same extensions each time, but it results in this "unexpected" behaviour.

@jvillalobos @devaneymoz What do you think about this situation? Is the reported behaviour in this issue acceptable when paging through the "See more..." results, in order to keep the first page sorted in random order, or do you think we should revisit the use of `random`, or look into other possible solutions.

**Comment by jvillalobos** [comment]
Yeah, I don't think this is worth fixing.

**Comment by devaneymoz** [comment]
agree

**Comment by Lusito** [comment]
Could you then at least not make it the default sort order?
When people get there this way:
- https://addons.mozilla.org/en-US/firefox/
- See more recommended extensions

And then paginate through the list, they will see some extensions multiple times and some propably never, which is not something you want when discovering these extensions.
Could you maybe store the random seed in the user-session and use it when it exists and the user is not on page 1? Shouldn't be too hard.

**Comment by jvillalobos** [comment]
The random order is intentional because we don't want to favor any particular recommended extensions. I agree it can be annoying to see repeated extensions, but it's not very likely it will be a problem for lots of users. If it becomes a problem, we can reconsider our approach.

**Comment by Lusito** [comment]
Not sure you are actually getting the issue here.. Just to make this a bit more clear:

Currently it's like this:
- Say you have items [a, b, c, d] and each page contains 2 items
- Visit page 1: 2 random items are shown.. let's say a and c
- Visit page 2: 2 random items are shown.. this might be (a and d) or even (a and c) again.
  - i.e. the user can never see the full list without setting the order to non-random

What I'm suggesting:
- Visit page 1: 4 items are randomized (let's say [d,c,a,b], the first 2 are shown. [d, c]
- Refresh page 1: 4 items are randomized (let's say [b,c,d,a], the first 2 are shown. [b, c]
  - i.e. users still get random items shown
- Visit page 2: the last random item order is preserved, [d, a] are shown.
  - i.e. users can actually browse all items

**Comment by jvillalobos** [comment]
FTR, I get what the issue is.

**Comment by philip-pirrip** [comment]
> The random order is intentional because we don't want to favor any particular recommended extensions. I agree it can be annoying to see repeated extensions, but it's not very likely it will be a problem for lots of users. If it becomes a problem, we can reconsider our approach.

Weird argument, because out of 100 recommended addons and 25 addons listed on every page, some will be shown multiple times and some - by page 4 that will be about 32%  of the total number - will never be lised. 68% random extensions favored over the rest of 32%.

Note: 
How many previously unseen addons will already have been listed when we're on pages 1, 2, 3, 4:
fi=25/100
se=fi+(1-fi)*1/4=43% (instead of 50%)
th=se+(1-se)*1/4=58% (instead of 75%)
fo=th+(1-th)*1/4=68% (instead of 100%)
