### ISSUE TITLE
Lang pack won't update to a new version with the actual version format

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#1086]
STR:
Testing around version updates I've noticed that the lang packs will not update to a new version manually (with Check for updates from Add-ons Manager) or automatically (after restarting the browser).

Example:
[This lang pack](https://addons.allizom.org/en-US/firefox/addon/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-language-pack-greek/versions/) has versions such as 67.0buildid20190607204819 and the next one is 67.0buildid20190607204820 

or on prod 
https://addons.mozilla.org/en-US/firefox/addon/acholi-ug-language-pack/versions/
Older version is 68.0buildid20190717172542 and the last one is Version 68.0buildid20190813150448

**There is a workaround**: I submitted a [lang pack](https://addons.allizom.org/en-US/firefox/addon/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-language-pack-test2/versions/) with the following versions :   67.0buildid20 and 67.0buildid21. 
When the version has this shorter format then the update is working. 

Notes:
Reproducible with lang packs from stage and prod, with FF68 (Win10).

**Comment by jvillalobos** [comment]
This is not a bug on AMO, it's a limitation in the version comparison in Firefox. Because of the length of the version numbers, Firefox gives up and considers the strings identical. I had to cut down 4 digits for the comparison to work.

Either this needs to be changed in Firefox, or the language pack version scheme needs to be changed so updates will work.

/cc @Callek

**Comment by Callek** [comment]
O boo /cc @pike

**Comment by Pike** [comment]
O boo /cc @zbraniecki

**Comment by zbraniecki** [comment]
O boo /cc @aswan

**Comment by wagnerand** [comment]
@zbraniecki @aswan is not available.
