### ISSUE TITLE
List of first add-ons and themes for the disco pane

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#109]
Can we get a list of the first add-ons and themes for the disco pane? Since you want custom copy in those add-ons can we get the copy as well please?

**Comment by devaneymoz** [comment]
I can't find Phil Walmsley on github, otherwise I'd add him to this issue because a few weeks ago I sent him the full copy for this page (sans copy for themes since at the time that portion of the page wasn't completely designed, nor had the themes been selected). Because of the way UX decided to frame the copy (it's more descriptive than just the add-on title), I'll detail it fully below, but please let me know if anything requires further explanation. Here are the four debut add-ons, listed in the order we'd like them to appear:

[**Block ads** with AdBlock Plus](https://addons.mozilla.org/firefox/addon/adblock-plus/)
_“This add-on is amazing. Blocks all annoying ads. 5 stars.”_  - rany

[**Take screenshots** with Awesome Screenshot Plus](https://addons.mozilla.org/firefox/addon/awesome-screenshot-capture-/)
_“The best. Very easy to use.”_  - meetdak

[**Up your emoji game** with Emoji Cheatsheet](https://addons.mozilla.org/firefox/addon/emoji-cheatsheet/)
_“Very simple interface and easy to use. Thank you.”_ - shadypurple

[**Download videos** with Video DownloadHelper](https://addons.mozilla.org/firefox/addon/video-downloadhelper/)
_“Download videos in a single click.”_ - Carpe Diem

**Comment by devaneymoz** [comment]
As for the four themes, they have not been finalized, but this can be executed pretty quickly. When do you need them by?

**Comment by andymckay** [comment]
@pwalm is Phil. Thanks, no rush on the four themes (as in next couple of weeks).

**Comment by diox** [comment]
@devaneymoz any news on those themes ?

**Comment by devaneymoz** [comment]
@dlox: I had this noted to finalize tomorrow (Wednesday). Is that okay or are they needed tonight?

**Comment by devaneymoz** [comment]
Here are our four debut Disco themes (preferably stacked in this order):

https://addons.mozilla.org/firefox/addon/golden-butterfly_9/

https://addons.mozilla.org/firefox/addon/kanagawa-wave/

https://addons.mozilla.org/firefox/addon/cat-glasses/

https://addons.mozilla.org/firefox/addon/marvelous-magnolias-by-madonna/

**Comment by diox** [comment]
@devaneymoz : thanks. Do we need editorialized titles for those, or are we re-using the theme name and author directly?

**Comment by devaneymoz** [comment]
@dlox: It's my understanding we do NOT need editorialized titles or really any copy for these themes. I believe we're just displaying the themes' actual titles?

**Comment by diox** [comment]
I don't know, that's why I'm asking :)

@devaneymoz / @pwalm : Can you give me the ordered list with both addons and themes ?

https://github.com/mozilla/addons/issues/64#issuecomment-199359978 has a design with 1 theme, 2 addons, 1 theme, 2 addons, 1 theme, and then it ends there, but that would be a total of 3 themes and I have 4.

**Comment by diox** [comment]
Also, one of those, https://addons.mozilla.org/en-US/firefox/addon/cat-glasses/ has a background that would look rather weird in the design, IMHO:

> ![cat-bg](https://cloud.githubusercontent.com/assets/187006/15393389/4cb43cea-1dcd-11e6-9c43-9ee82bec1eb4.jpg)

**Comment by devaneymoz** [comment]
dlox: good catch on the background image weirdness for the "cat glasses" theme, but if primarily white (or clear) theme backgrounds are problmatic we may continue to run into this issue because many themes make use of negative background color so the primary images pops out. 

The total number of themes to be displayed is not my domain. Perhaps pwalm can jump in here, but it would be my preference to run four. 

It is also pwalm's call on how the themes and add-ons are staggered. But if we go with what's outlined in #64 Comment, here's my suggestion (note only three themes here with removal of Cat Glasses):

Golden Butterfly (theme)
AdBlock Plus (add-on)
Awesome Screenshot (add-on)
Kanaga Wave (theme)
Emoji Cheatsheet (add-on)
Video DownloadHelper (add-on)
Marvelous Magnolias by MaDonna (theme)

**Comment by pwalm** [comment]
Four sounds good! As long as the themes and add-ons are mixed up, we're good.

**Comment by andymckay** [comment]
So it looks like here @devaneymoz is suggesting we remove Cat Glasses and instead use Marvelous Magnolias, which is this theme: https://addons.mozilla.org/en-US/firefox/addon/marvelous-magnolias-by-madonna/?src=ss

@diox could you change that please?

**Comment by diox** [comment]
Totally missed that somehow. I'll review the list.

**Comment by diox** [comment]
I had actually already included Marvelous Magnolias, it's just not on dev (it's the only addon/theme in the list that does not exist on dev).

I removed Cat Glasses entirely for now.
