### ISSUE TITLE
Redesign Add-on and Theme Preference Panes

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons#111]
Our current pref panes for both add-ons and themes aren't great. Double links, redundant buttons, limited info at a glance. Let's make them better!

### Cold start
![add-ons - cold start](https://cloud.githubusercontent.com/assets/6797635/15341614/94c8d6a6-1c44-11e6-982a-8a7c45421a4f.png)

### Active only
![add-ons - active only](https://cloud.githubusercontent.com/assets/6797635/15341625/ad146716-1c44-11e6-8056-da0d0958d486.png)

### Inactive only
![add-ons - inactive only](https://cloud.githubusercontent.com/assets/6797635/15341632/b5b9af52-1c44-11e6-9f23-5d23ff313f03.png)

### Disabled only
![add-ons - disabled only](https://cloud.githubusercontent.com/assets/6797635/15341641/c18bd21a-1c44-11e6-8fa5-b5101a2ce5ea.png)

### List hover
![add-ons - list hover](https://cloud.githubusercontent.com/assets/6797635/15341652/d54240b4-1c44-11e6-82fa-51b0ff51eae2.png)

### Suggested apps hover
![add-ons - suggested add-on hover](https://cloud.githubusercontent.com/assets/6797635/15341660/e29fddf2-1c44-11e6-8949-af825c74f102.png)

### Hover states
![add-ons - hover states](https://cloud.githubusercontent.com/assets/6797635/15341787/b725de14-1c45-11e6-9bad-72e96d0cbee2.png)

### Cold start
![themes - cold start](https://cloud.githubusercontent.com/assets/6797635/15341722/47c5022a-1c45-11e6-9c0d-f076b2b2122a.png)

### Active only
![themes - active only](https://cloud.githubusercontent.com/assets/6797635/15341731/5337a0cc-1c45-11e6-95c5-b48fdbbe564a.png)

### Inactive only
![themes - inactive only](https://cloud.githubusercontent.com/assets/6797635/15341796/c0913ac0-1c45-11e6-9e15-b4530b617c34.png)

### Active hover
![themes - active hover](https://cloud.githubusercontent.com/assets/6797635/15341803/cc5f1e94-1c45-11e6-9d13-0e3944a67585.png)

### Inactive hover
![themes - inactive hover](https://cloud.githubusercontent.com/assets/6797635/15341811/d9ac8c6c-1c45-11e6-81b5-f591ccc2176e.png)

### Hover states
![themes - hover states](https://cloud.githubusercontent.com/assets/6797635/15341825/ee1f5404-1c45-11e6-89bf-6f2b0b4993a9.png)

**Comment by tofumatt** [comment]
This is AMAZING 🎉🎉🎉

- tofumatt

**Comment by maxpopp** [comment]
I totally like the clean and tidy way, the elements are presented.
Question: Is there a different style of the "flip-switch" element for Windows or will it be the same?

**Comment by designakt** [comment]
I particularly like the empty states. And especially the idea that the default theme is not a theme! And that there is a clear separation between active and inactive.
I see you removed the "more" option, and you mentioned that is also accessible via preferences. Not all add-ons have preferences, so I wonder how we will deal with those. And with WebExtensions options will move into a modal instead of being that 2nd hierarchy level without any indication of hierarchy.
[![Add-on Options UI](https://bug1212685.bmoattachments.org/attachment.cgi?id=8689594) _Bug 121685_](https://bugzilla.mozilla.org/show_bug.cgi?id=1212685)
With that, they might be separated from add-on details, but I wonder if we need those in Firefox anyway, or if those details can be provided via a link to the AMO page of that add-on?

**Comment by pwalm** [comment]
@maxpopp Will be the same for Mac/Windows/Linux, this control is part of the Firefox style guide.

**Comment by pwalm** [comment]
@designakt Good point on the info vs. prefs button. Perhaps the button can change based on the info provided? If it's just information we can say "Add-on Information" (or whatever) and if the add-on has prefs we can just do what i've mocked up?

And not sure what the best way to surface those prefs is. I'm not super keen on modals in general, but I do like what you've designed quite a bit.
