### ISSUE TITLE
Feature request: FAQ section for each WebExtension page

### ISSUE THREAD

**Issue by nodeticswww** [mozilla/addons#1125]
Could we have a FAQ section feature so that WebExtension authors could easily list frequently asked questions and answers in a clear separate section on the WebExtension page? So on the WebExtension main page there could be e.g. a button "FAQ" which would then take the user to a separate subpage?

You could of course include Q & A in the WebExtension description but that easily gets messy, too long and hurts SEO as some search engines pick the problems as the main description (like duckduckgo can do).

It would be also useful that when someone wants to write a review, the AMO UI shows a link to the WebExtension FAQ, review guidelines link and support email + site link of the WebExtension. Too many users tend to use reviews as a channel to report bugs and request support.

**Comment by muffinresearch** [comment]
@jvillalobos I like this idea, maybe we could consider it for any future details page changes?

**Comment by jvillalobos** [comment]
I think questions about how an add-on works are better answered in the onboarding flow for the add-on, or with some Help feature that is part of the add-on itself. Only a small fraction of users will return to the add-on install page to try to find help. These things should be available to users as part of the add-on, rather than rely on AMO.

We have some changes coming up for the add-on summary and description so that it is clearer what they are meant to communicate to users. I agree that using the description as a dumping ground for any extra information isn't great, but adding more text fields isn't necessarily the right way to go.

I should also note that we do have a separate Developer Comments field that already exists in devhub but we haven't exposed back to users since the new front-end was implemented: https://github.com/mozilla/addons-frontend/issues/2764. That could be a shorter-term solution to this issue.

**Comment by nodeticswww** [comment]
Please note that many users have questions even before the install the extension. And I have lost count how many times someone has complained something in a review which is already answered in the internal Help file of the application. Having the FAQ there just before the user is about to write that rant review would really help. What's the harm of having such feature?

**Comment by jvillalobos** [comment]
It's a feature that has to be built and maintained, and would take additional effort to remove if it turns out not to be generally useful. Making it a separate subpage like you suggest would be even more work. For example, the Developer Comments feature I mentioned above isn't exactly being missed by a lot of people, but I think should be brought back because it already exists in the backend and the new front-end was supposed to support it when it was implemented a long time ago.

Anything we add has to be seriously considered because it required investment, and taking it out later is much harder. I'm also skeptical that creating this field will do much to solve your problem.

**Comment by nodeticswww** [comment]
I'm merely trying to save everyone's time. My time, AMO admin time, user time. The time is saved by reducing the number of unnecessary questions (and time it takes to answer them), invalid bug reports, reviewing of reviews that are not really reviews but support requests or bug reports etc. As it stands, I find myself answering the same questions all the time because there's no good place for providing the answers to these frequently asked questions.

I'm surprised that something as simple as this is seen as a massive effort to implement and maintain(?) but I'll take your word for it and you can close the issue.
