### ISSUE TITLE
Content Scripts not executing 

### ISSUE THREAD

**Issue by garyfeutz** [mozilla/addons#1130]
With Firefox version 70.0.1 (64 bit)

When navigating to a page from a new tab from the Top Sites list, or by opening a tab by right clicking on a url on a page and selecting Open Link in a New Tab, a content script associated in an addon manifest for that URL does not execute in the tab when displaying that url. 

The content script does execute when navigating to a page via a bookmark or by manually entering the url in the browser.

The content script should execute regardless of the means by which the browser gets it.

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
