### ISSUE TITLE
Master password popup - says PW not correct - but it is

### ISSUE THREAD

**Issue by jjfnj** [mozilla/addons#1131]
Master password popup - says PW not correct - but it is

When I login to Firefox it says enter your master password, I do but, it says it's not correct.

I expect it to Sync my FF browser with my other devices, which it does, partly, my shortcuts come over, my extensions come over to the new browser.  I see my personal avatar in my Firefox, I know it's my account, then when I sync... here comes the popup again, which says my password is not correct.  Help 

### Anything else we should know?  

Yes.  see link below.  this is what I get.
https://duckduckgo.com/?q=firefox+master+password+popup&t=ffab&atb=v117-1&iax=images&ia=images&iai=https%3A%2F%2Fi.stack.imgur.com%2F9TrUJ.png

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
