### ISSUE TITLE
Get to faster sooner – remove an extension to enable e10s sooner

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#119]
For many users e10s will speed up their Firefox considerably.
At one point we will migrate all users to e10s and with that might need to tell them that we disabled some extensions as they will break with e10s. (#48) Before we migrate all users we can offer them to get to a faster Firefox sooner by removing certain add-ons. (This would be a positive messaging about a faster Firefox, rather than one about a disabled extension. It would also give users some time to decide for themselves and developers some time to make their extensions e10s compatible)

Such a message could look something like this:
![motivatetomigrate](https://cloud.githubusercontent.com/assets/8145891/15653657/8310bcea-268e-11e6-913d-3b681089bdc6.PNG)
- It could be targeted to users with a small number (>=3) of incompatible (or unknown compatibility) add-ons. 
- It would state the option to make Firefox faster, offer replacements, or with one click remove all mentioned add-ons and enable e10s.
- In addition it could also mention for how long this choice will be voluntary before all users will migrated to e10s.

This issue is to discuss if such a feature will be helpful to enough users and how it could be implemented.  @deadsquid @bbinto @pwalm 

Related to issue #48 ( Provide a UI for migrating users' add-ons to e10s ) but could be a step before that.

**Comment by brampitoyo** [comment]
+1 I like the ability to manually expedite the update.

Our update interface is designed to work automatically and silently for the most part. But instead of showing you incompatible add-ons *after* the update (at which point it’s too late to do anything about it, other than to find a replacement), we can show you those add-ons *before* the update and give you more control), as shown in this interface

**Comment by atsay** [comment]
Removing an add-on because it breaks with e10s is a different message from removing add-ons to make your Firefox run faster. I'm not sure of the value this would add, and additionally might have unintended negative consequences. That said, I'm a fan of showing people how fast an add-on is when administering their installed add-ons in the ADM.

**Comment by tofumatt** [comment]
I don't think the message is different to an end-user. "This add-on makes my Firefox slow" is true if the add-on _itself_ is slow or if it causes Firefox to run in a much slower, less stable mode.

**Comment by andymckay** [comment]
I don't think this is going to happen?

**Comment by GJRobert** [comment]
This is very hostile and ignorant and rude to addon developers. Glad it's not going to happen.

**Comment by designakt** [comment]
@GJRobert I would love to understand why you think so.

**Comment by GJRobert** [comment]
Hi @designakt ,
Thanks for your kind inquery. (I only see your reply today 'cause I'm not coder and a frequent user of GitHub actually)

Forgive my straight wording in my last post.

It was just, to me, looking like all those great old addons are the only things to be blamed for dragging and making Firefox a second-class and out-of-fashion browser, from the point of view of this issue in the first place. Maybe it's totally legitimate or even just humorous in your culture, to create such a notice to end users to let them "speed up" their browser, urging them to abandon old stuff and embrace the era of new technologies, but if I am one of the developers who has devoted years of hard work, hoping to enrich this great Firefox addon ecology and society, and all of sudden my work is named as a big rock on the highway of e10s or other some other new trick, I will be really, really, really upset and sad.

Say I'm too sentimental.

To me, developers and addons are not dispensable and easily replaceable, if I am the master of this browser. Our new strategy, new framework and new APIs drives and drops lots of developers away, forcing them to abandon contributing, and they will not be back easily. So will be some greatest and most popular addons. And so will be some (may very few in your eyes) sentimental and old stubborn users like me.

I appreciate recent efforts of you guys from the circle of Mozilla to build a brand new super-fast Firefox (with all these fabulous Servo, e10s, Quantum, WebAssembly... stuff) hoping to make it the most popular browser in the world again. And I believe to some guys rolling out e10s and WebExtensions is a hard but necessary decision.

**But let's just not spill salt on the wound of those who are deemed to be left behind just because they have burnt out their passion and happiness.** That was my point of my last post. Thanks for your willing of listening again.

----

(A couple of remarks of my opinion on recent change of addons, if you are still there; you are free to complain "tl;dr"!
* e10s is respectable and may not be too hard to overcome for developers, but closing XUL is the most heart-breaking part. Maybe to most of you guys in Mozilla, yes, most users in the world do not even use addons or care for customization, and (you think) they just want Firefox to have same extensions as Chrome
* Actually I have had enough of people comparing the two browsers since the birth of Chrome and always saying that Chrome wins in performance; had enough of this world dominated by WebKit and Blink; had enough of hating but having to envy Chrome for smoother and better browsing experience (while bearing the huge RAM and energy consumption of both Chrome and Firefox, which both cause headaches on my MacBook Air), because I have been fascinated of Firefox UI, themes, addons and Gecko rendering ever since 2004/v0.9/Mozilla era. Chrome is an usurper, taking away the trophy and laurel of destroying the IE hegemony which should have been belonging to Firefox.
* To me, Firefox was not so slow and was quite usable in the golden era, when I can put 30+ addons onto it and it was still quite usable.
* Yes then Chrome emerged and could render pages and execute JavaScript superfast, so you think the root suspect is XUL, and Firefox should be redesigned in the Chrome way.
* But without the hope and support of current Firefox addons, I decided to turn to Vivaldi last month, since in the future all browsers WILL ALL be running CHROME extensions, so I was suprised to find that Vivaldi is indeed fast while preserving the spirit of deep customizability for power users. I thought that Vivaldi might be my default browser in the next years.
* But I'm still not satisfied with the RAM footprint of multi-process browsers, and I still do not appreciate the font in WebKit/Blink (too thin and too pale to my eyes), so suddenly I found the build of Pale Moon for Mac OS, and then story is... I'm back on a full-fledged old-school but satisfactory Gecko browser. Australis is absent, and many addons are only compatible with old versions. Pale Moon quite makes me recall the Firefox back a couple year ago, but is very usable, RAM- and energy-efficient on a laptop. I have long been unsatisfied to use every browser on my MacBook, but Pale Moon is doing a good job to give me back to smoothness and power of web surfing, with XUL addons supported, without multi-process structure at all.
* So is it XUL and single process to be blamed? I know to many of you it's worth to abandon deep customization and those dangerous APIs and embrace newer structures. But, the existence and success gained by Pale Moon, might well be something worth reflecting on.
)

**Comment by designakt** [comment]
Thanks for sharing your view more detailed! This helps me better get context and build empathy with your view.
I find your point on `the spirit of deep customizability for power users` very interesting. What are to you those features that you turned to Vivaldi for, and then Pale Moon? - I ask because we are [expanding the power of extensions](https://wiki.mozilla.org/WebExtensions#Additional_APIs) beyond what Chrome can do, and we are looking into building [features that appeal to power users](https://testpilot.firefox.com/experiments/tab-center) ourselves, because we value those and to a big part are power users ourselves. 😉
