### ISSUE TITLE
Addon page should show an older version if the current one is not compatible

### ISSUE THREAD

**Issue by dgutov** [mozilla/addons#120]
Example: https://addons.mozilla.org/en-US/firefox/addon/bmreplace/ shows the latest version to everyone, even though it requires Firefox 47 or newer. And to most users now, it says "Not available for Firefox 46".

The previous version of the addon is available, and it declares compatibility with Firefox 40 and newer. The addon page should recommend it to the users with Firefox < 47.

**Comment by diox** [comment]
We decided to wontfix this particular problem back when we did some work on compatibility for Firefox 57. See https://github.com/mozilla/addons-server/issues/5482 and other bugs with the same project label for more information.

We could revisit this later if it turns out to be an issue, but the majority of extensions we support these days are compatible with all supported Firefox versions, thanks to being WebExtensions.

**Comment by dgutov** [comment]
Fair enough.
