### ISSUE TITLE
Bug in the extension release notes

### ISSUE THREAD

**Issue by FilipePS** [mozilla/addons#1222]
My extension: https://addons.mozilla.org/firefox/addon/traduzir-paginas-web/

The Default Locale was (pt-br) and after a while I changed to (en-us).
After the change, the extension version notes do not appear anywhere beyond the extension's admin panel. For example, it does not appear here: https://addons.mozilla.org/firefox/addon/traduzir-paginas-web/versions/

Only version 6.1 notes are appearing because I manually set this release note in (pt-br).

**Comment by jvillalobos** [comment]
You can edit the version notes in the individual version edit page, [like this one](https://addons.mozilla.org/developers/addon/traduzir-paginas-web/versions/5070560). Note that there's a localization dropdown at the top right. If you don't localize your version notes at all, they should fall back default locale. If you changed your default, then there are probably many old versions localized to the old default (pt-br) that don't show up because of the new default (en-US). I think you would need to copy over the version notes to the new default language so they still appear.

**Comment by FilipePS** [comment]
Although the default language is currently en-us, Mozilla addons is using pt-br as a standard to display this information.
