### ISSUE TITLE
Google Improver referral spam addon (from Bugzilla)

### ISSUE THREAD

**Issue by djc** [mozilla/addons#123]
https://bugzilla.mozilla.org/show_bug.cgi?id=1277190 was filed on Bugzilla. Since the AMO product there seems mostly empty, figured there might be a better place to get this in front of the right people?

**Comment by wagnerand** [comment]
Can you please elaborate what "referral spam" means?

**Comment by tofumatt** [comment]
@djc In the future, you can use the "Report Abuse" link on an add-on's page to report privacy concerns.

<img width="1202" alt="screenshot 2016-06-02 07 43 14" src="https://cloud.githubusercontent.com/assets/90871/15743786/ddc09788-2895-11e6-944a-a5a62fa1b5be.png">

We could probably make that link more obvious, sorry 😞

**Comment by tofumatt** [comment]
@jvillalobos Looks like the add-on in question though is full of negative reviews saying it's spam; worth looking into?

**Comment by djc** [comment]
@tofumatt I did actually go and do that after filing this; however, I kind of assumed that someone would already have done that and it apparently had no effect.

Also, I'm not really a party to this bug; I just happened to triage the Bugzilla-side bug.

**Comment by jvillalobos** [comment]
The add-on itself is just a search engine (with some clever ideas in it, actually), and as far as I can tell doesn't contribute to the spamming. The owner of the add-on is probably behind the spamming, since it points to the add-on page, but disabling the add-on wouldn't make any difference.

@wagnerand, @kewisch, @eviljeff from an add-on policy standpoint, should we punish a developer from something done outside of the add-on? Is the add-on listing useful to keep at all given the overwhelmingly negative reviews?

**Comment by wagnerand** [comment]
Personally, I am not sure the add-on is super useful, but ymmv.

Generally, I think, we should not punish developers of add-ons for something done outside of the add-on. But if the author of the add-on and the author of "outside" is the same person, it might be reasonable.

Thoughts?

**Comment by kewisch** [comment]
So this add-on just passes results through this website and then defers to Google. The other feature is mostly provided by the awesomebar. There is a lot of text in the add-on description and on his site, which makes me want to stop reading.


If there is a scheme behind this and something can be changed in AMO to avoid it, that is a direction I'd support. Aside from that, I don't really think these are reasons to disable the add-on because it does not do anything that it is not supposed to. If the add-on gets a lot of bad reviews, then so be it, users will see that and not install it.

**Comment by jvillalobos** [comment]
Yes, as far as I can tell there isn't anything we can do on our side to stop the developer from spamming, and the reviews for the add-on are enough to prevent users from finding it or installing it. I'm closing this as WONTFIX.
