### ISSUE TITLE
Consider bumping the MAX_FILE_SIZE_TO_PARSE_MB

### ISSUE THREAD

**Issue by iann0036** [mozilla/addons#1237]
### Describe the problem and steps to reproduce it:
For consideration, the minified version of the AWS JS SDK with all services has recently just busted 4MB. It would be helpful if  the limit was adjusted to 8 or even just 5.

https://github.com/mozilla/addons-linter/blob/master/src/const.js#L92

### What happened?
I tried to upload an extension with the AWS JS SDK minified with all services.

### What did you expect to happen?
The upload to pass validation.

### Anything else we should know?
Relates to https://github.com/mozilla/addons/issues/181

**Comment by jvillalobos** [comment]
The minified version appears to be 2.5 Mb, so that would still work (but require sending the original sources separately).

Generally, I think our policy about this constant is that it should be bumped up when there are enough valid use cases that warrant larger JS files. Figuring out "enough" and "valid" should probably fall on @kewisch, though. As the comment in the source explains, these very large files are problematic in their own right, so they should be avoided as much as possible, especially for extensions which are supposed to be lightweight.

**Comment by iann0036** [comment]
Hi @jvillalobos,

The 2.5 Mb version only contains the "default services" of AWS, and excludes some important services for my use case. If you visit https://sdk.amazonaws.com/builder/js/ and instead select the "Select all services" option, you'll find the minified build to be 4.1 Mb.

**Comment by jvillalobos** [comment]
Do you need _all_ of them, or are you choosing all out of convenience? This file needs to be loaded by Firefox on a regular basis and will impact general performance.

**Comment by iann0036** [comment]
I unfortunately need most of them.

I could split them out and load them individually, but that would be a very tedious process both for myself and addon reviewers. This is the README I currently bundle for addon reviewers:

```
# Notes for Add-on reviewer

The aws-sdk-2.xxx.0.min.js file can be generated at https://sdk.amazonaws.com/builder/js/ with the "Select all services" option, then removing the following services:

* RedshiftData
* Bracket
* IVS
* HoneyCode
* KinesisVideoSignalingChannels
* ConnectParticipant
* ComprehendMedical
* Translate
* Comprehend
* Rekognition
* MTurk
* LexRuntime
* CloudSearchDomain
* CloudSearch

Note the build time on the page can be a few minutes. Also included the base file (Development) in this archive.

Credentials are available on the whiteboard.
```

**Comment by NiharRanjanBisaria** [comment]
I am also facing the same issue for past week , 
https://github.com/mozilla/addons/issues/1249
https://github.com/mozilla/addons/issues/1247
https://github.com/mozilla/addons/issues/1254
https://github.com/mozilla/addons/issues/1237

we have been uploading addons for past 5-6 years but never faced an issue with size , recently since past week we have been facing this issue
we have JS file sizes of 1Mbs.

Can you please consider bumping up the file size if this resolves this problem or
is this failure is happening because of some other issue because in subsequent trails one of the addon passed signing ? 

@willdurand  has commented on 1254 saying that it could be a potential AWS issue.

please provide a RCA as our organisation has been facing this issue for the past week.And we still have not received a confirmed RCA.

**Comment by iann0036** [comment]
Future travellers; I am now using this dodgy Python script to split my AWS SDK (v2):

```
import os
import json
import requests
import pprint

stream = os.popen('npm show aws-sdk version')
version = stream.read().replace('\n','')
metadata = json.loads(requests.get('https://sdk.amazonaws.com/builder/js/cache/' + version + '/metadata.json').text)

output = ''
partno = 1
line = 'x'

with open('aws-sdk-' + version + '.js', 'r') as f:
    while line != '':
        i = 0
        while i < 100000 and line != '':
            line = f.readline()
            output += line
            i += 1
        while line != "\n" and line != '':
            line = f.readline()
            output += line
        with open('aws-sdk-' + version + '-part' + str(partno) + '.js', 'w') as f2:
            f2.write(output)
            output = ''
        partno += 1
```
