### ISSUE TITLE
Can't add "Android PDF.js" to a collection

### ISSUE THREAD

**Issue by yoasif** [mozilla/addons#1252]
### Describe the problem and steps to reproduce it:

1. Login to AMO
2. Navigate to previously created collection
3. click edit
4. Search for "pdf js" or "Android PDF.js" in the text box

### What happened?

No search results for https://addons.mozilla.org/en-US/android/addon/android-pdf-js/

### What did you expect to happen?

I am able to add https://addons.mozilla.org/en-US/android/addon/android-pdf-js/

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
The search box filters the results by compatibility, so if you're doing this from desktop for an add-on that is mobile-only, it won't show up.

An alternative way to add it is to visit the add-on page (on any platform) and look for the "Add to collection" box, where you can choose which of your collections to add it to.

Closing because this is a stop-gap solution and we don't intend to change our search to accommodate it.

**Comment by Poopooracoocoo** [comment]
@jvillalobos I made a few comments on the blog post but they weren't approved :/ I mentioned something about this in one of my comments

**Comment by jvillalobos** [comment]
>  I made a few comments on the blog post but they weren't approved :/ I mentioned something about this in one of my comments

They're moderated, so they might still be on hold, not sure.

> oh and while you're here, AMO says "users" instead of "reviews". this can be really annoying.

I don't know what you're referring to here. If you think it's a bug, please file it separately.

**Comment by Poopooracoocoo** [comment]
>I don't know what you're referring to here. If you think it's a bug, please file it separately.

Look at this issue: https://github.com/mozilla-mobile/fenix/issues/10002

Firefox for desktop's about:addons doesn't have this issue and neither does Fenix's add-ons page.

**Comment by jvillalobos** [comment]
I don't see anywhere on AMO where the term "users" is used when "reviews" should be used instead.

**Comment by Poopooracoocoo** [comment]
ah my mistake. it actually does show the users. It's a pretty different interface to the ones in Firefox. Hovering over it shows you the rating but not how many people have reviewed it. 
![image](https://user-images.githubusercontent.com/51363864/94981714-cb00b380-0577-11eb-9e74-a638579d2646.png)

Firefox for desktop actually shows the users too and I apologise for not looking at it properly:
![image](https://user-images.githubusercontent.com/51363864/94981741-2632a600-0578-11eb-8b56-ba10ea75aecc.png)
to find how many people reviewed it, you need to go into the extension details of an installed extension:
![image](https://user-images.githubusercontent.com/51363864/94981797-7f9ad500-0578-11eb-9af7-5afb15d4774a.png)
you can kinda see why i thought that there was a mistake because of the text beside the star rating being different in two parts of the interface and because of that other bug. 

_lol being wrong hurts but its healthy to admit it and to learn from it_ 

I guess I might file an issue on the Fenix repo suggesting that they use the user count instead of the review count for consistency
