### ISSUE TITLE
Inconsistency between badge status of an add-on on AMO and about:addons

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons#1261]
### Describe the problem and steps to reproduce it:
1. Go to https://addons.mozilla.org/en-US/firefox/addon/google-search-link-fix/. Notice that the extension has no badges:

<details>
<summary>Click for screenshot</summary>

![Screenshot_2020-10-09 Google search link fix – Get this Extension for 🦊 Firefox (en-US)](https://user-images.githubusercontent.com/8336638/95500634-b29ff700-09c4-11eb-8be8-6e0d3c4713d5.png)

</details>

2. Install the extension and head over to about:addons.

### What happened?
Notice that the same extension now has a 'Recommended' badge.

<details>
<summary>Click for screenshot</summary>

![Capture](https://user-images.githubusercontent.com/8336638/95500733-e24eff00-09c4-11eb-88c1-589366ae3d93.PNG)

</details>

### What did you expect to happen?
Same badging on AMO and about:addons.

### Anything else we should know?
The add-on xpi contains the mozilla-recommendation.json file: https://robwu.nl/crxviewer/?crx=https://addons.mozilla.org/en-US/firefox/addon/google-search-link-fix/?qf=mozilla-recommendation.json

**Comment by diox** [comment]
Hi,

This is a bit of an edge case, but it's expected behavior and nothing to worry about.

This particular extension used to be recommended, but because its maintainer has decided to no longer support it actively we removed the recommendation. At the moment, the latest version available has still passed thorough review and because of that, it keeps the badge in Firefox. AMO has slightly more up to date information and doesn't display the badge on the page - note in particular it has the warning about not being actively monitored, which is accurate. If a new version is published, it will lose the badge in Firefox.

**Comment by Rob--W** [comment]
Here is some more context on this specific add-on:
https://www.reddit.com/r/firefox/comments/irtg5x/addon_recommended_on_one_machine_not_the_other/g52lnj7/
