### ISSUE TITLE
Broken banner on addons.mozilla.org when visiting from FF on android 

### ISSUE THREAD

**Issue by caseybaker** [mozilla/addons#1273]
On an Android device, visit addons.mozilla.org in Firefox. Search any string. Click on any result. On the page for the add-on, the message "To find add-ons compatible with Firefox for Android, click here" is displayed in a yellow banner beneath the grayed-out "add to firefox" button. The link in the banner takes you back to the add-ons.mozilla.org landing page with no change in filtering or add-ons. There is apparently missing functionality or a broken link.

Either the message should be removed as it does not do anything or the link should be fixed to point to the correct page (or to apply a filter correctly).

**Comment by willdurand** [comment]
cc @bobsilverberg

**Comment by bobsilverberg** [comment]
This is the intended behaviour. The home page only displays Recommended add-ons that are installable on Android, so by redirecting to the home page we are sending the user to a list of "add-ons compatible with Firefox for Android". You'll notice that if you click on one of these, the detail page for that add-on no longer displays the same banner, but instead displays a banner saying "You can install this add-on in the Add-ons Manager. Learn more about add-ons for Android." This is because it is not currently possible to install add-ons from AMO into the Android browser, but rather the Add-ons Manager needs to be used.
