### ISSUE TITLE
Addon Validation Error: Validation was unable to complete successfully due to an unexpected error.

### ISSUE THREAD

**Issue by GabrielDuarteM** [mozilla/addons#1309]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

It happened when I tried to submit a new extension.

* Whether your add-on is listed or unlisted.

Should be listed, but I haven't got to that part yet I guess...

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-us/developers/addon/submit/upload-listed

* The approximate time you submitted the add-on, with timezone.

Time zone in Hamburg (GMT+2)
Monday, 5 April 2021, 08:49 

The extension:
[Archive.zip](https://github.com/mozilla/addons/files/6256719/Archive.zip)

**Comment by AlexandraMoga** [comment]
I've tried to submit the extension through devhub and the validation is indeed not completed. The error is: Error: Validation was unable to complete successfully due to an unexpected error.

I've also run the add-on directly through `addons-linter` and  I was able to get validation results. Looks like the issue is somewhere in addons-server.

**Comment by diox** [comment]
Likely https://sentry.prod.mozaws.net/operations/olympia-prod/issues/10378322/?query=is%3Aunresolved which is a timeout in customs (504 actually)

**Comment by jannecederberg** [comment]
I'm trying to upload a revised version of an addon that has existed since 2015. The last update I made to it was on April 1, 2021 (not April fools) and it succeeded. Now the only change I have made to the previously uploaded addon version is changing the direction of one list comparator function to sort descending instead of ascending (literally changing one comparison operator: < to >). So 100% sure the problem is at Mozilla's server and has started occurring since April 1, 2021.

**Comment by diox** [comment]
@jannecederberg I suspect your problem is different than the original poster in this issue. Please try again, we had an issue with validation in general that we fixed since.

**Comment by GabrielDuarteM** [comment]
is there anything I can do to make it possible to release the extension or to help in fixing this problem?

**Comment by diox** [comment]
@GabrielDuarteM you included `prettier` in the `node_modules` in your add-on. Can you try submitting without it ? That causes several very large JavaScript files to be included, and I think that's what our scanners are choking on.

**Comment by GabrielDuarteM** [comment]
oohhh, I've zipped the file in a hurry, the node_modules folder was not supposed to go in, didn't even see it ahahahaha that solved, thanks!
