### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by xlzy520** [mozilla/addons#1335]
Please attach a copy of your add-on, and fill in the following information:

![image](https://user-images.githubusercontent.com/28336270/122683958-2e7d5f00-d235-11eb-9016-22dcdabc15cf.png)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

* Whether your add-on is listed or unlisted.

* The URL where you submitted the add-on.
[dist.zip](https://github.com/mozilla/addons/files/6682841/dist.zip)

* The approximate time you submitted the add-on, with timezone.
Mon Jun 21 2021 02:05:12 GMT+0800

**Comment by AlexandraMoga** [comment]
You add-on doesn't have the `manifest.json` file at the root of the extension. Looks like you archived the the add-on directory rather than the add-on files themselves. 

That being said, a fix for the validation error you received should land soon - https://github.com/mozilla/addons-server/issues/17370

Also, you can check this [page](https://extensionworkshop.com/documentation/publish/package-your-extension/) if you need more info about add-on packaging

**Comment by xlzy520** [comment]
已解决
