### ISSUE TITLE
Unable to sign extension

### ISSUE THREAD

**Issue by kmq** [mozilla/addons#1350]
### Describe the problem and steps to reproduce it:

I want to sign an extension. I want the extension to be unlisted. 
To this end I am using the "web-ext" tool in version 6.2.0 ( the lasted to be available on archlinux)

### What happened?

The signing process  took too long. So I manually cancelled it. Ths resulted in me being unable to sign my extension. Updating the version number led to the signing process timing out, without my intervention. 
When I try to sign my extension, I receive an error 500 from some mozilla server.

### What did you expect to happen?

I expected my extension to be signed.

### Anything else we should know?

I have attached an edited version of my terminal session that shows the problem: [mozilla_report.txt](https://github.com/mozilla/addons/files/7001729/mozilla_report.txt)

I have attachd the extension that i wish to be signed: [youtube-mpd-1.0.0.zip](https://github.com/mozilla/addons/files/7001734/youtube-mpd-1.0.0.zip) 
[youtube-mpd-1.0.1.zip](https://github.com/mozilla/addons/files/7001795/youtube-mpd-1.0.1.zip)

I tried to get support at the mozilla forum, and was directed to file an issue here.
https://discourse.mozilla.org/t/signing-extensions-is-failing/84637/7

And I am sorry but since you asked: you should know that this golden cage approach to software distribution is atrocious, you are making yourself the arbiter of which code may run on *my* machine. You should let me sign my own software with my own certificates.

**Comment by eviljeff** [comment]
I read through the log attached.  
The first clue is that version 1.0.0 was deleted in an attempt to re-upload a version 1.0.0 - there was a warning in developer hub that deleting a version _doesn't_ allow that version number to be reused.

Then looks like you've discovered a bug in the api code where we try to build a friendly error message (the `Version already exists. Latest version is: 1.0.0` message) that errors when there isn't a non-deleted version for the add-on.  We should fix that bug.

(Any other version number would have been fine)

It appears then you deleted the add-on entirely.  Unfortunately you've discovered another bug in the signing API whereby an old deleted add-on is still recognised and used for a new upload but we don't do anything else with the upload (e.g. sign it) because the add-on is already deleted.

We should fix those two bugs, but in the mean time you've got 2 options:
- upload a version via developer hub - if you upload it as not listed on AMO (unlisted) then it's the same outcome as the signing api
- change the id to another one.

Signing is required for all add-ons used on a release version of Firefox.  Use a non-release version (Nightly, Developer Edition) and [turn off](https://support.mozilla.org/en-US/questions/1258115) the requirement otherwise.

**Comment by kmq** [comment]
I guess one more bug is that cancelling the signing process in web-ext does not actually cancel the signing process?

Uploading a new version did not work.
Uploading an extension under a new id works, but then of course that would work. 

I understand that mozilla *requires* code signing, my opinion is that  the requirement to be signed *by mozilla* means mozilla is creating yet another golden cage.
