### ISSUE TITLE
Extension Removal Issue

### ISSUE THREAD

**Issue by cootle** [mozilla/addons#1353]
### Describe the problem and steps to reproduce it: 
All extensions added on to Firefox consistently remove themselves, requiring me to constantly have to re-add them. This does not happen all at once, sometimes it is one extension at a time but it happens to each of them. 

### What happened?
After closing out of Firefox, a lot of the time, some (or all) of my extensions remove themselves from my browser. This requires me to consistently manually add them back and as this has been happening for a long while, it has become a very frustrating process.

### What did you expect to happen?
I expect my extensions to not remove themselves as this happening is very frustrating due to one of the extensions being an adblocker, and the removal of this puts both my browser and device at risk.

### Anything else we should know?
A solution of any kind would be very helpful. Thank you.

**Comment by Rob--W** [comment]
Firefox does not suddenly remove extensions. Removed extensions could be a sign of a profile corruption, commonly due to disk failures.

Did you verify that your disk is in a good state?
Do you have other software that could be interfering with the profile (e.g. modifying/removing files within the profile directory)?
