### ISSUE TITLE
Signing unavailable version bumps up extension at AMO

### ISSUE THREAD

**Issue by pintassilgo** [mozilla/addons#1364]
This AMO URL lists recently updated extensions:
https://addons.mozilla.org/en-US/firefox/search/?sort=updated&type=extension

Right now, uBlock Origin is the 3rd, but it was updated almost a month ago (1.38.6, Oct. 14).

It looks like the extension was bumped up in the list because the author just pushed a preliminary version, as you can see here:
https://github.com/gorhill/uBlock/releases

But AMO no longer allows to host preliminary version, so it doesn't make sense to change the update time of the extension if it's unavailable at AMO. So uBO shouldn't appear among recently updated extensions.

**Comment by diox** [comment]
This is because internally, the `last_updated` is updated even for unlisted versions. This was done on purpose in https://github.com/mozilla/addons-server/issues/4083, though we considered changing it back a couple times, but never did.

A way to fix this without touching `last_updated` would be to order on something else like `current_version.created` or `current_version.reviewed` (which can have subtle differences).
