### ISSUE TITLE
Add-on Validator not working properly

### ISSUE THREAD

**Issue by teo951** [mozilla/addons#137]
Add-on Validator reports in the General Tests section warnings from jquery library:
"setTimeout or setInterval must have function as 1st arg
Warning: setTimeout and setInterval functions should be called only with function expressions as their first argument"
but this library have proper checksum.
jquery-2.2.3.min.js library see add-on: https://addons.mozilla.org/en-US/editors/review/ficlab-helper
jquery-2.2.4.min.js library see add-on: https://addons.mozilla.org/en-US/editors/review/%EB%94%94%EC%8B%9C%EC%A7%88%EC%A7%88

**Comment by tofumatt** [comment]
Thanks for filing! This is a known issue and has been fixed in the code but we haven't deployed the fix yet.

https://github.com/mozilla/addons-linter/issues/744 is the original bug.

It should be deployed in two weeks (next week there is a large Mozilla all-hands and we won't be doing our usual deploy).

Sorry for the delay in deploying the fix.
