### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by fragosti** [mozilla/addons#1380]
Please attach a copy of your add-on, and fill in the following information:

[phantom-0.14.1.zip](https://github.com/mozilla/addons/files/7807776/phantom-0.14.1.zip)

<img width="968" alt="Screen Shot 2022-01-04 at 2 11 32 PM" src="https://user-images.githubusercontent.com/3066135/148064144-d32e80a0-db50-4cba-bd12-bf198fc8e062.png">

I was updating an existing add-on just now. https://addons.mozilla.org/en-US/firefox/addon/phantom-app/

Submitted at https://addons.mozilla.org/en-US/developers/addon/phantom-app/versions/submit/

**Comment by rpl** [comment]
I took a brief look into this, starting by trying to run the addons-linter locally on the zip file attached and the last xpi file signed and hosted on AMO.

While trying it on nodejs 12 (which should be the same version used to validate the submissions to AMO):

- In both cases addons-linter is unable to complete because while validating the bigger minified file (all < 4Mb, but some are nearby that limit and besides the size of the file, the complexity of the resulting AST is likely be what is triggering this) nodejs exists with a fatal error due to garbage collecting issues:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa1a640 node::Abort() [node]
 2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9a62e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9a9a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd57c25  [node]
 6: 0xd582b6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd64b75 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd65a25 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd670cf v8::internal::Heap::HandleGCRequest() [node]
10: 0xd15b35 v8::internal::StackGuard::HandleInterrupts() [node]
11: 0x1071176 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x140dc19  [node]
```

- Locally this gets triggered usually when the addons-linter gets to parse and validate either `connect_hardware.*.js` or `phishing.*.js` (both ~3.5Mb minified scripts).

- Increasing the v8 max-old-space-size to 8Gb allowed addons-linter to complete successfully without hitting the garbage collecting fatal error (```node --max_old_space_size=8192 ./bin/addons-linter /path/to/phantom-0.14.1.zip```)

- The same was happening while trying to validate the last version available on AMO (which is surprising given that it is a version that got validated successfully on submission)

I did try the same STR using nodejs 16 and the addons-linter was able to complete successfully without having to increase max-old-space-size.
 
But to be fair my local machine does have 64G of ram, the worker where the linter runs while validating the submission may have more limited resources (and so it may still not be able to complete).

**Comment by rpl** [comment]
In the meantime, as a way to avoid the issue from the extension side, if those ~3.5Mb minified files can be broken into smaller minified file, there is a good chance that this issue wouldn't be triggered.

**Comment by fragosti** [comment]
@rpl thanks for your response. Before seeing your response I ran `web-ext lint` on our `dist/` directory and ran into the same `JS_SYNTAX_ERROR` mentioned in https://github.com/mozilla/web-ext/issues/2245 and others. After updating `eslint` to v8 I was able to get `web-ext lint` passing, but still can't get my upload passing the production tests. Running `addons-linter web-ext-artifacts/phantom-0.14.1.zip` just now seems to work, with only some warnings emitted. This was all done with node 16.

**Comment by fragosti** [comment]
@rpl is there a way you can confirm this is the issue that we're seeing on AMO? It is a bit suspicious that we didn't experience this with `v0.13.3`.

Also, is there a chance we can bump the memory limitations of the workers or use node 16? We are cleanly under the 4mb limit.

**Comment by diox** [comment]
FWIW the current `max-old-space-size` on our workers is `3072`.

**Comment by willdurand** [comment]
This old bug is kinda related: https://bugzilla.mozilla.org/show_bug.cgi?id=1657880 (same symptoms and that's when we set `max-old-space-size` to `3072`).

**Comment by rpl** [comment]
In our triage meeting today we discussed further about next steps and we agreed on the following as a preferred strategy to try before consider resorting to reconfigure the limits or change the nodejs version used in the server side worker:
- Create a queue for the js files bigger than a certain MB (eg. >= 2MB) to lint then in sequence instead of in parallel (https://github.com/mozilla/addons-linter/blob/7dff1e0892a0f6615218b68d54af882cc187192f/src/linter.js#L349-L355)
- If that was not enough yet
  - look into optionally use the nodejs GC utilities (locked behind a CLI option) to run a GC pass after each big file have been linted

**Comment by diox** [comment]
The add-on validates successfully for me now, we should have closed this a while back. That being said, it contains several very big JavaScript files, so it takes a while...
