### ISSUE TITLE
Add-ons Search Detection keeps being activated

### ISSUE THREAD

**Issue by JayDevDo** [mozilla/addons#1389]
### Describe the problem and steps to reproduce it:
Add-ons Search Detection keeps being activated. Having removed the xpi from my system, added policies, removed rights, blocked for install. 
If you really want to hide something, don't show it in the task manager.

Add-ons Search Detection keeps being activated even with 
- "xpinstall.signatures.dev-root" and 
- "extensions.experiments.enabled"
set to false. (accoding to https://github.com/mozilla-extensions/addons-search-detection)

### What happened?
add on was activated on restart.

### What did you expect to happen?
not being loaded AT ALL.

### Anything else we should know?
Never do things behind your user's back. Just be open about it or go work for FB/Google/MS.

**Comment by willdurand** [comment]
This add-on is a built-in add-on in Firefox because that's how the feature has been implemented. It is similar to features like "Picture-In-Picture", "screenshot" or "web-compat" but not quite exactly the same. There is a non-obvious difference between "system add-ons" and "built-in add-ons", related to how add-ons are packaged, which is why some features appear in the list of "Firefox Features" while others like Add-ons Search Detection appear in the "Add-ons" section in `about:support` for instance.

The fact that this feature shows as an add-on is more a side effect than anything else. It started as [a standalone add-on](https://github.com/mozilla-extensions/addons-search-detection) (and was listed under "Firefox Features" back then) and got [moved in-tree](https://bugzilla.mozilla.org/show_bug.cgi?id=1735721) to avoid unnecessary extra packaging steps.

We'll likely get rid of the built-in add-on shell and move its features elsewhere in the codebase but I don't know when...
