### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by davaiyo** [mozilla/addons#1393]
* new version of an existing add-on
* add-on is listed
* The URL where you submitted the add-on: `https://addons.mozilla.org/en-US/developers/addon/localcdn-fork-of-decentraleyes/versions/submit/`
* The approximate time you submitted the add-on, with timezone: February 27th at 08:06 AM GMT+1
* [LocalCDN v2.6.24.zip](https://github.com/mozilla/addons/files/8148224/v2.6.24.zip)

**Comment by davaiyo** [comment]
Great. Still no response after 21 days. :-1: :-1: :-1: 

Is anyone monitoring this repository?? Is there even a log file where you can see the error?? As an addon developer it is really frustrating when the response time so long and developers are ignored when problems occur :angry: 

I've added the result of `web-ext lint` here in case anyone is interested: [web-ext_lint.log](https://github.com/mozilla/addons/files/8310678/web-ext_lint.log)

**Comment by diox** [comment]
Hi, 

Sorry, your issue feel through the cracks, our resources are limited and we are only humans, so answering to every issue in a reasonable time is not always possible. There is logging where we can see the error, but ultimately most cases like these are highly individual and it can take a long time to investigate each.

Please understand that your add-on is a very specific case as it is quite large and embeds a lot of code by design. Our (non-public) scanners are likely having issues parsing through everything in the allocated time, and when that happens, we unfortunately have to raise an error because we can't be sure the add-on is safe enough to be signed and used by the public. We have plans to improve this, but it won't happen overnight as it depends on large architectural changes.

The only recommendation I can offer at this time is for you to remove or split some of the larger JavaScript files in the add-on.

**Comment by davaiyo** [comment]
Hi @diox ,

Thanks for your answer. I know the situation because I am a software developer and create this addon in my free time. As a reaction, adding a badge would have been already good and would tell me "hey someone is looking at this" or a short note "takes longer because ...". Unfortunately, it's not the first time that we have to wait so long for a response. 

Thanks for your tips. Splitting up the JavaScript files won't work because those aren't mine and need to be verifiable using the audit script. I will probably have to remove that one or two. I think it would help if the timeout was increased.

About the frustration:
The current Firefox way is very frustrating. More and more telemetry and the ~~very very very slow~~ frozen approval of addons for Fenix. Missing contact to addon developers makes it all worse. It's demotivating. If the Linters modifications take as long as the Fenix addon support, then it won't be implemented for another 2 or 3 years. I don't know if Firefox will still exist then, but we'll see. I know that Mozilla has fired many developers and that the developers are not to blame. The management is just completely shitty and will probably destroy Firefox. Sorry that you have to read all this now. I don't mean you directly, but the management.
