### ISSUE TITLE
API credentials is never generated. Email with confirmation is never send

### ISSUE THREAD

**Issue by vitonsky** [mozilla/addons#1413]
### Describe the problem and steps to reproduce it:

Recently my extension [Linguist](https://github.com/translate-tools/linguist) did banned on AMO due to corruption of moderators and support are ignore my reports.

I decide to build extension package and distribute it as file, to allow firefox users use Linguist even if AMO moderators did ban the addon for money and ignore me.

I have to sign addon to users can install extension not from AMO. But on page https://addons.mozilla.org/en-US/developers/addon/api/key/ i just see text "A confirmation link will be sent to your email address. After confirmation you will find your API keys on this page. ", but i never received email with confirmation.

I think that corrupt moderator which ban my extension, may did disabled access to API for me or this may be bug.

Anyway, i don't have access to API and i even don't have buttons to send email with confirmation.

Could you fix it or give me some contacts to i can report about this abuse?

![Screenshot 2022-05-14 at 15-41-21 Manage API Keys Developer Hub Add-ons for Firefox](https://user-images.githubusercontent.com/86191922/168439326-832acfa3-e52a-41ef-9567-222ccac81823.png)

**Comment by eviljeff** [comment]
It's possible your email address is being filtered somewhere.  Please email amo-admins@mozilla.com from the appropriate email address for someone to look into it.

**Comment by mhoye** [comment]
Sir - 

While your add-on was rejected by a reviewer due to review issues, you have not been banned by AMO.

The review team is looking into it again and you should hear back from them soon. It is not clear why you did not receive the API confirmation email; having investigated, we can confirm it was sent and could not find any issues on our end. Please try visiting that page once more, and check your email inbox and spam folders. We would also like to confirm that you received emails from AMO on the review of your add-on, which again we can confirm were sent.

We ask for your patience while we look into this, and will contact you about it shortly. In the meantime, however, please understand that groundless actions of abuse and corruption will not be tolerated, and will result in a formal ban if they continue.

 Thank you,

- mhoye

**Comment by vitonsky** [comment]
@mhoye i tried generate API credentials just now, successful for this time, thank you.

I confirm that i received emails with duplicates of reviewer messages. But i still not received response for email sent 7th may to amo-admins@mozilla.com with subject "Abuse on review process". I've checked spam folder and other.

Thank you for response, i glad that you make attention and i believe that you deal with this problem and that your investigating will improve review process for all AMO contributors.

I want to addons will not more disable never for firefox users only because reviewer just don't try to build addon and press "ban" button, and then write after 7 days "You will need to upload a new version, as this one is already disabled" and mean "maybe i will enable it back, maybe no". This is absolutely unacceptable. This also harms the Linguist brand.

I will wait your response guys. Let's improve community together.
