### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by maximtop** [mozilla/addons#1418]
I can't continue the discussion with the reviewer on the page of addon disabled by reviewers. 

![image](https://user-images.githubusercontent.com/17272769/174783295-5eb9441a-28de-4302-ac09-b07484e366fc.png)

Clicking on all links (like https://addons.mozilla.org/en-US/developers/addon/58d8a144825541acbe79/edit) brings me to this page 

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/17272769/174783494-d98e56bd-1edf-40d9-9900-4577413a8026.png">

Also, I was advised to use the following links for testing.
> Please use our AMO dev environment at https://addons-dev.allizom.org/ or the AMO stage environment at https://addons.allizom.org/ for testing

But I can't get API credentials to my emails. Is it ok?

**Comment by diox** [comment]
If the entire add-on has been disabled, then it's final and you won't be able to access its developer pages, so that's expected.

> Also, I was advised to use the following links for testing.
> But I can't get API credentials to my emails. Is it ok?

dev & stage environments don't send real emails, but if you share your account id and the environment with us privately we can forward the invitation email for you to get your API credentials. You can join our [Matrix channel](https://chat.mozilla.org/#/room/#amo:mozilla.org) to discuss that further.
