### ISSUE TITLE
Graph on statistics dashboard incorrectly represents my data/statistics

### ISSUE THREAD

**Issue by RedHotRojo** [mozilla/addons#1420]
### Describe the problem and steps to reproduce it:
The numerical value of my Daily Users statistic does not match the graph it's on. I simply went to my statistics dashboard and found that the graph did not match the actual value. The actual value is 940 but point appears above the 1,000 mark. On the contrary, the matching downloads value is 22 but appears below the 20 mark.

### What happened?
The coordinate on the graph does not appear in the correct position; I had 940 daily users but the point appears above the 1,000 mark. I had 22 downloads that day but the point appears below the 20 mark.

### What did you expect to happen?
I expected the point to match the graph in terms of the y-values (daily downloads/users).

### Anything else we should know?
Here is a screenshot of my graph along where I also hovered over point to show its numerical value:
![image](https://user-images.githubusercontent.com/39638458/176573224-8b37122a-d61c-42b7-811e-3445f2c5a0cf.png)

**Comment by willdurand** [comment]
> The coordinate on the graph does not appear in the correct position; I had 940 daily users but the point appears above the 1,000 mark. I had 22 downloads that day but the point appears below the 20 mark.

Hey, looking at your graph (and despite having worked on stats in the past), I see two Y axis and two curves.

The first curve in red (-ish because I don't see colors very well) is for the number of "downloads", whose Y axis is the left one. It looks like the point highlighted (22 downloads) appears between 20 and 25 on this left axis.

The second curve is for the number of "daily users". The highlighted point indicates 940 users, and is right below the 1000 mark, so probably fine as well.

What is odd, though, and maybe the source of the issue here is: "daily users" and "downloads" in the popup are inverted and it is easy to think the curve above the other one is for the "daily users" if we don't look at the legend below the graph.

Am I missing something?

**Comment by RedHotRojo** [comment]
> > The coordinate on the graph does not appear in the correct position; I had 940 daily users but the point appears above the 1,000 mark. I had 22 downloads that day but the point appears below the 20 mark.
> 
> Hey, looking at your graph, I see two Y axis and two curves (and despite having worked on stats in the past, I never noticed the two Y axis before today).
> 
> The first curve, which is almost all the time above the other one (red-ish but I am not sure because I don't see colors very well), is for the number of "downloads", whose Y axis is the left one. It looks like the point highlighted (22 downloads) appears between 20 and 25 on this left axis.
> 
> The second curve is for the number of "daily users". The highlighted point indicates 940 users, and is right below the 1000 mark according to the Y axis on the right side of the graph, so probably fine as well.
> 
> What is odd (and maybe the source of the issue here) is: "daily users" and "downloads" in the popup are inverted and it is easy to think the curve above the other one is for the "daily users" if we don't look at the legend below the graph.
> 
> Am I missing something?

Sorry, I had my colors mixed up 🤦‍♂️
I think I got confused because the daily users was above the downloads in the pop up

**Comment by wagnerand** [comment]
> What is odd (and maybe the source of the issue here) is: "daily users" and "downloads" in the popup are inverted and it is easy to think the curve above the other one is for the "daily users" if we don't look at the legend below the graph.

This would be an easy fix that could reduce confusion.
