### ISSUE TITLE
Irrelevant search results in AMO

### ISSUE THREAD

**Issue by brisdaz** [mozilla/addons#1425]
### Describe the problem and steps to reproduce it:
1. Search for [OzBargain in AMO](https://addons.mozilla.org/en-US/firefox/search/?page=1&q=ozbargain&type=extension)

### What happened?
326 extensions results many of which don't have the keyword in it. 

### What did you expect to happen?
Only search results with the keyword ozbargain in it. 

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/search/?page=1&q=ozbargain&type=extension
![image](https://user-images.githubusercontent.com/50305553/181378366-7fd5dcea-ea49-4839-aa63-5547220eba55.png)

**Comment by smayer97** [comment]
VERY OLD Issue that Mozilla continues to ignore and justify their approach. Makes NO sense and contributes to lowering confidence in their products when you cannot control and trust the results.

**Comment by smayer97** [comment]
Not sure why my previous comment was marked as off-topic... It is not. It was to emphasize that Mozilla needs to stop de-emphasizing and outright ignoring this very important issue. 

Here is a sample of tickets that have been opened, and summarily closed, over this issue:
https://github.com/mozilla/addons/issues/1210
https://github.com/mozilla/addons/issues/1211
https://github.com/mozilla/addons/issues/1259
https://github.com/mozilla/addons/issues/1274

(https://github.com/mozilla/addons/issues/1211 also lists https://github.com/mozilla/addons/issues/1200, https://github.com/mozilla/addons/issues/905, https://github.com/mozilla/addons/issues/821, https://github.com/mozilla/addons/issues/818, https://github.com/mozilla/addons/issues/792, https://github.com/mozilla/addons/issues/783, https://github.com/mozilla/addons/issues/779, https://github.com/mozilla/addons/issues/729, https://github.com/mozilla/addons/issues/724, https://github.com/mozilla/addons/issues/695, https://github.com/mozilla/addons/issues/613, https://github.com/mozilla/addons/issues/355)
going back **over** 5 years!

Think about it this way... how many add-ons are NOT being used and how many users are abandoning searching for add-ons because the search results are so irrelevant and useless that users have no confidence in finding something useful?

After all, isn't the goal to **encourage** the adoption of add-ons and the FireFox ecosystem? FF add-ons had always been one of its key strengths. The search results actually work against this. 

See my several comments on #1259 of this matter highlighting the issues with search results.

**Comment by eviljeff** [comment]
The way the search breaks down the query string can lead to some odd results - it's got to handle misspellings and words being concatenated or not - and we'd much rather show extra results that may not match than hide potential results.  I see "OzBargin" is the top result anyway so it seems like it's working as expected.

**Comment by smayer97** [comment]
Why do my replies get marked as off-topic? They are absolutely ON-TOPIC! 

As highlighted with many examples in the thread for #1259, there are WAY TOO MANY irrelevant results that show up that make it hard to find useful results, because they are lost in the sea of extra unrelated add-ons. 

Someone really needs to look at these examples to understand the problem. Please take a careful look at this.

**Comment by smayer97** [comment]
If you continue to ignore this issue, this shows how out of touch you are with the users, and is one reason why FF has declined in popularity. One of the very things that made FF so popular is its add-ons ecosystem. 
Failing to address the shortcomings around this is to continue to not pay attention to why people are shying away from FF more and more.

**Comment by smayer97** [comment]
Why is this still closed? 

The results are EVEN LESS RELEVANT if you try to apply a filter, a sort, etc., yielding so mnay results that have NOTHING to do with the original search... 

Does anyone at Moz actually use this and/or test this? You can VERY QUICKLY see how over-engineered with little quality results this feature is. Please simplify it. Users ARE smart enough to modify their search if they do not get desired results, rather than using fuzzy logic that produces very low quality results.
