### ISSUE TITLE
Low ratings without words are senseless

### ISSUE THREAD

**Issue by Jahn08** [mozilla/addons#1429]
### Describe the problem and steps to reproduce it:
There are [guidelines on how to write reviews for addons](https://addons.mozilla.org/en-GB/review_guide) as well as a possibility to flag those not applying the criteria. However, any user can still submit an assessment without any explanation and it cannot be flagged - there is no the Flag button - even though such a random review without any comments obviously does not follow the guidelines.

### What did you expect to happen?
It makes sense either:
1. Ban the review without any words as they are definitely inappropriate and do not give any information to owners of addons. Good ratings without comments might motivate developers, whereas low ratings without text demotivate and irritate: there must be at least some information why it was submitted to make further improvements to an addon.
2. Or flag such reviews, although it is likely to introduce more manual work since people would likely flag all low assessments.

### Anything else we should know?
![image](https://user-images.githubusercontent.com/23010028/182778387-7560b068-964c-40bb-a3e6-38edff0f8779.png)

**Comment by eviljeff** [comment]
The ability to leave a rating for an add-on without also leaving a text review was added purposefully a few years ago - we used to force users to leave some text but it just resulted in a large number of nonsense reviews consisting of a single word (or a single letter).  Ratings do not really exist to motivate developers (though it's great they do); they primarily exist to provide a signal to other potential users about how good/bad the add-on is.

Ratings without text can't be flagged because there is no way for a moderator to make a judgement about if the rating is valid or not.

So, as there's not really a bug here I'm going to close this issue.  We are looking at making some changes to the rating/review system which will hopefully improve the situation in the future.
