### ISSUE TITLE
AMO: Redirect URLs improperly encoded

### ISSUE THREAD

**Issue by neeklamy** [mozilla/addons#146]
On Addons.mozilla.org (AMO), external URLs containing the ampersand character aren’t properly encoded. This can be seen on the Clean Links add-on page:

**Steps to reproduce:**
1. Go to the [Clean Links add-on page](https://addons.mozilla.org/en-US/firefox/addon/clean-links/)
2. Install Clean Links
3. Follow the “[Support site](https://outgoing.mozilla.org/v1/581ea3cffea643f0af85feab6799df90727719d390f9df4c8bc5e188a9021fd2/http%3A//forums.mozillazine.org/viewtopic.php%3Ff=48&t=2749445)” link
4. You will end up on a non-existent page: http://forums.mozillazine.org/viewtopic.php?f=48

**What’s happened:** The external site URL includes an ampersand which hasn’t been encoded

<pre>https<span>://</span>outgoing&period;moz […] topic.php%3Ff=48<b>&</b>t=2749445</pre>

**What should happen:** The external URL should be fully encoded

<pre>https<span>://</span>outgoing&period;moz […] topic.php%3Ff=48<b>%26</b>t=2749445</pre>

Following the link would then lead to the correct URL

<pre>http://forums.mozillazine.org/viewtopic.php?f=48&t=2749445</pre>

For more detail, see: diegocr/CleanLinks#127

**Comment by wagnerand** [comment]
Mentor: @diox 

Please refer to https://wiki.mozilla.org/Add-ons/Contribute if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by CuriousLearner** [comment]
Hi,
I would like to work on this bug. I was just wondering if I would also need mozilla-central clone for the addons project?

**Comment by CuriousLearner** [comment]
Hi @diox please guide me further :)

**Comment by diox** [comment]
You only need addons-server - see http://addons-server.readthedocs.io/en/latest/ - you'll need to modify python code for this.

Once you have a local instance of addons-server up and running, follow the steps to reproduce above (submit another add-on, but use http://forums.mozillazine.org/viewtopic.php?f=48 as the support site URL). 

Once you have reproduced the bug locally, try to find where it's happening. It should be in `src/olympia/amo/urlresolvers.py`, in `get_outgoing_url()`. There are tests in `src/olympia/amo/tests/test_url_prefix.py`, you can add some there.

**Comment by wagnerand** [comment]
@CuriousLearner please look at our onboarding documentation at https://wiki.mozilla.org/Add-ons/Contribute. Your initial question was already answered there.

**Comment by muffinresearch** [comment]
The bug is in outgoing issue filed here: https://github.com/mozilla-services/outgoing/issues/6

**Comment by oremj** [comment]
@bqbn deploying https://github.com/mozilla-services/outgoing/releases/tag/v1.1.0 should fix this issue.

**Comment by JustOff** [comment]
When 1.1.0 is expected to be deployed?

**Comment by muffinresearch** [comment]
@JustOff Should be out very soon as part of today's push.

**Comment by bqbn** [comment]
v1.1.0 is out. Please test it again and see if the issue has been resolved.

**Comment by JustOff** [comment]
Thank you, now all is ok!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49.0.2(Win 7).
Postfix video:  
![redirect](https://cloud.githubusercontent.com/assets/15685960/20004830/245e8706-a297-11e6-8101-6e2434b8495b.gif)

**Comment by sumyungguy** [comment]
[I'm not sure if this is a regression, but this bug is still present, at least for those using a redirect remover as in the original report. The Clean Links addon has been removed from AMO, but the problem is now the same using Skip Redirect. Here is an update to the STR:]

On Addons.mozilla.org (AMO), external URLs containing the ampersand character aren’t properly encoded. This can be seen on the ~~Clean Links~~ Easy Copy add-on page:

**Steps to reproduce:**

1. Install ~~Clean Links~~ [Skip Redirect](https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/)
2. Go to the ~~Clean Links~~ [Easy Copy](https://addons.mozilla.org/en-US/firefox/addon/easy-copy/) add-on page
3. Follow the “Support site” link
4. You will end up on a non-existent page: http://forums.mozillazine.org/viewtopic.php?f=48

**What’s happened:** The external site URL includes an ampersand which hasn’t been encoded

`https://outgoing.prod.mozaws.net [...] viewtopic.php%3Ff=48&t=2421905`

**What should happen:** The external URL should be fully encoded

`https://outgoing.prod.mozaws.net [...] viewtopic.php%3Ff=48%26t=2421905`

Following the link would then lead to the correct URL

`http://forums.mozillazine.org/viewtopic.php?f=48&t=2421905`
