### ISSUE TITLE
API keys - confirmation email wasn't sent, no way to resend email confirmation

### ISSUE THREAD

**Issue by antoniolucasnobar** [mozilla/addons#14775]
### What happened?

I'm trying to generate API key to access addon APIs using the [addons.mozilla.org -> tools->Manage Api Keys](https://addons.mozilla.org/en-GB/developers/addon/api/key/).

The page only says: API Credentials

A confirmation link will be sent to your email address. After confirmation you will find your API keys on this page. 

As web message states before generating the key I need to confirm it via email, however no confirmation email was sent to "[cids@trt12.jus.br](mailto:cids@trt12.jus.br)" (we've checked the spam and other inboxes). This might be relevant to the issue, after asking for the API key, the account email was changed from "[cids@trt12.jus.br](mailto:cids@trt12.jus.br)" to "[desenv@trt12.jus.br](mailto:desenv@trt12.jus.br)", because cids@trt12.jus.br became just an alias for desenv@trt12.jus.br.

The user id is: 17079836

We tried contact to [amo-admins@mozilla.com](mailto:amo-admins@mozilla.com) with no response. We tried also to ask for help in AMO Matrix channel, but again with no response.

### What did you expect to happen?

We expected to receive email and get API key.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-744)

**Comment by wagnerand** [comment]
@antoniolucasnobar EMail delivery to this email address has been suppressed by our vendor as previous attempts to deliver emails failed with the following error:
```
550-5.2.1 The email account that you tried to reach is disabled. 
```

I have removed your email now from the suppression list and reset the API key flow for you. Before you request new API keys, please make sure that you can receive emails, otherwise your email address will end up being suppressed again.
