### ISSUE TITLE
[Task]: Add validation errors related to enterprise channel/enterprise manifest property

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14850]
### Description

Part of [Enterprise Add-ons](https://docs.google.com/document/d/1yqnBiMyczKhgkKIwLuFQNo3eK-5Y8ORX7igEBp6Fdcc/edit) project.

Follow-up for https://github.com/mozilla/addons/issues/14849

(This likely needs to be moved to be an `addons-linter` only issue)

If an add-on is submitted to the “On this site” and “On your own” channels AND the enterprise property (`browser_specific_settings: { gecko: { admin_install_only: true } }`) is set in the manifest, validation should fail with an error message explaining the user should select the enterprise channel as a distribution mechanism on AMO.

If an add-on is submitted without the enterprise property in the manifest to an Enterprise channel, validation should also fail, with an error message explaining that this distribution mechanism is only valid if using the property.

Submissions that have both the enterprise property and an update url should be invalid (if the add-on is installed through enterprise-policy, it should also update that way)

### Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [x] Submissions using the enterprise manifest property in listed or unlisted channel should fail validation
- [x] Submissions in the enterprise channel without using the enterprise manifest property should fail validation
- [x] Submissions with the enterprise channel property and an update url should fail
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-849)

**Comment by willdurand** [comment]
> Submissions using the enterprise manifest property in listed or unlisted channel should fail validation

That was fixed by https://github.com/mozilla/addons-server/pull/22369

**Comment by willdurand** [comment]
> Submissions in the enterprise channel without using the enterprise manifest property should fail validation

This is also kinda fixed by the linter update, though without the new channel, we cannot instruct the linter to lint the add-on as "enterprise".

**Comment by willdurand** [comment]
https://github.com/mozilla/addons-server/pull/22380 is going to fix the other acceptance criteria above.

**Comment by willdurand** [comment]
Since https://github.com/mozilla/addons/issues/14849 mentions the need to pass `--enterprise` to the linter (when we have the new channel), we can close this issue now.

**Comment by ioanarusiczki** [comment]
I tried uploading again the testing samples from the [linter issues ](https://github.com/mozilla/addons-linter/issues?q=is%3Aissue+-label%3A%22qa%3Averified_fix%22+-label%3A%22state%3Awontfix%22+-label%3A%22state%3Aduplicate%22+-label%3A%22qa%3Anot_needed%22+is%3Aclosed+-label%3A%22state%3Ainvalid%22+-label%3A%22state%3Aworks_for_me%22+milestone%3A2024.06.27)on AMO dev currently with 6.31.0 and    " The "admin_install_only" property is reserved." error is present in all the attempts.

With admin_install_only:true and update_url specified in bss.gecko:
- on submit/upload-listed I get 2 errors The "admin_install_only" property is reserved and "update_url" is not allowed 
- on submit/upload-unlisted I get only 1 error about the reserved property but I think that's expected since the unlisted channel in dev hub allows update_url for all the other extensions (non-enterprise)
