### ISSUE TITLE
[Bug]: Flag for human review is no longer present after resolving only one of multiple escalations

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14872]
### What happened?

STR:
Report an extension/theme , report went to Cinder themes queue
From Cinder use Escalate to AMO (or a different one that would escalate it to AMO) 
Go to the review page observe there is an escalation
Report again , repeating steps above
In rev tools resolve one of the Escalations, not both (I tried with Ignore/Approve)

### What did you expect to happen?

The addon/theme should still be in the queue - Manual review or Updated queues

Instead the flag for human review is no longer present 

Examples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/631539
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631538
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631540

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-871)

**Comment by diox** [comment]
Original idea to fix this was to only remove the `NeedsHumanReview` flag for a given reason (abuse report, appeal, escalation) if there aren't any unresolved jobs for that particular reason. https://github.com/mozilla/addons-server/pull/22401 is a draft PR implementing that.

The problem is, https://github.com/mozilla/addons/issues/1741 gets in the way: Cinder does not create a new job for abuse reports filed while an appeal is ongoing, they get collapsed in the same job. So for the same job, we have a `NeedsHumanReview` caused by an appeal, and another one caused by reports. That creates potential edge cases depending on what jobs exist for a particular add-on and what the reviewer does. For instance, if there is a job for a regular report and another for an appeal at the same time for whatever reason (no guarantee this can't happen):
- (if we go with the implementation currently in `master`) if the reviewer resolves only the appeal job, we clear all NHR for both reasons, then the job corresponding to the regular report is stranded, never resolved as the add-on would no longer appear in the queue
- (if we go with my PR implementation above) if the reviewer resolves only the regular report job, and then another report is filed, that new report will be attached to the appeal job, creating a new NHR for abuse violation. If then the reviewer resolves the appeal job - the only job they see is left - we clear all NHR for only the appeal reason, but that leaves a NHR for abuse violation reason that would never be cleared.

Potential workarounds I see:
- Ask Cinder never to add new reports to existing appeal jobs (it seems intended though)
- Force reviewers to resolve all jobs at once instead of picking and choosing
- Use my approach, but in addition check that there are no outstanding jobs left and clear any leftover NHR for abuse report violations if that's the case
- Use my approach, but never add new NHR for abuse violation reason if there is an ongoing appeal
- Find a way to link the NHR to the CinderJob and only clear the relevant NHR when a given job is resolved

**Comment by diox** [comment]
> Original idea to fix this was to only remove the NeedsHumanReview flag for a given reason (abuse report, appeal, escalation) if there aren't any unresolved jobs for that particular reason
> (...)
> Use my approach, but never add new NHR for abuse violation reason if there is an ongoing appeal

We're going with this.

**Comment by ioanarusiczki** [comment]
I tried some tests with multiple escalations, multiple appeals for an [extension](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/631742#review-actions) and for a [theme](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631741).

Verified on -dev.
