### ISSUE TITLE
Unable to submit a regular update after a higher version has been submitted even if it's been deleted

### ISSUE THREAD

**Issue by danny0838** [mozilla/addons#1489]
### Describe the problem and steps to reproduce it:
1. Submit version `1.4.0` of an add-on.
2. Submit a beta release `2.0.0b1` of the add-on.
3. Delete `2.0.0b1`. (As the add-on store unfortunately doesn't support beta release and the users are forced to auto updated to the unstable beta release.)
4. Submit version `1.4.1` of the add-on.

### What happened?
Version `1.4.1` cannot be submitted, with a reason that its version must be higher than the last submitted version `2.0.0b1`.

### What did you expect to happen?
Version `1.4.1` should be submit-table if all higher versions have been deleted.

**Comment by diox** [comment]
Sorry, this was a conscious decision because Firefox doesn't upgrade to a lower version number than the one installed, so it was confusing to some developers (https://github.com/mozilla/addons-server/issues/19788).

While we don't currently have proper support for beta versions, you can emulate that by submitting self-hosted versions, see https://extensionworkshop.com/documentation/publish/distribute-pre-release-versions/ for more details. I know it's not ideal, we are looking into adding back beta versions sometime in the future (it used to be a feature, but it was rarely used and came with a lot of edge cases).

**Comment by danny0838** [comment]
I understand the decision of disallowing a submission of a version lower than the **current public version**. But this does not answer this issue as the problem is that the higher version has been deleted and is no more the current public version.

**Comment by danny0838** [comment]
I don't think a deleted version is the **current public version**. A deleted version is usually an erroneously submitted or yanked version and should be ignored.

The current behavior forces  the developer to release a major release for even a patch release if he has been erroneously updated a higher version. This is bad for the semantic of the version and is very bothering for both the user and the developer.
