### ISSUE TITLE
[Bug]: Cannot send reports for dictionaries from Firefox Nightly after they're being installed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14896]
### What happened?

1. With FF Nightly 129.0a1 go to a dictionary https://addons.mozilla.org/en-US/firefox/feedback/addon/bambarabamanakan/
2. Send reports 
3. Install the dictionary and try to send reports again : try from both places, the detail page or from addon manager

### What did you expect to happen?

An error occurs on 129.0a1 - reproducible on prod

![unexpected error](https://github.com/mozilla/addons/assets/33448286/6bc4b470-bfe3-4092-9aa6-5af66c6b6052)

This is not reproducible on Firefox Release - 127.0.2

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-901)

**Comment by KevinMind** [comment]
@ioanarusiczki is it relevant or important which fields are selected in the abuse report? Could you clarify that in the ticket?

**Comment by ioanarusiczki** [comment]
@KevinMind it's not important what option you choose, just make sure a reason is checked together with the rest of the mandatory fields.

**Comment by KevinMind** [comment]
Thanks 🙏 . FWIW that is itself relevant information. For future tickets, If it is not important what fields to select could you specify that in the STR. Otherwise there is no way to know if an error occurs due to the identified bug or because form submission X has different fields than form submission Y. Just stating that the field selections are irrelevant would have been enough for me.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF129.0a1.
