### ISSUE TITLE
[Bug]: Cannot submit an abuse report 

### ISSUE THREAD

**Issue by alexandruschek** [mozilla/addons#14917]
### What happened?

Repro Steps:

1. Go to the detail page of an add-on
2. Press report
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/122a5df5-85a9-4e65-b29a-09b14e7fab0e">
3. The "Unexpected error" message appears after submission
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/c57e7c24-85a9-45fb-af78-c2a61e8f24d0">

Notes:
If the report is submitted anonymously, then the report is submitted without issue.

### What did you expect to happen?

To submit the report.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-928)

**Comment by wagnerand** [comment]
@alexandruschek is that happening on stage? Could you give us the date and time you experienced this?

**Comment by alexandruschek** [comment]
It happens both on -DEV and -STAGE environments. It happened around 15-16 hours ago.

**Comment by diox** [comment]
When using Firefox, AMO will try to use the `sendAbuseReport` JavaScript API, which makes the HTTP request to AMO API from the browser. It uses the `extensions.addonAbuseReport.url` pref to know which server to contact, so this needs to be set to point to dev/stage when testing those environments.

Setting the pref correctly fixes the issue for me. The error was `Reporting add-on for abuse failed: Error: ERROR_CLIENT - {"status":401,"responseText":"{\"detail\":\"Valid user session not found matching the provided session key.\",\"code\":\"ERROR_AUTHENTICATION_EXPIRED\"}"}` and the request could be seen using the Browser Toolbox Network tab (*not* the regular developer tools - since the request is made by the browser internally)
