### ISSUE TITLE
[Bug]: Compatible versions of GNOME browser extension are not offered to Firefox 115 ESR users

### ISSUE THREAD

**Issue by nE0sIghT** [mozilla/addons#14912]
### What happened?

Recently I uploaded version 12 of GNOME browser integration [1] extension to AMO with MV3 support and minimum supported Firefox version 126.
While older 11.1 version is supported by Firefox 115 ESR it doesn't offered by AMO to users with "You need an updated version of Firefox for this extension" message while 11.1 version can be installed via "See all versions" link [2].

This behavior doesn't looks friendly to ESR users. Is there any way to provide extension to ESR users as well without hard-to-find "See all versions" link?

![image](https://github.com/user-attachments/assets/2b136269-77cb-4940-af03-0f7c96683884)

[1] https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/
[2] https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/versions/

### What did you expect to happen?

Version 11.1 of GNOME browser extensions is offered to ESR users

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-922)

**Comment by eviljeff** [comment]
Unfortunately, no. AMO's architecture only supports a single "current version", which is the version that's offered to all website visitors, with browser compatibility checked against it.

There are non-optimal workarounds, such as using the all versions page like you suggest, or hosting/linking the xpis for ESR users on your own website.

Closing because this would only be fixed with a significant reimplementation of AMO, which isn't on the short term roadmap.
