### ISSUE TITLE
[Task]: Review Queue Filtering for DSA Abuse Reports

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#14921]
### Description

When the DSA abuse report queues are re-enabled, there will be a high number of new reports in the AMO review queues. Want to address those at a lower priority than new add-on reviews.

Possible solution: a simple filter button to show only one of those two “categories.”

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Filtering option available for DSA abuse reports
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-933)

**Comment by chrstinalin** [comment]
@wagnerand For context: this (and #14920) are mostly regurgitated from a one-on-one with Shane. Andrew recommended pinging you to confirm they looked right.

Would it be a single toggle for all DSA types under 'Needs human review'? Or individual toggles for each type of human review (appeals, abuse reports, escalations...)?

**Comment by diox** [comment]
As discussed on slack, this is not as trivial to implement as it may seem.

A key problem is that for this to work you'd need to be able to exclude add-ons that are exclusively in the queue because of abuse reports, and nothing else. The current database structure isn't meant to do this sort of query in a performant way: the queue was explicitly designed to be unified without caring about the reasons that led to something being added to the it.

https://github.com/mozilla/addons/issues/9520 added flags to distinguish add-ons flagged from abuse, but this wouldn't help here as there might be another reason for the add-on to be in the queue.

There are multiple approaches we could look at to fix this issue but it'd require careful planning and consideration to be performant while not compromising maintainability of the code.

**Comment by diox** [comment]
@eviljeff so submit a draft PR of an idea we need to investigate for this

**Comment by ioanarusiczki** [comment]
Definitely something not right because I don't see the changes from https://github.com/mozilla/addons-server/pull/22558 on AMO dev.
