### ISSUE TITLE
[Task]: Show all authors in top author list on the review page 

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14923]
### Description

On the review page at the top (underneath the add-on name), the list of "listed" author is shown. That list should show *all* current (=non-deleted) authors instead, we can mark the listed ones in bold and non-listed ones in regular font weight. (Another way to distinguish between listed and non-listed can also be discussed.)

<img width="861" alt="Screenshot 2024-07-26 at 11 59 55" src="https://github.com/user-attachments/assets/8fecd555-b338-495b-810d-2450a05197f6">

### Acceptance Criteria

```[tasklist]
  - [ ] In the authors list at the top of the review page, all current authors should be shown, not just listed ones. They should be visually distinct from each other, using bold and regular font-size.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-941)

**Comment by diox** [comment]
In the template, we currently go through the property `listed_authors` that is prefilled by the default `transformer` for add-ons, which is called automatically when the ORM fetches add-ons. Since we want more than listed authors, this would make an extra database query, but this is probably ok.

`Addon._attach_authors([addon], listed=None, to_attr='current_authors')` can be used in the view to add a `current_authors` property to the `addon` instance. From there, iterating on it in the template should give you `UserProfile` instances just like `listed_authors`, with `role` and `listed` properties set on them.

**Comment by ioanarusiczki** [comment]
I also see these changes on AMO dev 

![authors in rev tools](https://github.com/user-attachments/assets/215c30a7-f00b-4669-aca0-6970ad5f4877)

on the listed review page
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/621541
or unlisted review page
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/621541

Only listed authors are visible on frontend pages
https://addons-dev.allizom.org/en-US/firefox/addon/youtuberecommendedvideos_test/
