### ISSUE TITLE
[Bug]: unauthenticated abuse reports don't hit the throttle

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14931]
### What happened?

I'm trying to test a couple of throttles on -dev for[ Fastly ](https://mozilla-hub.atlassian.net/browse/OPST-670) 

I tried from AMO dev frontend, without authentication, and after 20 + attempts I've noticed that I can continue sending reports.

So I tried the following:
sent 20+ requests from https://httpie.io/app for https://addons-dev.allizom.org/api/v5/abuse/report/addon/?lang=en-US 
with a Session id -> I get a 429 {"detail": "Request was throttled. Expected available in 85984 seconds."} 
Once I remove the authentication I can continue sending new reports.

Same is reproducible on -stage. 

### What did you expect to happen?

I should hit a 429 without authentication too.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-948)

**Comment by diox** [comment]
@ioanarusiczki If you are testing from a third party service like https://httpie.io/app that would explain the problem: there is no guarantee they'd be using the same IP for all requests. You can see the IP used by making a request to https://addons-dev.allizom.org/services/client_info and looking at the `REMOTE_ADDR` (it's not enabled on stage, but it can confirm that httpie.io is not using the same IP for all requests)

**Comment by ioanarusiczki** [comment]
Confirming that. I modified extensions.addonAbuseReport.url, using `https://addons-dev.allizom.org/api/v5/abuse/report/addon/` instead of `https://services.addons-dev.allizom.org/api/v5/abuse/report/addon/` , 
sent new reports and I see the country codes being present.

**Comment by ioanarusiczki** [comment]
I used to test this making unauthenticated requests with abuse report add-on endpoint from Postman and I remember hitting throttle but I left third party apps aside and tried using the frontend:
- 20 reports on a user -> I am hitting the throttle

<img width="1469" alt="throttle" src="https://github.com/user-attachments/assets/d875e534-d4bc-4337-b58a-2b93f264763b">


- then  I could not continue reporting a rating or a collection because I hit the throttle after the 20+ reports on the user

![collections](https://github.com/user-attachments/assets/96da3a47-90a6-4ecf-93c7-bdb513a4f61a)

<img width="1465" alt="ratings" src="https://github.com/user-attachments/assets/7d2c3ea4-f92c-4c85-bbe4-54feb6d32f0e">

But when I try reporting an extension or a theme I can continue reporting.
Same scenario applied on stage has the same results so I think the problem is only with the addon abuse reports endpoint when user is anonymous.

**Comment by diox** [comment]
We chatted about this and discovered it was caused by `extensions.addonAbuseReport.url` not being set correctly.

Digging further though:
- On dev, throttling does seem broken atm specifically for [services.addons-dev.allizom.org](http://services.addons-dev.allizom.org/) requests only. Probably related to Fastly changes, need to investigate more. It's possible we're not passing the `REMOTE_ADDR` correctly, or that the cache is simply separate for `services` endpoint (so submitting abuse against other types would not count towards the limit for submitting abuse against add-ons).
- Everywhere, for add-on abuse only, sometimes we get "An unexpected error occurred" instead of the "Request was throttled" error, but the report isn't posted anyway. That's a minor UX issue, probably related to how we send the report through Firefox `sendAbuseReport` API.

**Comment by diox** [comment]
With https://github.com/mozilla/addons/issues/14929 fixing the first item from my comment above we should be ok now.

**Comment by ioanarusiczki** [comment]
Verified on -dev and filed the other problem https://github.com/mozilla/addons/issues/14959

![frontend error instead of 429](https://github.com/user-attachments/assets/c38c7245-6b69-4cad-ba0e-5456c88c6cf8)

I see the 429 with browser toolbox 

![429 on dev](https://github.com/user-attachments/assets/8855eca9-2e37-4181-ae20-226c74ef9e47)
