### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by dindoun** [mozilla/addons#1495]
hi,
when I do a search with the name firebug, it says 8 217 résultats pour « firebug but I can't see the word firebug

### What did you expect to happen?
to see the word firebug or zero ( no ) result

https://addons.mozilla.org/fr/firefox/search/?q=firebug

**Comment by eviljeff** [comment]
There is a theme with the word "firebug" in it's name right at the top of the results.

Search inputs are broken down into smaller parts of words ("trigrams", technically) because users don't always know the exact wording the developer has used - "firebug" will be returning a lot of results because "fire" and "bug" are common words used in add-ons for Firefox.  If there _is_ an exact match, then it's pushed further up the results, but there isn't in this case (other than the theme I mentioned).  

Closing because wanting to _only_ return exact matches for a search term isn't a common use-case.
