### ISSUE TITLE
[Bug]: 500 server errors on some sorting options in rev tools

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14961]
### What happened?

While testing https://github.com/mozilla/addons/issues/14935 I've noticed some sort options throwing 500 server errors

In Manual Review Queue for Maliciousness Score
In Pending Rejection Queue for Metadata Weight, Total Weight and Maliciousness Score

### What did you expect to happen?

this is reproducible on both -dev and -stage

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-981)

**Comment by diox** [comment]
This is an old issue which has been happening since the queues were merged last year in https://github.com/mozilla/addons/issues/8995.

The problem is that for those fields, the value is coming from the "first" pending version, which is computed separately from the main query. When we try to sort on any of them, we're asking Django ORM to sort on a field that doesn't exist on the main query...

To fix this is annoying: each add-on in the queue might have multiple versions pending review, so you can directly sort, if we want to keep the sort functionality we would probably need to expose each of the fields as annotations, and use those annotations for the sort. Or we could prevent sorting on these fields altogether.

**Comment by diox** [comment]
@wagnerand do reviewers need the ability to sort on these columns ? Do they even need those columns ?

**Comment by wagnerand** [comment]
We can remove all of those columns.

**Comment by diox** [comment]
Reviewers don't currently look at these columns, so we can remove them entirely.

**Comment by ioanarusiczki** [comment]
I see the changes on AMO dev.
