### ISSUE TITLE
[Task]: Re-create the cinder job on receiving AMO_ESCALATE decision

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#14970]
### Description

part of https://mozilla-hub.atlassian.net/browse/AMOENG-961 where we are changing how escalations in cinder work.  We want to more accurately represent an escalation to AMO reviewers from cinder, similarly to how workflows work in cinder - by recreating a new cinder job on the back of the old job.

There shouldn't be any change in functionality.

The terminology in AMO has also changed to "Forwarded", to differentiate the other types of escalation.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A cinder job can be escalated/forwarded to AMO from cinder with the same "Escalate to AMO" policy/action
  - [ ] Existing escalated/forwarded jobs are still seen as a escalated/forwarded
  - [ ] Terminology in the reviewer tools is "forwarded" rather than "escalated"
  - [ ] A replacement job is created in cinder, in the Content Infringement queue, for the forwarded job
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-991)

**Comment by eviljeff** [comment]
note: there is a backfill command that needs to be run.  I will run on addons-dev; stage will need to done after the tag, and prod by SRE after the deploy.

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know if I can try to test this.

I'm thinking I must go through all possible scenarios using escalations and check the decisions tab in Cinder to see there if a new job has been created ?

**Comment by eviljeff** [comment]
> @eviljeff Let me know if I can try to test this.
> 
> I'm thinking I must go through all possible scenarios using escalations and check the decisions tab in Cinder to see there if a new job has been created ?

I'm not sure if the job will be in the decisions tab, but after escalating there should be a new job in the Content Infringement queue (just as there would have been if the job had originally been routed to AMO reviewers rather than cinder moderators).

Also, confirm that resolving escalated jobs via the reviewer tools still works (email goes out, NHR cleared, etc), so that I didn't regress https://github.com/mozilla/addons/issues/14906

**Comment by ioanarusiczki** [comment]
- I tried escalations for listed extensions and themes from their detail pages and used disable/enable for rev tools (since there is a problem with manual approvals I could not try reject + approve).  Went through scenario 1-4 (described [here](https://mozilla.testrail.io/index.php?/suites/view/49792&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)) and escalated reports then appeals from Cinder -> looks good, every time a job showed up in the content infringement queue and once a decision was taken from rev tools it was closed.

- I tried the scenario from https://github.com/mozilla/addons/issues/14906#issue-2398045875. I've noticed that new reports sent are no longer present in rev tools under the appeal forwarded from Cinder. Also when I try reporting again after the appeal was resolved (with deny appeal) , I did not see these new reports going to Cinder. Not sure about what's expected here, I'll still look around once again tomorrow.

- I also tried multiple escalations from https://github.com/mozilla/addons/issues/14872 and noticed a different behavior. While the first escalation is still unresolved in rev tools, forwarding a new report from cinder will go under the first escalation and all can be resolved by making a single decision from rev tools. Meanwhile in Cinder is one job opened for the add-on in the Content Infringement queue. I think it looks better than before.

**Comment by ioanarusiczki** [comment]
I checked again https://github.com/mozilla/addons/issues/14906#issue-2398045875 (point 2 from my comment above) and I've noticed that reporters get an email immediately after sending new reports

![mail sent to reporters](https://github.com/user-attachments/assets/7572921f-0c8a-4b30-9944-331c4033fe1d)

I don't see these reports anywhere in Cinder or rev tools but I assume that's alright as long as this email is received. According to https://github.com/mozilla/addons/issues/14894#issuecomment-2253094043

Filed https://github.com/mozilla/addons/issues/15001. I see that reports forwarded from Cinder with reports that go straight to rev tools are combined under one job in Cinder and AMO, so one decision is made for all of them but there might be something about clearing the human review flag.

If you need a change (that's UX) - to make the text clickable in the DSA section too (works on Approve, Deny actions), I could file a followup

![clickable text](https://github.com/user-attachments/assets/5e474358-613b-422d-a048-8af4f570f721)
