### ISSUE TITLE
[Task]: Add new sentence to the email template for unlisted auto-approved rejections

### ISSUE THREAD

**Issue by iulianacse** [mozilla/addons#14974]
### Description

As approved by Legal, the following sentence should be added to the email template for unlisted auto-approved rejections:

`Please provide a resolution to aforementioned issues within 14 days. After that time, non-compliant versions are subject to being blocked by Mozilla.`

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Add sentence to the email template
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-995)

**Comment by wagnerand** [comment]
Adding at the end of that template sounds good. I think the days being dynamic is not something that was considered, but it makes sense. It should be the rejection delay, yes.

**Comment by eviljeff** [comment]
@wagnerand I'm unclear now if this issue is about delayed rejections, or immediate rejections.  Can you clarify?  (If it's immediate rejections - what I initially assumed - there isn't a number of days specified in the reviewer tools.)

The proposal is to add:
> Please provide a resolution to aforementioned issues within 14 days. After that time, non-compliant versions are subject to being blocked by Mozilla.

The immediate rejection template says (if the version isn't being blocked at the same time):
> Based on that finding, those versions of your {{ type }} have been disabled on {{ target_url }} and are no longer available for download from Mozilla Add-ons, anywhere in the world. Users who have previously installed those versions will be able to continue using them.

And the template for delayed rejections says:
> Based on that finding, those versions of your {{ type }} will be disabled on {{ target_url }} in {{ delayed_rejection_days }} day(s). Once disabled, these versions will no longer be available for download from Mozilla Add-ons, anywhere in the world, but any compliant versions will remain in place, and you may choose to upload a new version that addresses the policy violation. Users who have previously installed the disabled versions will be able to continue using them.

In either case, that makes some of the earlier text contradictory because blocking _will_ make the disabled versions unusable for existing users, so I think they need rewording.

**Comment by wagnerand** [comment]
I've aligned with Iuliana and Abhi to close this ticket and give it some more thought. We'll draft internally first to make sure we come up with an accurate and non-conflicting approach.
