### ISSUE TITLE
[Bug]: AMO dev: activity log is recording Fastly IPs

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#14977]
### What happened?

I tried the following: login, editing a rating, submitting a version from dev hub or API. 

There's various IP Addresses coming from Fastly when looking at REMOTE_ADDR
https://addons-dev.allizom.org/services/client_info or https://addons-dev.allizom.org/services/client_info

### What did you expect to happen?

It should register a user's IP public address.

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1000)

**Comment by diox** [comment]
`services.addons-dev.allizom.org` returns the right `REMOTE_ADDR` for me and @ioanarusiczki.

The difference is that when making a request to `services.addons-dev.allizom.org`, the `HTTP_X_FORWARDED_FOR` contains 3 IPs. When we make a request to `addons-dev.allizom.org`, it contains 4.

@bqbn can you see why that is the case ? For requests coming from the CDN, We expect to see 3 IPs at all times: `<client IP>`, `<CDN IP>`, `<GCP IP>` in that order. Here for `addons-dev.allizom.org` it seems we're seeing 2 different IPs belonging to Fastly in the chain, so we pick the wrong one.

**Comment by bqbn** [comment]
This is a side-effect of fixing the slow download speed for non-cached files, discussed in https://mozilla-hub.atlassian.net/browse/OPST-670. While fixing that issue, we also fixed the mis-configured shielding feature. The newly appeared Fastly IP is the IP of the shielding POP.

Shielding is explained here: https://www.fastly.com/documentation/guides/concepts/shielding/

**Comment by diox** [comment]
So, I see 2 solutions then.
1. Either we use https://www.fastly.com/documentation/reference/http/http-headers/Fastly-Client-IP/ (noting that we need to properly set it in VCL to prevent users from setting it)
2. Pass some additional header (also protected in a similar way so that only us can set it) when going through a shielding POP so that addons-server backend can take that into account when parsing `HTTP_X_FORWARDED_FOR`.

That second option with the additional header has the benefit of being flexible, it slots nicely in the existing logic we have.

**Comment by bqbn** [comment]
Can you use only the first IP address in the `HTTP_X_FORWARDED_FOR` header without considering how many IPs it contains?
In the case of Fastly, if an edge POP determines that a shielding POP is unavailable for any reason, the edge POP may fetch directly from the origin. In that scenario, there would be only 3 IP addresses in the header.

**Comment by bqbn** [comment]
That said, I think using the code in https://www.fastly.com/documentation/reference/http/http-headers/Fastly-Client-IP/ makes sense. Note that we can set a header of our choice and because the code runs on the edge, the client forged value will always be overwritten by our code, which is the "true" client IP.

**Comment by diox** [comment]
> Can you use only the first IP address in the `HTTP_X_FORWARDED_FOR` header without considering how many IPs it contains? 

We can't just pick the first IP, because if the client passes the header, the value they provide is prepended in what we receive:
```
curl -sH 'X-Forwarded-For: 1.2.3.4' https://addons-dev.allizom.org/services/client_info | jq .HTTP_X_FORWARDED_FOR
"1.2.3.4, {myip}, 140.248.84.33, 167.82.142.60, 34.107.180.235"
```

> In the case of Fastly, if an edge POP determines that a shielding POP is unavailable for any reason, the edge POP may fetch directly from the origin. In that scenario, there would be only 3 IP addresses in the header.

I see... We could [detect we're shielding](https://www.fastly.com/documentation/reference/vcl/variables/backend-connection/req-backend-is-shield/) and pass some extra header down that addons-server could look at to determine the proper position of the actual client IP in `HTTP_X_FORWARDED_FOR` ?

> That said, I think using the code in https://www.fastly.com/documentation/reference/http/http-headers/Fastly-Client-IP/ makes sense

Or this, yes. I have a slight preference for the extra header that just indicates we're shielding though, to keep the existing logic that fetches the IP from `HTTP_X_FORWARDED_FOR` by just determining where it should be in it from the left.

**Comment by bqbn** [comment]
Please see https://github.com/mozilla-it/webservices-infra/pull/2261/commits/89f1f0d87f16beb6fdebd93146d9e8e9fa761a43.

I added a header called `x-amo-request-shielded` to indicate if a request is shielded or not. Its value should be "true" unless  the shielding POP is unhealthy or a client request is hitting the shielding POP directly because the client is close to the shielding POP.

Let me know if that works for you or not.

**Comment by ioanarusiczki** [comment]
I verified again:
- admin user restrictions
- activity log at version submissions, ratings, developer replies, login , api submission.
- didn't see ip registered at patch operations or from dev hub making addon changes on detail/versions (but it's the same on -stage)

I'll take one more look into [activity log](https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/) on Monday (check something against stage). 

But https://addons-dev.allizom.org/services/client_info and https://addons-dev.allizom.org/api/v5/services/client_info show the correct ip address for me 👍
