### ISSUE TITLE
XPI ZIP format is not standards compliant, invalid timestamp data

### ISSUE THREAD

**Issue by gdevenyi** [mozilla/addons#1498]
### Describe the problem and steps to reproduce it:
Using ansible to download/extract an XPI file, it fails, due to invalid timestamp data, bug report for ansible here:
https://github.com/ansible/ansible/issues/81092

I have tested with more than one XPI file from addons.mozilla.org and they have the same broken timestamp.

### What happened?
XPI's invalid ZIP format triggers errors in other applications

### What did you expect to happen?
Timestamps to be correct

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
Hi,

I'm not very familiar with ZIP format internals but I'm not so sure our zips have invalid timestamps.

[ZIP format spec](https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html) dictates the timestamps are stored as MS-DOS timestamps with 2 bytes for time, 2 bytes for date, at offset `0xa`,`0xb` and `0xc`,`0xd` respectively for each file header, and optionally in an extended timestamp format stored after the filename with a 2 bytes identifier (`0x5455`) followed by 2 bytes size followed by the extended timestamp data.

Here is the hexdump for the beginning of `ublock_origin-1.50.0.xpi` showing the
first local file header:
```
00000000  50 4b 03 04 14 00 08 00  08 00 00 00 00 00 00 00  |PK..............|
00000010  00 00 00 00 00 00 00 00  00 00 0f 00 00 00 31 70  |..............1p|
00000020  2d 66 69 6c 74 65 72 73  2e 68 74 6d 6c a4 57 cd  |-filters.html.W.|
00000030  72 e3 36 0c be fb 29 58  1e 7a aa c2 cd 6d 67 2b  |r.6...)X.z...mg+
```

You can also see that header in Python with `zipfile.ZipFile('ublock_origin-1.50.0.xpi').infolist()[0].FileHeader()`.

There is no extended timestamp, and the MS-DOS time & date fields are both at `0`. Is that invalid ? I don't know, is that specified ? It's not an attempt at storing a super old date, it's just the default values the zip got when it was created by [our signing service](https://github.com/mozilla-services/autograph/), which is written in Go. Perhaps an issue with the way the go `archive/zip` module creates archives by default ?

I'm surprised ansible is choking on it, as I can read and extract the zips just file with Python or `unzip`. In any case we're unlikely to change this behavior in the near future, since it's working for us in the contexts we're using XPIs, and it's been that way forever.
