### ISSUE TITLE
[Task]: Unlisted add-on versions should exceed report thresholds before they are reviewed

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14985]
### Description

Unlisted add-on versions are not subject to Digital Services Act legislation as Mozilla/Firefox does not host any of the content or add-ons. Due to this, we want an unlisted add-on version to appear in the review queue once it exceeds the existing agreed thresholds for reports.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Abuse reports for unlisted versions should not be sent to Cinder.
  - [ ] Abuse reports for unlisted versions should not enqueue the version in the AMO Reviewer Tools queue.
  - [ ] Given the existing (pre-DSA) abuse-reports signal, once an add-on crosses the threshold, the unlisted version should be flagged for human review.
  - [ ] Abuse reports for unlisted versions are not exposed in the DSA section of abuse reports and appeals on the reviewer tools page. Consequently, they are excluded when resolving abuse reports.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1010)

**Comment by ioanarusiczki** [comment]
I reported unlisted add-ons from https://ioanarusiczki.github.io/ -> test 1 and test 2 , these are signed by Mozilla and then uploaded on the website to simulate an abuse report when unlisted versions are signed then distributed by a developer. 

I reported them for add-on Policies or other reasons (that previously were sent to Cinder). All reports went to admin tools -> Abuse report module.  This is [an example](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/30419/change/). None of the reports were registered in Add-on infringement queue or Add-on listings in Cinder. Also not available in the Manual Review queue on AMO when reported for add-on policies (inside the add-on or both locations).

But I should also test that when a threshold is crossed these versions should be flagged. @eviljeff I don't know anything about this, I need some info.

**Comment by eviljeff** [comment]
Just to confirm, listed versions still work; reports without a version still work (e.g. when the add-on isn't installed in the user's browser at the time they report it); non-addon reports still work.

> But I should also test that when a threshold is crossed these versions should be flagged. 

No, that's the just the existing cron job that flags add-ons for high abuse reports - we've not touched that ([yet](https://github.com/mozilla/addons/issues/14993)).

**Comment by ioanarusiczki** [comment]
> No, that's the just the existing cron job that flags add-ons for high abuse reports - we've not touched that (https://github.com/mozilla/addons/issues/14993).

Ok, then that's the bridge I'll cross later.

Been looking over reports, now I understand what "without a version" means , that's how most of my testing is done so no problems here. 

I got all reports for installed versions or themes too. A note to make, Cinder would always display the latest version of an add-on even when an older version was reported. It is displayed correctly in rev tools however when such a report is escalated to AMO. Also the correct version is displayed in the manual review queue when reported for add-on policies.  I think I've seen this before even filed it (not sure though). 

Reporting non-addons - worked.

Reporting an add-on with mixed versions:

- when reporting the unlisted version installed, this is not present anywhere (only in admin tools), listed is ignored.
- when reporting the listed version installed I see it being flagged for review in rev tools, the unlisted is ignored.
- when reporting without a version, both listed and unlisted versions are flagged for human review. I am not sure here, should the unlisted be ignored because of the threshold now ? (or this only applies to purely unlisted)

**Comment by eviljeff** [comment]
> when reporting without a version, both listed and unlisted versions are flagged for human review. I am not sure here, should the unlisted be ignored because of the threshold now ? (or this only applies to purely unlisted)

Mmm, the flagging logic when the report _is_ sent to cinder hasn't changed but you've got a point - maybe we shouldn't be flagging the unlisted versions for NHR any longer.  Can you file a follow-up issue so Andreas and Alan can make a decision on it?

**Comment by ioanarusiczki** [comment]
Ok, I filed it https://github.com/mozilla/addons/issues/15010
