### ISSUE TITLE
[Task]: Do not include DSA abuse reports in aggregates that have been decided on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#14993]
### Description

Abuse reports that apply to DSA and have been decided on by a human should not be included in the aggregate considerations.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Abuse reports that apply to DSA and have been decided on by a human should not be included in the aggregate considerations. 
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1018)

**Comment by eviljeff** [comment]
Some clarifications @wagnerand:
- Should reports be excluded them from the calculations only _after_ they've been resolved with a decision?  (the alternative is excluding all reports that _should_ be manually reviewed - but may not have been at the time).  
  - The former would mean when we're backlogged with reports we don't miss problematic content; the latter is perhaps more accurate, because there would be no overlap between reports that are DSA relevant, and reports that are considered in aggregate.
- If we're only considering reports with decisions, does any decision count, including non-decisions like `AMO_IGNORE`, for invalid/misfiled reports?  
  - (what about `AMO_CLOSED_NO_ACTION`, which is used when content is already disabled - although I'm not sure you would be reviewing those add-ons anyway?)

**Comment by wagnerand** [comment]
> Some clarifications @wagnerand:
> 
>     * Should reports be excluded them from the calculations only _after_ they've been resolved with a decision?  (the alternative is excluding all reports that _should_ be manually reviewed - but may not have been at the time).
>       
>       * The former would mean when we're backlogged with reports we don't miss problematic content; the latter is perhaps more accurate, because there would be no overlap between reports that are DSA relevant, and reports that are considered in aggregate.

We should do the latter. If we already ran into a backlog issue, surfacing more add-ons from aggregation won't help with the backlog, but will just increase and doesn't lead to those being handled any faster.


>     * If we're only considering reports with decisions, does any decision count, including non-decisions like `AMO_IGNORE`, for invalid/misfiled reports?
>       
>       * (what about `AMO_CLOSED_NO_ACTION`, which is used when content is already disabled - although I'm not sure you would be reviewing those add-ons anyway?)

In terms of decisions, it's hard to make the perfect decision upfront. I'd lean towards including invalid/misfiled/non-actionable reports in the aggregation, but if we see a lot of add-ons being enqueued over and over again for this, we might have to reconsider that. Might be worth keeping that in mind for the implementation in case we need to change it later.
Reports for content that is already disabled should not be included in the aggregation.

**Comment by ioanarusiczki** [comment]
I tried understanding https://github.com/mozilla/addons/issues/9221 first, because I needed to establish the minimum number of reports that would make an addon be flagged. 

There's not too many addons on dev with ADU but what I could find for an unlisted version is

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/619960 -> I reported it once with version 3.0 installed (ADU is 5 so I think it should be reported once to be flagged)

I also reported once a [listed version ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/502955) , the report is open and went to Cinder. (ADU is 9, so it should take one report to be flagged). I want to see if this is flagged after the cron job runs while the report is not being decided on (left open in Cinder).

**Comment by ioanarusiczki** [comment]
mmm, none of the add-ons on dev were flagged with `Over abuse reports threshold for usage tier`.  I was expecting both to be flagged. Not sure what I didn't do wright, should I increase the abuse reports ratio threshold before flagging? 

I've reported an unlisted version on stage https://reviewers.addons.allizom.org/en-US/reviewers/review-unlisted/1004828 
ADU 29 which means it belongs to tier nr.1, modified the abuse report ratio to 10, so I'll need a minimum of 3 reports (in the past 2 weeks).

**Comment by ioanarusiczki** [comment]
I'm not sure what happened with those above but I've submitted new extensions and created a few scenarios in this[ document ](https://docs.google.com/document/d/12nZYQMD6FjzHMmPp9Hp_Zy48Bgs-9BCb17QUcnIf3UI/edit) 

So @eviljeff has been adding the ADUs for each and triggered the cron task -> checking the scenarios all look good.

To make a short summary:

- all unlisted versions installed and reported (no matter what reason) were flagged
- unlisted version not installed and reported (with reason A or B) using their guid was flagged
- unlisted addon with multiple versions both installed and reported was flagged
-  listed version reported for reasons A or B got flagged 
- listed versions that were reported with other reasons than A and B which go to Cinder or rev tools were not flagged again for "Over abuse reports threshold for usage tier"
