### ISSUE TITLE
 AwesomeBar elements on the right change position due to pageActions & Reader Mode

### ISSUE THREAD

**Issue by designakt** [mozilla/addons#150]
see https://bugzilla.mozilla.org/show_bug.cgi?id=1227513
This results in users possibly clicking the wrong button as buttons change position depending on what page a user is on. This not only affects the AwesomeBar drop-down arrow, but all page actions. They do not have a fixed place in the UI as all other buttons do, but rather appear/disappear depending on the page.

We might need to investigate the scope and possible solutions to this problem. So far I can see two options, but I did not investigate implications those will have on other things.
- move pageActions to the left of the dropdown arrow (fixes the arrows position, but not the position of page actions)
- move pageActions to the toolbar and always show them ([as chrome did](https://bugs.chromium.org/p/chromium/issues/detail?id=403823))

**Comment by brampitoyo** [comment]
I think that the first option is the one that will cause the least disruption to the way add-ons already work today, and give add-on developers greater flexibility when compared to Chrome (where you can only put a button on the toolbar).

The problem is, we have no clear documented way to deal with custom elements on the Awesome Bar.

* Let’s say that an add-on adds a new icon on the Awesome Bar and you want to hide it. How do you do this?
* Let’s say that you right-click on this icon. Should a custom context menu appear? At the moment, this isn’t the case.
* Try going to Firefox’s “Customize” interface. You’ll notice that Firefox considers the Awesome Bar a single, inseparable unit, so you can’t put any new icon inside it.

**Comment by designakt** [comment]
With Photon this is being redesigned so I will close this.
