### ISSUE TITLE
[Task]: Remove verified/sponsored support in frontend

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15038]
### Description

https://github.com/mozilla/addons/issues/14996 drops support for the (long unused) Verified and Sponsored promoted categories in addons-server.  We should remove references in frontend too.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] No reference to Verified or Sponsored
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1079)

**Comment by ioanarusiczki** [comment]
This looked good on dev when I checked for https://github.com/mozilla/addons/issues/14996#issuecomment-2368076974 but as I said I should wait for the primary hero scenario when this lands on stage

![sponsored on primary hero](https://github.com/user-attachments/assets/642d9293-45f8-4866-99d6-11a7dd7cd5f7)

Also look over some frontend badges - which currently are still present on -stage for: 
https://addons.allizom.org/en-US/firefox/addon/cas_new_addon_verified/
https://addons.allizom.org/en-US/firefox/addon/search-by-image519/
https://addons.allizom.org/en-US/firefox/addon/4manthease-mosel-codcanzee/

or search results
https://addons.allizom.org/en-US/firefox/search/?promoted=badged&page=4

**Comment by ioanarusiczki** [comment]
@eviljeff 

So on primary hero shelf this is how it looks like after removal of sponsored/verified support -> instead of "Sponsored" it's a "Promoted". Currently the extension in admin tools belongs to "not promoted" and if I'd try to save current settings I get the message that it should belong to recommended, by firefox or spotlight. I don't think there is such scenario on prod. 

![now on stage](https://github.com/user-attachments/assets/81780c20-33a6-465a-8061-4ae4dca516ed)
