### ISSUE TITLE
"Search tools" are too hard to search for - request for it's inclusion in the search "Add-on type" filter dropdown

### ISSUE THREAD

**Issue by mxmilkiib** [mozilla/addons#1503]
### Describe the problem and steps to reproduce it:
"Seach tools" category is not an option in the "Add-on type" dropdown on the search results page.

### What happened?
I searched for a search tool for a certain site that has a somewhat generic name. I got many results that included general extensions as well as themes. There was no ability for me to dial down into search tools at that point in the process.

### What did you expect to happen?
It would be nice is search tools (etc.?) are filterable via that method of searching for addons.

**Comment by AlexandraMoga** [comment]
Since search tools are no longer a separate add-on subtype (they are basically extensions) we do not have a special search filter dedicated for them. However, you can still find extensions that fall under the search tool category by going to the 'Extensions' page and selecting Search Tools from  the available categories:

![image](https://github.com/mozilla/addons/assets/31961530/4e8af1a9-9658-4b82-b343-fdf3a73fdb29)

You should be landing on this page - https://addons.mozilla.org/en-US/firefox/extensions/category/search-tools/

**Comment by mxmilkiib** [comment]
How about a Add-on Subtype drop-down filter on the search results page? So that is alterable beyond the page with the Categories buttons. I.e. you can use the search box at the top right first and then select the Subtype Category or whatever the name would be.
