### ISSUE TITLE
[Task]: Implement updated stashing strategy to stash soft as well as hard blocks

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#15050]
### Description

After we decide how to stash soft/hard blocks we must apply these changes to our stashing generation logic to upload new soft add/remove entries.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] existing commands/cron job account for soft/hard block updates
  - [ ] FX is aware and aligned on this updated data structure 
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1094)

**Comment by diox** [comment]
https://mozilla-hub.atlassian.net/browse/AMOENG-1093?focusedCommentId=940513 documents the format of the stashes.

**Comment by willdurand** [comment]
> after enabling them I've noticed a URL that redirects to prod (I might be missing a pref, I've tried to modify this that for dev but I've still the prod url instead of the correct env.) @willdurand perhaps halp here ...

The pref is: extensions.blocklist.addonItemURL

**Comment by willdurand** [comment]
> I've added [services.addons-dev.allizom.org/api/v4/addons/addon](https://services.addons-dev.allizom.org/api/v4/addons/addon/) to extensions.abuseReport.amoDetailsURL and I've a correct redirect to dev.

This pref (`extensions.abuseReport.amoDetailsURL`) doesn't exist AFAICT.

**Comment by ioanarusiczki** [comment]
@willdurand  Looks like I've modified `extensions.blocklist.addonItemURL` too on Friday and kept having the prod url , this morning it worked as expected 🤷‍♀️  
And  `extensions.abuseReport.amoDetailsURL` is no longer in the list indeed, it's been used before abuse reporting was modified.

**Comment by ioanarusiczki** [comment]
I verified AMO stage with `enable-soft-blocking` disabled. 

- blocked multiple guids , were blocked in the browser (I've installed 10 out of 31)
https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/485/change/ 

- deleted multiple guids, those installed in Nighltly were unblocked 
https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/486/change/

- a version with dual sign off blocked then unblocked
https://reviewers.addons.allizom.org/en-US/reviewers/review/1004682 version 1.4.1.7 

- a theme and a dictionary blocked 
https://reviewers.addons.allizom.org/en-US/reviewers/review-listed/2243482#review-actions
https://reviewers.addons.allizom.org/en-US/reviewers/review/2243481

- addons blocked with delay: after generating mlbf they're still available in the browser which is expected since the delay did not expire
https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/491/change/ 

**bloomfilters**

takes a while for https://firefox.settings.services.allizom.org/v1/buckets/blocklists/collections/addons-bloomfilters/records to update but I also used https://remote-settings.allizom.org/v1/buckets/blocklists/collections/addons-bloomfilters/records which does not seem to be cached.

I had the expected results in [blocked] and [unblocked] 
[softblocked] is present in the generation of the stash - always empty

**Comment by ioanarusiczki** [comment]
I also tried on stage with `enable-soft-blocking` disabled 

- to create a [softblock ](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/495/change/), generate mlbf. Checking it, no guids in [softblocked] and the version continues to be enabled in about:addons

- softened an existing [hard block](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/blocklistsubmission/496/change/) -> this guid {00294368-7d81-43ec-a16a-85c1400c2da4} shows up as [[unblocked]](https://remote-settings.allizom.org/v1/buckets/blocklists/collections/addons-bloomfilters/records), checking the browser the version has been enabled (previously blocked). 

I hope the latter is expected.

**Comment by KevinMind** [comment]
Yes, when soft blocking is disabled, softening a hard block is treated as an unblocking. It should be in the unblocked stash. If softblocking is enabled it instead would be in the softblocked stash.

You could verify this by flipping the waffle switch and rerunning the cron.

**Comment by willdurand** [comment]
> [softblocked] is present in the generation of the stash - always empty

Yes, that should be the only obvious difference.
