### ISSUE TITLE
[Bug]: By Firefox addon is not present in the Promoted group as line (currently is Not Promoted)

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons#15052]
### What happened?

Seems to be related to the sponsored/verified issue https://github.com/mozilla/addons/issues/14996

https://addons-dev.allizom.org/en-US/firefox/addon/addon_by_firefox/ is currently "Not promoted" in admin and it used to be By Firefox (line addon). 

Context: 
Automated tests test_addon_detail_by_firefox_badge failed on -dev 

Same test on -stage doesn't fail.

Checked also: the recommeded addon badge test - this looks good on -dev. The badge is still displayed. 

CC @alexandruschek 

### What did you expect to happen?

It appears to be a problem after discussing with @diox  

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1097)

**Comment by diox** [comment]
This is a regression caused by https://github.com/mozilla/addons/issues/14996.

The commit/PR changes the constants, removing `SPONSORED` and `VERIFIED`, with:
https://github.com/mozilla/addons-server/pull/22671/files#diff-79d694e59e09ae3b9265b9380908ecc836da7fccc2522878519e3613fd13e6f2

Note that the removed constants have `id` `2` and `3`, but the comment says they had `3` and `4`. `4` is still there, and it's `LINE`, i.e. `By Firefox`. That mistake would be ok if it was just the comment that was wrong, unfortunately it was repeated in the migration, which hardcoded the ids:
https://github.com/mozilla/addons-server/pull/22671/files#diff-99fa534b8e58a0e3d592bf0cc12c3b7be2c79d8d183a968625579d2af1ab2eb7 :
```python
    PromotedAddon.objects.filter(group_id__in=(3, 4)).update(group_id=0)
    PromotedApproval.objects.filter(group_id__in=(3, 4)).delete()
```

**Comment by ioanarusiczki** [comment]
Looking good on -stage https://addons.allizom.org/en-US/firefox/addon/by-firefox/

Checked admin tools -> all in place for recommended, by firefox, strategic, spotlight and notable.
Verified and sponsored were deleted.
