### ISSUE TITLE
[Task]: Store the reason an add-on version was added to the review queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#15072]
### Description

We would like to permanently store the the timestamp and reason an add-on version was added to the review queue. For some cases, the reason is already shown while in the queue, but we want to keep track of income volume and origin/reason on a permanent basis.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] A permanent record in the database recording the reason when and why an add-on version was added to the review queue.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1123)

**Comment by diox** [comment]
We technically already do for `NeedsHumanReview` cases, as we never delete the NHR instances, we simply toggle them to inactive.

What's not covered by NHR at the moment: belonging to a promoted group forcing pre-review, having reviewer flags set disabling or delaying auto-approval.

**Comment by wagnerand** [comment]
I am not sure that is a very reliable way.I remember cases where I had to manually step in and fiddle with the flag in the admin tools. I don't remember changing the reason, but maybe an activity log entry would be the better option? Or something else that is purely recorded and not also used to impact the queue.

**Comment by diox** [comment]
@wagnerand to start looking at existing NHR data to see if that suits his needs. If it does we can look into adding NHR for pre-review cases.

**Comment by wagnerand** [comment]
@diox Using NHR looks like a viable approach.

**Comment by wagnerand** [comment]
Nominating for P2 to be implemented before the end of the year so that from 2025 on, we have full-year coverage.

**Comment by diox** [comment]
This forces us to change how and when due dates (which is what determines if a version is in the review queue) are calculated, when an add-on is promoted or has is auto-approval disabled.

**Before:**
If an add-on is promoted or has one of the auto-approval disabled flags, and a new version becomes awaiting review, it immediately got a due date

**After:**
If an add-on is promoted or has one of the auto-approval disabled flags, and a new version becomes awaiting review, it fist goes through auto-approval, and that sets a `NeedsHumanReview` flag on it, a corresponding activity log and the due date. 

Notably, if the promotion is removed or the auto-approval re-enabled, the version should still have its due date, as long as the `NeedsHumanReview` is still here.

**Comment by ioanarusiczki** [comment]
- addon in promoted group , a new version is submitted. It's flagged for HR because it belongs to a promoted group. 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634490
Activity log https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4587679/change/

On stage the review page is different (version in awaiting review because "Is in a promoted add-on group that requires pre-review") https://reviewers.addons.allizom.org/en-US/reviewers/review/1106878 

I removed the addon from the promoted group -> version is auto-approved but still has a due date and it is present in the Manual Review Queue. 

- listed/unlisted with auto-approval disabled 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634516
activity log https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4587984/change/
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/634517
activity log https://addons-internal.dev.mozaws.net/en-US/admin/models/activity/activitylog/4587985/change/

I enabled again the auto-approval, versions got approved but still have a due date and they're in the manual review queue.

- with scanner rules -> awaiting review for that and also flagged again so it's 2 activity logs generated for each
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/634519
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/634517

- noticed that on dev that ublock origin is in awaiting review compared to stage. 
on dev https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634521
on stage https://reviewers.addons.allizom.org/en-US/reviewers/review/1909734

In all cases, there's the notable icon that shows up with different tooltips for extensions. 

![Screenshot (2)](https://github.com/user-attachments/assets/a47fcc0d-e690-4b63-b167-be911943494f)

![Screenshot (3)](https://github.com/user-attachments/assets/13ff5569-8fa3-438f-913a-50610c967901)


I see it in the theme queue too.

Themes on dev 

![themes on dev](https://github.com/user-attachments/assets/3e18cb62-2410-4574-b071-d779dd351c84)

Themes on stage

![themes on stage](https://github.com/user-attachments/assets/d19bbaf9-19ea-4fd6-bdc0-6dd85b586392)

**Comment by ioanarusiczki** [comment]
Maybe a followup for icons?

**Comment by diox** [comment]
The reason the icons are incorrect is that I've introduced new reasons for needing human review as part of this patch, but those don't have an icon, even though they match existing flags we had. I'll look into fixing this today and cherry-pick that.

**Comment by alexandruschek** [comment]
I checked on stage, following the str, and it works as expected
