### ISSUE TITLE
[Task]: Implement forward/escalation to legal queue in Cinder from reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15078]
### Description

Just as Cinder moderators can transfer jobs to the legal queue for investigation by our legal team, AMO reviewers should be able to too.  (Rather than a manual email/slack message, as now).  

When https://github.com/mozilla/addons/issues/15035 is implemented job moves between queues would be fully circular - meaning a reviewer could forward a job to legal, who could then answer in cinder and forward it back to AMO.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] Have an action in reviewer tools that forwards a job to the legal queue on cinder
  - [ ] (stretch - may be in a follow-up) be able to forward a review on an add-on that _isn't_ connected to a job to legal
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1132)

**Comment by ioanarusiczki** [comment]
On AMO dev:

- I think any add-on can be forwarded to the Legal Cinder queue because of the presence of "Request Review from Mozilla Legal" including unlisted versions (approved or awaiting review)

- same add-on can be forwarded multiple times

An example
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/635010

- I could forward to Legal versions without an abuse report 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634982

- or with an abuse report attached (reported for add-on policies and flagged for HR in rev tools). These would continue to have the report in the DSA section as "Forwarded" but the HR flag is being removed. 

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/634981

- I could send to Legal a theme which previously had a report in cinder and has been forwarded to rev tools. This would continue to have HR flag set.
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/635009

Legal Escalations queue -> I tried to disable content, resolve with ignore or escalate to AMO (these all are possible actions) and I did not see them having any effect. Probably this is not part of the patch.

Jobs are closed:

https://stage.cinder.nonprod.webservices.mozgcp.net/job/18f3e599-26e5-4791-b401-8cf167d6d9b9
https://stage.cinder.nonprod.webservices.mozgcp.net/job/8a1513ce-66fb-41f8-8250-2d0ca5db5c29
https://stage.cinder.nonprod.webservices.mozgcp.net/job/27425d96-9e19-4a69-b03d-611cc50fa64c
