### ISSUE TITLE
[Bug]: Inconsistent display of version that need human review on add-on's review page

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#15109]
### What happened?

For version(s) that needs to be reviewed, we currently show it in two ways. 

One is with an orange bar on the version flagged for review

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/14b541a9-0d75-40fc-84ba-14e131af691a">

And the other is without the highlighted color 

<img width="1218" alt="image" src="https://github.com/user-attachments/assets/429d95ca-5b3d-446e-8d42-1a819bad2207">

I don't see any obvious difference between the two (if there is something that as a reviewer I should've been aware of, I'd be happy to get educated here!).
 
This creates a small hurdle for anyone new onboarding to understand they're the same, at least practically from a reviewer's perspective.

### What did you expect to happen?

Versions flagged for review to be displayed consistently on the add-on review page

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1163)

**Comment by diox** [comment]
This is intended, there is a subtle difference : "Orange" ones need human review because they have a ... Needs Human Review active instance. The other "blue" ones would typically not have a due date, unless they were forced into pre-review because of a flag on the add-on itself or because the add-on belongs to a promoted group.

So:
- All versions are "blue" by default...
- Versions that hit a scanner rule, were already approved but the add-on became notable, were flagged after the add-on grew past a usage threshold, had sources provided while pending rejection, had a developer reply, were flagged after the add-on got too many abuse reports, were reported for abuse inside the add-on or subject to an appeal are "orange". This takes precedence over the "blue".
- Notable/Recommended add-ons versions subject to pre-review that are not triggering one of the rules above are still "blue"

https://github.com/mozilla/addons/issues/15072 will likely change that, and we can reconsider the styling then.

**Comment by abhn** [comment]
Got it, and sounds good. Practically speaking (from an add-on reviewer PoV), there's no real difference between the two (exact same review situation) so we might still want to (re)consider the styling decisions.

The various cases you mentioned should ideally be logged into the activity log giving the reviewers insights into why the add-on was being reviewed. I know some of them are, but not sure if it is all of them.
