### ISSUE TITLE
[Task]: Include all promoted add-ons in second level approval, regardless of last review date

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#15244]
### Description

Currently promoted add-ons are only added to the second level approval queue if a review has been done since it was added to the promoted category.

This change is to ensure that when a moderation decision is made on a promoted add-on, it should be added to the second level approval queue regardless of when its last review date was.

### Acceptance Criteria

```[tasklist]
  ### Milestones/checkpoints
  - [ ] When a moderation decision is made on a promoted add-on, it should be added to the second level approval queue regardless of when its last review date was
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1313)

**Comment by ioanarusiczki** [comment]
I've tried with https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/634958 , added it in recommended , it does not have a badge, only after a new version approval would get the badge. 

I've disabled it from Cinder - don't see it in 2nd level approval queue.

**Comment by diox** [comment]
You were too fast, the change hasn't made it to dev yet.

**Comment by ioanarusiczki** [comment]
On AMO Dev

A line addon without the badge is in 2nd level approval https://reviewers.addons-dev.allizom.org/en-US/reviewers/decision-review/5943

a recommended too https://reviewers.addons-dev.allizom.org/en-US/reviewers/decision-review/5944

**Comment by ioanarusiczki** [comment]
On AMO dev I've also tried:
- a spotlight add-on https://reviewers.addons-dev.allizom.org/en-US/reviewers/decision-review/5945
- a notable (by making it notable from admin, I know that's not how it's supposed to happen but the trick worked) https://reviewers.addons-dev.allizom.org/en-US/reviewers/decision-review/5947
- a recommended theme (added from admin and not by using the Mozilla theme collection because that would make it instantly recommended) https://reviewers.addons-dev.allizom.org/en-US/reviewers/decision-review/5949
- by firefox theme (I know that's not a thing for production but it's working) https://reviewers.addons-dev.allizom.org/en-US/reviewers/decision-review/5949
- an awaiting review first listed version added to recommended extensions in admin https://reviewers.addons-dev.allizom.org/en-US/reviewers/decision-review/5951
