### ISSUE TITLE
Explain the reason why certain addons unavailable in certain region

### ISSUE THREAD

**Issue by 0x391F** [mozilla/addons#1561]
Some add-ons, such as uBlock Origin https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/, should explain the reason why it unavailable in certain region, for example, China ("law" problem), because some chinese user complain firefox "deny" them to install certain add-ons, and it causing some user turn to use other browsers.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-24)

**Comment by rugk** [comment]
Also, you may want to reply with **HTTP 451** when it has been removed due to legal reasons. After all “451 Unavailable For Legal Reasons” already explains a lot.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451

Ref [coming from this issue/background, where exactly that happened](https://discourse.mozilla.org/t/the-censorship-circumvention-extension-has-disappeared-from-the-russian-version-of-mozilla-addons/130914/50?u=rugkx).
Ref https://github.com/mozilla/addons/issues/1534

**Comment by diox** [comment]
We do reply with HTTP 451 errors when they add-ons are not available in a region already.
