### ISSUE TITLE
[Task]: handle abuse reports being directly associated with an appeal cinder job

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#1741]
### Description
Cinder combines multiple abuse reports into a single job - i.e. if a job is already open for an entity (an addon, a rating, a collection, or a user) then rather than opening a new job, the report is attached to the existing job.  We handle this fine.  But we made an assumption that appeal jobs - where a previous decision was appealed by the reporter or the owner of the entity - were separate.

This assumption ~may not be~ **is not** correct.  QA testing (#1728) has shown that reporting an entity that has an outstanding appeal job _also_ combines that that report into the job. **UPDATE**: I have reproduced QA's findings

### Acceptance Criteria
* We need to make any necessary model changes to support the scenario of abuse reports being associated with an appeal job
* This also applies to appeal-appeal jobs (reporter-reports->decision:approve; reporter-appeals->decision:reject; owner-appeals)
* appeals on those decisions need to be tested (e.g. do we allow enough time?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-18)

**Comment by abyrne-moz** [comment]
We will create a spike in the next sprint to try to reproduce this.

**Comment by ioanarusiczki** [comment]
I don't know exactly what changes this may bring so I tried reporter-reports->decision:approve; reporter-appeals->decision:reject; owner-appeals and used the delay reject (scenario from https://github.com/mozilla/addons/issues/1728)

1. For an extension reported for violating add-on policies "inside add-on" or "both locations" -> this is flagged for human review and goes to rev tools. After reporter's appeal, I've delay rejected the version and then sent new abuse reports (for the same policy). Emails are not sent to reporters as I mentioned in https://github.com/mozilla/addons/issues/1728 but I see the new reports being present on [reviewers page](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/631542). 
Sending new reports for the other policies while the extension is pending rejection -> they're present in Cinder , listings queue

2. Extension or theme is escalated to AMO. Reporter appeals, delay rejection is set.  While pending rejection if I sent new reports, they're going to Cinder listings/themes queue. If some of these reports are already assigned to a reviewer, new reports are created separately.
I tried with https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/631564
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/631565#review-actions

3. I tried the scenario using only Cinder moderation (with reject instead of delay reject). Noticed that once the reporter's appeal is present and it's not assigned yet to a moderator, new reports sent are not showing up. After I assign the appeal and send some reports, it will work.  I'll make a followup, try to explain it with an example. 

@eviljeff I hope 1. and 2. are expected behaviors. In case I didn't cover something please let me know.

**Comment by eviljeff** [comment]
> After reporter's appeal, I've delay rejected the version and then sent new abuse reports (for the same policy). 

If the version has been rejected - or delay rejected - on the back of an appeal, then it's expected that any new reports would be separate.  The appeal job has been resolved.  The issue about about open appeals, that have not already been resolved.

> Emails are not sent to reporters as I mentioned in https://github.com/mozilla/addons/issues/1728

tbh I've lost any context to the comments at the bottom of #1728 so I don't know what emails would be expected to be sent to reporters.

**Comment by ioanarusiczki** [comment]
> The issue about about open appeals, that have not already been resolved.

Then I don't understand the description you made. Could you clarify what to check about open appeals? 

#1728 was a followup for #9449 ->There is a delay rejection set on the back of a report or appeal. Other reporters send new reports. When I initially tested for #9449 I've noticed that these reporters were getting an email.

>  What about further abuse reports that come in between the delayed rejection set up and the eventual takedown. Do we notify those reporters straight away that a delayed rejection is in progress? - Decision: Yes

**Comment by ioanarusiczki** [comment]
I'll try to summarize this:

1. For author appeals (this would be scenario1: "content not taken down, reporter is notified and appeals, we confirm the decision. The content stays up, the reporter is notified can no longer appeal." it looks good. It's more obvious with rev tools since right now Cinder won't display [new reports under an appeal](https://lindie.app/share/6a21d831b39351d7c6fe898f6d22619af62dde98/PROD-1692). The first reporter is getting an email without an appeal url, the rest of the reporters get an email with an appeal url which would be expected since they didn't send appeals yet.

2. For an appeal sent by the author , extensions could be still reported from addon manager. While the appeal is still open, if I send new reports these will be available under the appeal. No matter of the decision taken, reinstate content or keep content disabled, there is only one email sent which is going to the author. Reporters won't receive an email in these cases. This applies to the rest of the possible scenarios (2,3 or 4) in rev tools or Cinder. 

3.  scenario 2 "reporter-reports->decision:approve; reporter-appeals->decision:reject; owner-appeals)" with a delay rejection are working as expected but I'll detail this in https://github.com/mozilla/addons/issues/1728

4. with extensions/themes escalated -> new reports will be going to Cinder which I understood it's expected. 

_To make a note:_
scenario 3 is 
Content taken down, author appeals, we change the decision and bring the content back up
scenario 4 is 
Content taken down, author appeals, we confirm the decision

I don't know what's expected from 2. exactly because there's never been emails sent to reporters after author's appeal.
This does not apply to other entities reported because they cannot be reported again after being disabled/deleted.

**Comment by eviljeff** [comment]
Okay, I think I got it: reporters aren't sent any emails on the back of author appeals.  (which makes sense when they were the original reporters - they already got their email for the first decision - but is a flaw for reports that are attached to subsequent appeals)

**Comment by eviljeff** [comment]
@ioanarusiczki can you file a new issue with the current state of bugginess?

> I'll detail this in https://github.com/mozilla/addons/issues/1728

I'm not clear what you're detailing - the rest of the paragraph says it working as expected? - but if there's a bug we need to fix can we have it as a new issue please (non-trivial bug-fixes, especially ones that span multiple prod deploys, are hard to track without new issues)

**Comment by ioanarusiczki** [comment]
1, 3, and 4 - look good
Filed a followup for 2. 
Left for me  2 other things I've noticed and file those too, worst case scenario they're invalid but they're not related to this issue anyway.
