### ISSUE TITLE
User reviews for old Marketplace apps are still present in the database and can't be deleted by their authors

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/addons#176]
I once wrote i comment on a app called Nook.
I can see it on my account page: https://addons.mozilla.org/da/firefox/user/[USERNAME]/
So i try to delete it with the "Delete review" link https://addons.mozilla.org/da/firefox/addon/app-377832/

Nothing happens when clicking the link.
The browser does not even visit the link.

https://addons.mozilla.org/da/firefox/addon/app-377832/reviews/472130/delete says:
"We're sorry, but we can't find what you're looking for."

**Comment by andymckay** [comment]
That addon is actually an app and I bet its left over from the Marketplace days. Apps are no longer supported. The 404 is because it can't find the App because the Django implementation no longer knows anything about them.

Probably the best thing to do here is clear out the data from the database so that comment never shows up.
