### ISSUE TITLE
Searching for "online antivirus" doesn't find any results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons#1797]
STR:

1. Open AMO dev
1. Search for "online antivirus" and check the results

Actual results:
There are no no addons found for this search query

Expected result:
I'd expect to find something like this list: https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=online%20anti%20virus . Some of these addons contain a "online anti-virus" string in the summary

Notes:

* reproduced on AMO -dev with FF63, Win10x64

![image](https://user-images.githubusercontent.com/31961530/48783052-3032bf00-ece8-11e8-8d44-8e60321ce0c5.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-83)

**Comment by diox** [comment]
At the moment on dev:
- ["online anti virus" finds 7 results](https://addons-dev.allizom.org/en-US/firefox/search/?q=online%20anti%20virus)
- ["online anti-virus" finds 7 results](https://addons-dev.allizom.org/en-US/firefox/search/?q=online%20anti-virus)
- ["online antivirus" finds 5 results](https://addons-dev.allizom.org/en-US/firefox/search/?q=online%20antivirus)

Only "antivirus" is missing the last 2 results, because they don't contain "antivirus" as-is anywhere, they only have "anti-virus" in their description. The other add-ons are found through their name regardless of the presence of the hyphen, thanks to the trigrams and/or fuzzy matching.

Based on these results I'm wontfixing this, I don't think this is worth the effort, it would be a very specific case and quite annoying to implement just for the description match.
