### ISSUE TITLE
Firefox accounts AMO upgrade process problem

### ISSUE THREAD

**Issue by gene1wood** [mozilla/addons#182]
I went to AMO and logged in and it prompted me to upgrade my account to FxA. Here's what I experienced

https://www.youtube.com/watch?v=CHe405FgUSw

* I logged in to AMO with the email address that I had used with AMO previously.
* When taken to Firefox Accounts I saw that my FxA account was with my personal email address so I signed in.
* I was taken back to AMO and given the error message "Your Firefox Account already exists on this site."
* I didn't know what that meant or what I should do so I clicked the "Need help?" link but didn't find an answer there.

How do I login to AMO now that it's using Firefox Accounts? Am I required to create a second FxA account with the same email address that I used in AMO? Am I required to create a new AMO account with the same email address that I use in FxA? Something else?

**Comment by mstriemer** [comment]
Sorry for the late reply!

This happens when both email addresses exist on AMO. So I guess you have an AMO account with your work email address and another with your personal one. Since Firefox Marketplace also used the same database at one point you could have created one of those on Marketplace but we unfortunately can't tell.

The resolution is to delete the account you don't want (I'm guessing this is your personal address one) or change its email to something that doesn't match your Firefox Account.

I updated the support article [1] around the time you ran into this but unfortunately it looks like it didn't go live in time to help you.

I'm going to close this on the assumption that this will fix your problem but please re-open if it does not.

[1] https://support.mozilla.org/en-US/kb/access-your-add-ons-firefox-accounts#w_what-does-the-your-firefox-account-already-exists-on-this-site-error-mean
