### ISSUE TITLE
In the Status & Versions page, each version should be associated with a channel

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#193]
### User story

As a developer, I would like to manage both the listed and unlisted versions of my add-ons from one place. Whereas today, I am required to create an entirely new add-on entity for each channel.
### What this bug focuses on

Your add-on has many versions. You need a way to distinguish which versions belong to listed, and which versions belong to unlisted

**Comment by brampitoyo** [comment]
In order to distinguish between listed and unlisted versions, we can either tag each version number with a channel name (shown below), or separate each channel in its own list.

**One important design note:** these tags will only show up when your add-on has versions uploaded to multiple channels. For add-on belonging to only one channel (which is the majority of them), colour tags won’t be used.

* “AMO” is colour tagged teal/cyan
* “Self” (self-hosted) is colour tagged purple

The design is still early, so expect it to change. The visibility UI is particularly unfinished, so there’s a lot of room for improvements there. Regardless, you should be able to see what I’m thinking as far as version tagging goes.

(I also haven’t addressed how channel would impact other page elements like the “Status sidebar” and “My Submissions”.)

![management status versions](https://cloud.githubusercontent.com/assets/51007/18299172/d24ee82c-7512-11e6-92d1-a1750409d1fe.png)

**Comment by brampitoyo** [comment]
Some thoughts:

* Put channel tag in “Status” column
* Remove “1 file” and replace it with channel tag

**Comment by jvillalobos** [comment]
Thoughts on status sidebar:

* For all add-ons, show Multiprocess status (note we use "multiprocess" as one word in most places I've seen) of latest version, Last Updated, and Upload New Version. For add-ons with listed versions, show the rest of the information.
* For all add-ons, remove View All and Visibility.
* Rename "Current version" to "Listed version", meaning this is the version shown on the main add-on page. This would also apply to the box in the main page area. If an add-on only has unlisted versions, there would be no "Listed version" box, and "Older versions" should read "All versions" instead. Or maybe we should simplify this and just have a star or some other highlight for the listed version.

**Comment by brampitoyo** [comment]
I’ve updated the Status & Versions page.

Changes:

* Number of file indicator (“1 file”) has been replaced with the channel tag, and the channel tag comes before status. It now looks like:
  * <kbd>AMO</kbd> Reviewed
  * <kbd>Self</kbd> Signed
  * etc.
* “Add-on visibility” renamed to “<kbd>AMO</kbd> Listing visibility”
* “Current version” renamed to “<kbd>AMO</kbd> Listed version”

Also note the purple texts that indicates when sections or tags should be shown or hidden. The gist here is that, if you only have unlisted or listed versions only, you won’t see the tags. And if you only have unlisted versions, some sections will be hidden.

I’ve also updated the status sidebar and reduced the number of information in it. Based on @jvillalobos’ feedbacks, we’ll show different information depending on whether you have versions in one channel or both channels.

### Status & Versions

![status versions](https://cloud.githubusercontent.com/assets/51007/18459196/a99d23fa-79bb-11e6-80a9-4db522d80979.png)

### Status sidebar

#### Unlisted version only

![unlisted sidebar](https://cloud.githubusercontent.com/assets/51007/18459205/bd3d180c-79bb-11e6-821b-d85c9083fd34.png)

#### Listed version only

![listed sidebar](https://cloud.githubusercontent.com/assets/51007/18459207/c294edc0-79bb-11e6-89d0-e0d0a1103485.png)

#### Versions exist on both channels

![unlisted listed sidebar](https://cloud.githubusercontent.com/assets/51007/18459220/e27b7d48-79bb-11e6-9ccc-4e37c58c6a8c.png)

**Comment by jvillalobos** [comment]
Looks good.

**Comment by brampitoyo** [comment]
The design for this issue is finished and we’re now ready to implement it.

**Comment by eviljeff** [comment]
I started implementing the status sidebar but there some problems with the designs as shown:
- Multiprocess is per Add-on (https://github.com/mozilla/addons-server/issues/3947) so can't be shown per channel
- Last Updated is also per Add-on.  Could switch it to a version date but the same template snippet is used in the 'my submissions' list (that will optionally show add-on creation date instead of update) so what should happen there?
- The designs ignore that Listed channels can have both a current and a latest version (i.e. pending review) that will have a queue status line too.
- Hiding the status for Unlisted-only add-ons makes sense but there is an edge case where we (admins) disable the add-on so that wouldn't shown to the developer and https://github.com/mozilla/addons-server/issues/3970 is asking we disable uploads which might be confusing.
- Latest version is defined as the most recent non-disabled, non-beta version so it's very possible to have an add-on with no latest version if the developer's submission was rejected or they deleted it.  The UI could get confusing in this case as usually we hide the line if there isn't a latest version.  It's not clear what should happen with the (AMO) (Self) tags when there isn't an AMO latest version but there does exist an AMO version that's disabled.
-  I'm concerned it's quite difficult to tell from the UI that you have an add-on with only unlisted versions (rather than listed) unless you know about our UI and what should be there or not and the label differences (listed version rather than latest version).  I'm not sure we say "unlisted" or explicitly indicate it's not on AMO anywhere unless you also have a listed version. Maybe that's okay, but I'm calling it out.

**Comment by jvillalobos** [comment]
>  Multiprocess is per Add-on (mozilla/addons-server#3947) so can't be shown per channel
> Last Updated is also per Add-on.

I suggest showing the common attributes at the top. So, it would be like:

common stuff
(separator if there's more than one channel)
AMO stuff
(separator if there's more than one channel)
Self stuff

Bram, what do you think?

> The designs ignore that Listed channels can have both a current and a latest version (i.e. pending review) that will have a queue status line too.

Those can just be added, right?

> Hiding the status for Unlisted-only add-ons makes sense but there is an edge case where we (admins) disable the add-on.

Let's show the status in that case.

>  Latest version is defined as the most recent non-disabled, non-beta version so it's very possible to have an add-on with no latest version if the developer's submission was rejected or they deleted it. The UI could get confusing in this case as usually we hide the line if there isn't a latest version.

I think it's okay to hide the line in that case.

> It's not clear what should happen with the (AMO) (Self) tags when there isn't an AMO latest version but there does exist an AMO version that's disabled.

In #3472, we agreed that the listing options would still be available even if all listed versions are disabled, so I think the way to go here is to keep the tags.

>   I'm concerned it's quite difficult to tell from the UI that you have an add-on with only unlisted versions (rather than listed) unless you know about our UI.

Good points, but I think we should keep it like this until a greater redesign. If it turns out to be a big source of confusion, we'll come up with something more explicit.

**Comment by brampitoyo** [comment]
@jvillalobos wrote:

> I suggest showing the common attributes at the top

Here’s an updated sidebar that takes this into account, plus other cases that @eviljeff had mentioned. I would have most certainly missed a few scenarios, but I hope it covers most.

What do you think?

![unlisted listed sidebar](https://cloud.githubusercontent.com/assets/51007/20377092/8ab19888-ace0-11e6-948d-44eaea1c0268.png)

**Comment by eviljeff** [comment]
The label has changed on the latest mockup from "Listed Version" and "Latest Version" to "Current Version" for both channels.

Note 'current' and 'latest' mean different things internally and on the API. 
Unlisted channels only have 'latest' version - the most recent non-disabled version.
Listed have both - current is the most recent Approved version, or the most recent non-disabled version if the addon isn't Approved; latest is the most recent non-disabled, non-beta version.  (Confusingly, there is a 'latest' url which is actually the 'current' listed version)

**Comment by eviljeff** [comment]
Btw, the logic above would lead to the following if the developer disabled all their unlisted versions:
![no unlisted latest version](https://cloud.githubusercontent.com/assets/768592/20390071/f5e3ab3a-acc4-11e6-92b4-8265cd7d09ce.png)

**Comment by eviljeff** [comment]
Nit: Status would be 'Incomplete' if there are no Approved or Awaiting Review versions - AMO doesn't explicitly have a Rejected status for either the Addon or Version/File

**Comment by jvillalobos** [comment]
Re: your last screenshot, the Self-hosted section shouldn't show up if there isn't anything to show.

**Comment by eviljeff** [comment]
blocked awaiting a response to https://github.com/mozilla/addons/issues/193#issuecomment-261238963 (version name terminology)

**Comment by jvillalobos** [comment]
Let's keep "Listed" and "Latest".

**Comment by brampitoyo** [comment]
I’ve updated the sidebar logic:

* “Listed” and “Latest” version name terminology is kept as before
* If there’s no version that’s Approved or Awaiting Review, the status is “Incomplete” instead of “Rejected”
* If developer disabled all their unlisted versions, we hide the “Self-Hosted” section entirely instead of just displaying the flag

![unlisted listed sidebar](https://cloud.githubusercontent.com/assets/51007/20503655/d03f3472-b097-11e6-89b4-02467a3fd27a.png)

Thoughts?

**Comment by eviljeff** [comment]
btw, https://github.com/mozilla/addons-server/issues/4015#issuecomment-262069097 takes out the Visibility: line
