### ISSUE TITLE
During submission flow, if your add-on is listed, add fields for Notes to Reviewer & Version/Release Notes

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons#200]
### User story
As a developer, whether my add-on is listed or unlisted, I would like its submission/signing process to proceed as quickly as possible.

### What this bug focuses on
If your add-on is destined for listing, whether you’re uploading a completely new add-on or a new version of an existing add-on:

* Your users would like to know what’s been changed (ie. Version/Release Notes)
* Mozilla reviewers would like to know if there’s anything they should bear in mind when reviewing  (Notes to Reviewer).

You should be able to fill out this information before submitting for review.

**Comment by brampitoyo** [comment]
Added *Version/Release Notes* and *Notes to Reviewer* fields on the “Describe your add-on” step.

Note that this page now become lengthy, but we’re also able to condense a few steps into one. It’s a compromise.

What do you think of the ordering of the fields?

![listed describe](https://cloud.githubusercontent.com/assets/51007/18295667/6d5daa0e-74f7-11e6-9325-7d7d91f64fa2.png)

**Comment by jvillalobos** [comment]
* "The detail page will be". I'm not sure if we say "detail page" elsewhere. I think normally we call it "listing page", or we could go with "public add-on page" or something like that.
* The "This add-on is experimental" checkbox should have a help icon next to it with an explanation. Maybe it's just missing from the mockup.
* I'd move the more detailed description up, right below the summary. I think it makes more logical sense there.
* We use "version notes" instead of "release note" throughout the site. I would move that field to the bottom, just above the notes to reviewer.
* The End-User License Agreement isn't really needed for listing or review, so I think we can drop it.

**Comment by brampitoyo** [comment]
Design note: if the number of fields get too many, consider adding form headings a la the “Edit Details” page.

**Comment by jvillalobos** [comment]
Here's what I suggest for fields and their ordering:

* Name and version
* The detail page will be
* Brief summary
* This add-on is experimental
* Categories
* Support email address
* Support website
* License
* Privacy Policy
* Notes to Reviewer

I dropped the Detailed description because that can be added later, like the screenshots. I also dropped the Version Notes, since they're not so important for the first release and can also be added later.

**Comment by brampitoyo** [comment]
Thanks for the ordering suggestion. I’ve updated the mockup with these changes:

* Dropped “Detailed description”, “Version note” and “EULA” fields
* Shortened some headings, following the edit interface whenever I can:
  * “The detail page will be” → “Add-on URL”
  * “Provide a brief summary” → “Summary”
* Added “Support email address” and “Support website”

![listed describe](https://cloud.githubusercontent.com/assets/51007/18460812/e80abef6-79c8-11e6-8ea0-f5c54b56cf8f.png)

**Comment by jvillalobos** [comment]
Looks great! Not terribly crowded, IMO.

**Comment by brampitoyo** [comment]
Despite the addition of quite a few fields, it’s still less crowded than Chrome Webstore’s.

![chrome-webstore-edit-item](https://cloud.githubusercontent.com/assets/51007/18494101/4fc4de88-7a68-11e6-8f6f-f4659e4ebc47.png)
