### ISSUE TITLE
Upgrade RabbitMQ to 3.12.12

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons#2014]
### Describe the problem and steps to reproduce it:

We currently use RabbitMQ 3.8.33, which is no longer supported.

### What happened?

RabbitMQ 3.8.33 is no longer supported.

### What did you expect to happen?

We'd like to upgrade it to RabbitMQ 3.12.12.

Please upgrade the developers' local environment to this version and we can start upgrading our environments one by one.

### Anything else we should know?
n/a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-296)

**Comment by bqbn** [comment]
To clarify, the purpose of this issue is to have the dev local environment upgraded to the proposed 3.12.12 version.

SRE will take care of upgrading the versions in all three environments.

**Comment by diox** [comment]
[3.12 (technically starts with 3.11) requires feature flags to be explicitly set](https://www.rabbitmq.com/blog/2022/07/20/required-feature-flags-in-rabbitmq-3.11).

So before we upgrade, while we're still on 3.8, we need to set the flags, and then upgrade. On our local envs the easiest option is for everyone to trash their `rabbitmq` container (`docker compose down rabbitmq`) before putting it back up again with the new version instead of just stopping/restarting it
