### ISSUE TITLE
Reviews and developer replies are not updated for every language of a page after editing them

### ISSUE THREAD

**Issue by anonym24** [mozilla/addons#202]
https://discourse.mozilla-community.org/t/reviews-and-developer-replies-are-not-updated-for-every-language-of-a-page-after-editing-them/10558

**Comment by diox** [comment]
Ouch, that's bad. I suspect that bug has existed since the beginning of time...

It's a consequence of `Review` using `TranslatedField`s instead of `CharField`s. The review doesn't really care about translations, but for some reason the model was written this way, and yeah, it fails hard when people using different languages manipulate the reviews.

The proper fix would be to move to `CharField` for the `body` and `title` fields on the `Review` model, but ths migration for this is quite painful to write and execute.

**Comment by anonym24** [comment]
And also after deleting answer to review and trying to add it again an error will show up. 

> Oops! We had an error.
> We'll get to fixing that soon.
> You can try refreshing the page, or head back to the Add-ons homepage.

I guess this site needs some help

**Comment by anonym24** [comment]
Still this error appears. Can't answer to user's review.., "We'll get to fixing that soon." - empty words I guess

**Comment by diox** [comment]
Deleting and answer then replying to the same comment again is a separate problem, already tracked in #158

**Comment by diox** [comment]
Similar root cause: https://github.com/mozilla/addons-server/issues/7517

**Comment by eviljeff** [comment]
we fixed mozilla/addons-server#7517 so I assume this is fixed too.  Reopen if it can still be reproduced.
