### ISSUE TITLE
allow (admin-controlled) moderation by default for an add-on

### ISSUE THREAD

**Issue by mconnormoz** [mozilla/addons#205]
Follows #204 in terms of having the capability to moderate add-on reviews.  If there's a problematic review in isolation, reactive moderation is fine.  For add-ons that are being repeatedly targeted by spam/abuse/attack reviews, it would be good to have a way to auto-flag all add-ons for moderation.

The main downside here is that this would put extra load on moderation queues in the short term, but it would very quickly stop abusive tactics, so it's likely we wouldn't get that much, and it'd be less work than cleaning up after determined attackers.

For bonus points, we could have a middle ground where only accounts created in the previous N days would be moderated (aka the "Twitter egg filter" approach).

**Comment by jvillalobos** [comment]
This isn't a common-enough problem to worry about it from a tooling perspective. We do have plans to improve the ratings system so we show the most useful reviews first, rather than just the latest, which can help deter some of these attacks. This plan is still being formed, so the specifics may change. Hopefully we'll be able to get to implement it later this year.
