### ISSUE TITLE
Please support better image quality on amo :) 

### ISSUE THREAD

**Issue by Ulf3000** [mozilla/addons#221]
I think the quality of screenshots from an addon are way too lowquality and lowres , they should be available in 1080p and good quality ... it makes amo look cheap and outdated. sorry to be so harsh but this was already a problem back in the days but in 2016 its just waaaay overdue.  

thanx for listening :)

**Comment by andymckay** [comment]
How would you suggest doing that since the screenshots are uploaded by the addon author?

**Comment by tofumatt** [comment]
Presumably the issue is that we process the images and we are compressing
them too heavily.

**Comment by andymckay** [comment]
Ah right, we resize the images as well.

**Comment by Ulf3000** [comment]
yep on most addon description images you can´t see whats going becasue of teh resizing and compression.

as a addon dev i then have to look that i don´t make the images a single pixel or kb too big OR ELSE  mozilla will compress the hell out of it and i have to make a new image and reupload.

**Comment by EnTeQuAk** [comment]
Yeah, we're resizing previews to 700x525 and we use the easy-thumbnails default quality of 85 instead of the usual 95 which leads to better quality.

Good news is that - at least according to our code - we seem to save the original image so we could improve this incrementally. I think, while doing this might worth investing a bit more time and think about saving / storing various quality sizes, e.g at least one for normal resolutions and for 2x retina displays so that we can implement or at least think about it while doing `addons-frontend` or to use something like `django-ultimatethumb` to calculate those on-demand e.g to save disk-space for qualities and images we'd never show because no one accesses them.

**Comment by muffinresearch** [comment]
We should definitely consider overall what we might want out of image processing from both short-term improvements to what we would ideally like in the future. 

For example it would be nice to look at using `srcset` [1] on the new frontend, so that the browser can render the most appropriate image size.

[1] http://caniuse.com/#feat=srcset
[2] http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset

**Comment by jvillalobos** [comment]
Duping this one to the new tracker: https://github.com/mozilla/addons-server/issues/7907
