### ISSUE TITLE
Stuck on platforms when submitting a WebExtension

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#26]
Add a new add-on for example: 

https://dl.dropboxusercontent.com/u/2301433/Firefox/WebExtensions/github-canned-responses-test.xpi

And find you are stuck on the *****ing platform error. There's a few bugs on this I think.

![screenshot 2016-02-01 12 26 27](https://cloud.githubusercontent.com/assets/74699/12730099/0d3f43ea-c8df-11e5-8751-ab809d7fbdba.png)

Please save us from the pain, @magopian

**Comment by andymckay** [comment]
Note that none of the checkboxes are enabled and cannot be enabled, developer tools will get us around it.

**Comment by andymckay** [comment]
See also: mozilla/olympia#1390, mozilla/olympia#993

**Comment by bwinton** [comment]
Adding a `strict_max_version` doesn't help me, but removing the `strict_min_version` looks like it gets around the problem.

**Comment by magopian** [comment]
This was fixed last week by https://github.com/mozilla/amo-validator/pull/386. It should make it to stage today, and to production on thursday. In the meantime you can try uploading to https://addons-dev.allizom.org.

This is the result on -dev (the issue is the `strict_min_version` which doesn't exist, it should be `43.0`):
<img width="715" alt="screen shot 2016-02-02 at 11 06 16" src="https://cloud.githubusercontent.com/assets/167767/12746044/055cfdb6-c99d-11e5-8333-56e698346e21.png">

**Comment by andymckay** [comment]
Thanks @magopian.

![](https://media.giphy.com/media/v3o4ybLU2VwRi/giphy.gif)
