### ISSUE TITLE
Auto unload tab addon - (Broken middle click action - open link in new tab). 

### ISSUE THREAD

**Issue by jazzmale** [mozilla/addons#272]
Auto unload tab addon 0.9.0.0 
Broken middle click action - open link in new tab. 

Opens dummy tab with a link in the address bar but can't be loaded, even manually. 

Previous 0.8.9.9 works fine.  

FF 49.0.2 - Ubuntu 16.04.2

**Comment by andymckay** [comment]
This issue tracker is for issues about the add-ons site. If you are talking about this add-on:

https://addons.mozilla.org/en-US/firefox/addon/auto-unload-tab/

Then you'd need to contact the add-on author. Sadly I'm not sure of a way of doing that since they haven't provided support information in the form of a website or email address for you to contact them.
