### ISSUE TITLE
Expand compatibility range for 53

### ISSUE THREAD

**Issue by magicp-github** [mozilla/addons#286]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
1. Go to https://addons.mozilla.org/en-US/developers/addons
2. Cannot expand compatibility range for latest Nightly.

### What happened?
Cannot select 53.0a1 in maxVersion

### What did you expect to happen?
Expand compatibility range for 53

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
https://addons.mozilla.org/en-US/developers/addons

**Comment by eviljeff** [comment]
Filed bug for ops to add:
https://bugzilla.mozilla.org/show_bug.cgi?id=1319504 (confidential non-public bug)

**Comment by eviljeff** [comment]
Some code was removed a few months ago that lets us bulk-add these appversions.  It's been fixed in https://github.com/mozilla/addons-server/pull/4049 but that won't be live till the next push on December 1st.
So added the following manually:
firefox "52.*"
firefox "53.0a1"
firefox "53.0a2"
firefox "53.0"

**Comment by magicp-github** [comment]
This bug was verified fixed. Thanks!
