### ISSUE TITLE
Review Syntax highlighter: Limit on file-size

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#313]
### Describe the problem and steps to reproduce it:
There are developers who include massive files in their addons. They can be JS or even CSS etc
I have seen many that are 700+kb
The result causes the browser to hang and usually ends up in having to stop the script running.

### Suggestion
A mechanism to check file-size before running the highlighter script and if file-size is large than some value (lets say 100kb ??!), not to run the highlighter and show the file as is.

### Note
It may be some other script that hangs and crashes (other than the highlighter). If so, please update the post.

**Comment by wagnerand** [comment]
The current file limit is 1MB. If the file if above that size, we don't show the file at all, but instead advice reviewers to download it/open it in a new tab.

Showing it inside the file-viewer but without syntax highlighting might not gain us very much. Every single line has to go through some part of AMO rendering anyway, for example for the line numbers.

The much bigger problem though is that the file-viewer and the rendering of the file contents in particular (along with actual highlighting) is a hugely fragile part of AMO. The code is quite old and very complex, it involves server-side and client-side work and every time we touch the smallest piece, we break something else.

That's why we're planning to rewrite the whole thing at some point, see https://github.com/mozilla/addons-server/issues/4149

**Comment by wagnerand** [comment]
Actually, that linked issue is about the syntax highlighting part only. We have been thinking and talking to other teams about replacing or rewriting the whole file-viewer as well. It's not only the frontend, but also the backend which is a huge pain for people involved and we regularly run into bugs, as you have noticed.

**Comment by andymckay** [comment]
I think the real answer is to use another service that is maintained and looked after so we don't have to maintain this. For example: reviewboard, mozreview and github all have and maintain good reviewing interfaces. There are other considerations around this, but maintaining all these problems and code is just a pain.

**Comment by erosman** [comment]
Sometimes a diff without the syntax highlighter could be useful (unless the diff script also has the issue). Today I got hanged on a massive CSS file.

**Comment by erosman** [comment]
I don't know how the Syntax Highlighting is implemented (and I am guessing the problem is with the syntax highlighting process). The problem of hung pages and script timeout errors still persists.

In addition to CSS, even JSON files cause unresponsive browser.

I would suggest not processing CSS/JSON with the same code that processes JS files. Even no highlighting for those files is not a major issue and can be managed.

**Comment by erosman** [comment]
CSS is still hanging the browser ...
example: (not the best example of CSS writing though but nonetheless)
`https://addons.mozilla.org/en-US/firefox/files/browse/749554/file/css/index.css#top`

Personally, I would be happy with NO highlighting/processing on CS and JSON files.
