### ISSUE TITLE
After signing an unlisted addon set to "invisible", the link to download it links to a 404

### ISSUE THREAD

**Issue by julienw** [mozilla/addons#324]
### Describe the problem and steps to reproduce it:
* Uploaded a new version for an unlisted add-on
* went through all the steps until the final window "The version has been signed and you can download it by clicking on this button"

=> it went to an error page.
Strangely the first time it was a nice "unavailable" error page. Then after reloading I got the ugly nginx default 404 error page.

Addon is: https://addons.mozilla.org/fr/developers/addon/french-holiday-forms/edit
Final link that doesn't work is: https://addons.mozilla.org/firefox/downloads/file/582606/french_holiday_forms-1.2.1-fx.xpi?src=devhub

Note that the previous versions of the add-on weren't unlisted, so maybe this has a consequence.

**Comment by julienw** [comment]
The add-on was 'invisible' as well. (I initially thought this was the same as "unlisted" so I enabled it).

**Comment by julienw** [comment]
OK, I can download it after setting the module back to "visible". So this is either a bug or a UX problem.

**Comment by diox** [comment]
"Invisible" terminology is really confusing and we should find a better way to explain that to users, but that's another (UX) issue. 

It should have been possible to download the file for the author regardless of the add-on state, *especially* if it's unlisted. I'll look into that.

**Comment by diox** [comment]
@julienw I'll try fixing the issue that caused the add-on to be 404, can you please file another issue about what was confusing for you, from a UX point of view ?

**Comment by diox** [comment]
The download view itself is correct, if the add-on is disabled, it tries to use `X-SendFile` and the `guarded_file_path`, otherwise it simply redirects to the CDN url.

The problem is, when we upload a new file, it goes in the regular `file_path`, not `guarded_file_path`. That's one of the reasons why we have the [nasty hide_disabled_files and unhide_disabled_files crons](https://github.com/mozilla/addons-server/issues/3598). 

I want to fix the code to upload to the right path depending on the add-on and file status but need to dig deeper to understand the repercussions of doing so, since there is some refactoring involved.

**Comment by diox** [comment]
Going to try to fix this with a naive approach instead of doing the full refactor (that's https://github.com/mozilla/addons-server/issues/3596). My plan is to copy the file to `self.current_file_path` in `from_upload()`, instead of what we're doing right now. That should obey the add-on disabled state and hopefully doesn't break anything...

**Comment by diox** [comment]
Re-opening because I noticed the signing code expects the file to exist in `file_path`, so my naive fix is not enough - it would prevent the file from being signed.

**Comment by diox** [comment]
QA: Make submitting unlisted addons & versions works, that they are properly signed. In particular, it should work for new submissions, but also unlisted versions added while the add-on has been set to invisible (which should only be available if the add-on had listed versions uploaded in the past).
