### ISSUE TITLE
Addon Daily User Statistics has a wrong count

### ISSUE THREAD

**Issue by CardBook** [mozilla/addons#427]
a example for the day 2017-06-23 : 
the count by platform (https://addons.mozilla.org/fr/firefox/addon/cardbook/statistics/usage/os/?last=30) shows 14300. If you calculate the count yourself you'll find : 16516 (1+11012+710+4780+13)

it's the same for the count by lang

**Comment by EnTeQuAk** [comment]
I didn't check the numbers yet since I'm currently on the move and can't
check the details but we recently changed the daily users to be
calculated only using activated installations (see our addons blog for
more information). These calculations are only active from the 22nd
onwards, so the numbers will get more and more correct as we approach
the 5th July.
Does this help? 


On Mon, Jun 26, 2017, at 04:56 PM, CardBook wrote:
> a example for the day 2017-06-23 :
>  the count by platform
>  (https://addons.mozilla.org/fr/firefox/addon/cardbook/statistics/usage/os/?last=30)
>  shows 14300. If you calculate the count yourself you'll find : 16516
>  (1+11012+710+4780+13)> it's the same for the count by lang


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons/issues/427

**Comment by CardBook** [comment]
the problem occurs until the 21-06-2017 onwards... Before the total does not exactly match but there are similar... so the count will decrease : not good for the moral ;O)

**Comment by CardBook** [comment]
solution on your blog : 

`This change also doesn’t affect the detailed statistics dashboard developers have access to. Only the number displayed on user-facing sections of the site will change.`
