### ISSUE TITLE
[l10n] "Some add-ons ask for permission..." template string for legacy add-ons isn't localisable

### ISSUE THREAD

**Issue by zelitomas** [mozilla/addons#448]
https://pageshot.net/ZgslcxBkPnhSaOUU/addons.mozilla.org

Original string: Some add-ons ask for permission to perform certain functions (example: a tab management add-on will ask permission to access your browser’s tab system).

Shoul be (cs locale): Některé doplňky požadují oprávnění k provádění některých funkcí (příklad: doplněk pro správu panelů bude požadovat oprávnění pro přístup k systému panelů prohlížeče).

The string is translated on Pontoon for more than 5 months - https://pontoon.mozilla.org/cs/amo/all-resources/?search=Some+add-ons+ask+for+permission&string=163066

**Comment by eviljeff** [comment]
example addon please

**Comment by zelitomas** [comment]
Hello, evijeff,

the name of exmaple addon is written in the heading in the first link, but here is a link - https://addons.mozilla.org/cs/firefox/addon/ublock-origin/

**Comment by zelitomas** [comment]
But any non-WebExtension addon works as well

**Comment by eviljeff** [comment]
😞
That's a different [string](https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/templates/addons/impala/details.html#L333) - the one shown for webextensions is worded slightly differently.

But 
https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/templates/addons/impala/details.html#L353
and
https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/templates/addons/impala/details.html#L355
aren't actually localisable - I wrote `{{ ('Some` instead of `{{ _('Some`.

Thanks for spotting the mistake.

**Comment by zelitomas** [comment]
Oh, I'm really, really sorry for the mistake :(, but I'm happy to hear that you found out where the problem is.

Thank you very much :)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
1. For webextensions the Permissions link is completely translated and, therefore, localized.
Posftix screenshots:
![es](https://user-images.githubusercontent.com/15685960/28705427-628bf77c-7378-11e7-8bcd-b919a8620730.png)
![fr](https://user-images.githubusercontent.com/15685960/28705428-628d05a4-7378-11e7-8e97-6e89a7e213ad.png)

2. For legacy add-on the Permission link seems localized, but the content is not translated - I guess this is only because no contribution was added.
Postfix screenshots:
![de](https://user-images.githubusercontent.com/15685960/28705572-13c8aabc-7379-11e7-9b2d-f350fb1d149e.png)
![fr-a](https://user-images.githubusercontent.com/15685960/28705573-13ce22c6-7379-11e7-9e6a-cdc403da3111.png)

Please reopen if I am not right.
Thanks!

**Comment by eviljeff** [comment]
yep, we'll have to wait a few days until the localisation teams pick up the new string and it gets pulled back into AMO.
