### ISSUE TITLE
Mistakes in private politics and user accounts

### ISSUE THREAD

**Issue by S-Kerrigan** [mozilla/addons#461]
Firstly, i signed up in the https://addons.mozilla.org/ many years ago (2012), and after some time created my collection of memories add-ons. It was worked fine.

Then i some years no signed and does not change any changes in this collection. Today i wanted add new add-on to collection and saw, that i cannot sign-in in my profile?! Firstly i tried to change the password, but their i saw analogy answer. Ok, i went to register page, done it, then went to collections page and saw my collection!

So, web-application / portal give me false about, that my account was absent, plus my information was not deleted. I know, that no critical, just me unpleasantly, that it happened.

![capture](https://user-images.githubusercontent.com/4696242/29060888-db4b574a-7c45-11e7-8d86-bf69b7c79fc7.JPG)

**Comment by EnTeQuAk** [comment]
I am sorry to hear that you ran into problems with your collection. We switched to Firefox Accounts over a year ago to unify the login for users across many of Mozillas services.

As you mentioned none of your information got deleted so everything is still accessible.

Unless I misunderstood your ticket I'm going to close this since there isn't anything that we can or need to fix. If I'm mistaken, please feel free to re-open / reply at any time.
