### ISSUE TITLE
Error "Could not parse the manifest file" during verification

### ISSUE THREAD

**Issue by grumbelbart** [mozilla/addons#484]
I am trying to sign a company-internal version of the zotero add-on. The only change w.r.t. the original are modified server addresses. The signing process fails with the message:

  Your add-on failed validation with 1 error.
  Could not parse the manifest file. 

That error does not show up in the full validation report, which shows only warnings.

The signing worked for all previous versions of the add-on. I have attached the manifest file -- which we do not touch, i.e., it is the unmodified manifest of the original add-on. Any help is appreciated.

[chrome.manifest.txt](https://github.com/mozilla/addons/files/1298501/chrome.manifest.txt)

**Comment by diox** [comment]
That error probably comes from parsing the `install.rdf` file, not `chrome.manifest`. It's confusing but `install.rdf` is commonly called the install manifest.

It'd be easier to figure out what's going on with the full xpi used.

**Comment by grumbelbart** [comment]
Thank you for the hint. I've attached both install.rdf and the full XPI.

[zotero-4.0.29.22.xpi.patched.xpi.zip](https://github.com/mozilla/addons/files/1299333/zotero-4.0.29.22.xpi.patched.xpi.zip)

[install.rdf.txt](https://github.com/mozilla/addons/files/1299334/install.rdf.txt)

**Comment by diox** [comment]
That add-on has a signature (see `META-INF` folder), but it does not seem to be valid for the contents of the add-on, so it's failing. Since the signature is going to be replaced when you submit the add-on, you should remove it anyway by deleting the `META-INF` folder.

Also note that it's a legacy add-on. We don't allow uploads of legacy add-ons anymore unless they target older versions of Firefox and have [`strictCompatibility`](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#strictCompatibility) set.
