### ISSUE TITLE
More search sorting options

### ISSUE THREAD

**Issue by Jan02** [mozilla/addons#492]
Please add more search filters:
- ratings
- review count
- date range: updated, submitted
- maturity of addon measured by: how long has it been submitted, how often is it updated, how many users does it have
this filter could be 3 sliders

**Comment by eviljeff** [comment]
@jvillalobos for your Product opinion

**Comment by tofumatt** [comment]
Date submitted and updated are definitely useful sort options to me.

Matthew Riley MacPherson (sent from mobile)

**Comment by jvillalobos** [comment]
These all sound like sorting options rather than filters, so I'm editing the issue title to reflect this.

I think relevance (default), users, avg rating, and last update date make sense. Review count, date submitted, and "maturity" seem very niche to me, and I'd rather start with fewer filters since it's easier to add features than to remove them.

**Comment by eviljeff** [comment]
I think the API already has all of them that make sense http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-search-sort 
@tofumatt I don't know if there are any of them that need adding to addons-frontend?

**Comment by jvillalobos** [comment]
I just came back to this issue because I realized that list is what we currently support, heh. Closing, then, but feel free to continue the discussion.
