### ISSUE TITLE
Addon search dropdown suggestions doesn't respect FF version

### ISSUE THREAD

**Issue by martin-kokos** [mozilla/addons#496]
### Describe the problem and steps to reproduce it:
Have FF57 and go to https://addons.mozilla.org/en-US/firefox/
Use search field and type "sess"
Notice `Session Manager` as search suggestion
Click it going to https://addons.mozilla.org/en-US/firefox/addon/session-manager/?src=ss
Find out "This add-on is not compatible with your version of Firefox. "

### What happened?
Search suggests plugins ignoring version

### What did you expect to happen?
See suggestions that are compatible with version or see no suggestions

### Anything else we should know?
![image](https://user-images.githubusercontent.com/4807476/30879858-f9b95a42-a300-11e7-907e-1c3a73ed5344.png)
It goes without saying users will miss legacy plugins, and this hurts transitions to new addons.

**Comment by tofumatt** [comment]
This is fixed in the new version of the site we’ll be launching as a beta sometime next month. See the issue here: https://github.com/mozilla/addons-frontend/issues/3209

We (likely) won't be fixing it in this older version of the site but fortunately the new one will be opt-in next month and rolled out to all users in advance of Firefox 57 launching. 😄

So I'm going to close this as fixed on the new site and won't fix for the old site. Hope that helps!
