### ISSUE TITLE
AMO RSS feeds do not have any entry body formatting

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons#5123]
https://addons.mozilla.org/extensions/format%3Arss?sort=updated
These feeds are very useful. Items in feeds like these however, do not have any text formatting included, which made the descriptions look spammy until i found out the entry bodies do not include CRLF/LF/<br>'s at all.

**Comment by Korb** [comment]
Am I correct in understanding that currently, as a regular user with no programming knowledge, I can't copy a link to a page like `https://addons.mozilla.org/en-US/firefox/addon/…/versions/` and paste it into my favorite feed reader _(where I have three thousand feeds, neatly organized into a convenient folder structure)_? I've been doing this for years: signing up for new job postings on websites of good companies, interesting app repositories, and even games on Steam. And in order to subscribe to extension release notes in AMO, I need to use third-party tools designed **specifically** for extension news and only for them. Frankly, I can only explain the logic of these changes through the prism of corporate insularity, not user interests.

**Comment by rctgamer3** [comment]
Stop hijacking and necrobumping a six-year old discussion for your unrelated discussion.
Can someone please lock this thread.
