### ISSUE TITLE
Include Android in filter

### ISSUE THREAD

**Issue by FlyingHorseGA** [mozilla/addons#543]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
When filtering sesrch results I am unable to select "Android" under the OS category.

### What did you expect to happen?
I expect "Android" to be selectable as an OS just like "Windows", "Linux", "MacOS" etc...

### Anything else we should know?
After getting redults from a search for Add-ons there is a box to the left to select filter parameters for the results. One of the parameters is "Operating System" Please add "Android"

Here is an example: https://addons.mozilla.org/en-US/android/search/?q=android
![screenshot_2017-11-14-22-27-40](https://user-images.githubusercontent.com/17473829/32817487-fed415d8-c98b-11e7-8159-25d259e457a9.png)

**Comment by muffinresearch** [comment]
@FlyingHorseGA hi - thanks for filing an issue. There's some confusion introduced here that arises from Android being both a client App e.g. Firefox or Firefox Android, but it's also a platform. 

The fact that you are on the android URL e.g. /en-US/android/ should be providing you android compatible add-ons already.

We are already making some plans to make this clearer in the future.

**Comment by stephenjudge** [comment]
I have come across many extensions that AMO let's me install on Firefox for Android, only to find after installing them that they don't work. I don't know if this is due to the extension developer erroniously marking their extension as compatible with Firefox for Android, without doing testing. Or have all WebExtensions add-on's now automatically be labelled as being compatible with Firefox for Android. It is very frustrating to go through the process of searching for an extension with the functionality your are looking for, install it, then find out it is not compatible with Firefox for Android at all.

Would it help to document here the list of extensions I have come across that show up in AMO on Firefox for Android but don't work after installing?

**Comment by jvillalobos** [comment]
There are many add-ons that report Android compatibility but don't really work. That is partly misreporting by developers, and part UX limitations in the new add-on submission flow. It's something we're aware of and will fix hopefully soon.
