### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by rickyvetter** [mozilla/addons#547]
Please attach a copy of your add-on, and fill in the following information:
[Archive.zip](https://github.com/mozilla/addons/files/1481475/Archive.zip)
Sorry, we couldn't load your WebExtension.

* This error occurred on a new version of an existing add-on.

* Add-on is listed

* I submitted from https://addons.mozilla.org/en-US/developers/addon/reason-tools/versions/submit/

* I submitted at approximately 8:03(UTC) 2017-11-17

**Comment by jvillalobos** [comment]
There doesn't appear to be anything wrong with the manifest, so the linter must be choking due to the very large and minified JS files in the add-on. Is there a reason they're all these large? Previous versions of your add-on apparently had only one very large background script, while the others were under 1Mb.

/cc @EnTeQuAk

**Comment by rickyvetter** [comment]
This new version supports three way translation between OCaml and two versions of the Reason syntax. Theoretically the large file should have increased by 50% and the rest should have stayed the same. I'm looking into why all of the other files grew as well.

**Comment by muffinresearch** [comment]
@rickyvetter did you get anywhere with your investigation?

@EnTeQuAk if you had a moment it would be interesting to get some idea of where the linter is blowing up.

**Comment by rickyvetter** [comment]
Yes I was able to remove the bloat from all but one of the files. The verification works as long as it's just one ~3MB file.
