### ISSUE TITLE
Display installed Addon

### ISSUE THREAD

**Issue by Rictusempra** [mozilla/addons#548]
### Describe the problem and steps to reproduce it:
Install any addon from AMO and visit the same page

### What happened?
N/A

### What did you expect to happen?
Something should indicate this addon has been installed

### Anything else we should know?
Perhaps upgrade button (if any newer version)

**Comment by yfdyh000** [comment]
> Perhaps upgrade button (if any newer version)

Perhaps "Update to" for any different version.

**Comment by muffinresearch** [comment]
@Rictusempra hi, thanks for the feedback.

We had to make some last minute changes to the original "switch" button (as used in about:addons) because it didn't perform well in user testing in the context of this site. One of the features this had was the ability to display something that's already installed.

For now we have the simpler button, but we do expect to add back some of the smarter elements of the switch back into the current button and the indicator for install is one of them.

**Comment by muffinresearch** [comment]
Closing this since it should be covered by https://github.com/mozilla/addons-frontend/issues/3954
