### ISSUE TITLE
customise browser  themes - categories

### ISSUE THREAD

**Issue by satzel** [mozilla/addons#550]
Hi there,

when browsing themes to customise firefox, different categories are offered to narrow down the choices. Like nature, film and tv and so on. which works fine. 

### What happened?

in the category "fashion" I seem to see a lot of girls in underwear or bikinis, where the emphasis doesn't seem to be the fashion but the sexy poses, asses and boobs presented. on page 1 of top rated themes 14 out of 25 themes i would sort into the "sexy girl" topic.

### What did you expect to happen?

to see themes related to fashion

### Anything else we should know?

maybe it would be possible to label the categories more accurately? so to find themes that show girls posing in bikini and underwear with an emphasis on them presenting themselves in sexy poses, maybe call it "half-dressed girls in sexy poses" or maybe "Harvey Weinstein" themes and for fairness and gender equality overall maybe it would be possible to include the same category for guys in underwear?

**Comment by jvillalobos** [comment]
Developers categorize add-ons themselves, and this goes largely unchecked, since in the case of themes we're talking about tens of thousands of them. "fashion" has always been the better fit for those themes (which include some male model ones as well, just not as many). We've talked about creating a separate category for them, but nothing concrete has come up yet.

I do think that in general we should curate content in the category pages, since somewhat similar problems happen in the extension categories. We may be able to address this early next year when we extend the work we're doing for content curation.
