### ISSUE TITLE
Automatic FFox update incompatible w/ online PPT viewer function - no alternative given

### ISSUE THREAD

**Issue by ColoradoLeo** [mozilla/addons#557]
Clicking a download button to view a PPT file results in sheets of symbols instead of a PPT presentation. 
![image](https://user-images.githubusercontent.com/33843582/33036299-30095bc8-cdeb-11e7-8338-f525aa4eb064.png)
![image](https://user-images.githubusercontent.com/33843582/33036348-4e7575ce-cdeb-11e7-9bc1-62bee88b7fb8.png)

The MS add-on - which would allow for online viewing through Firefox  -is no longer compatible with the new  updated Firefox.   
![image](https://user-images.githubusercontent.com/33843582/33036386-6c93892e-cdeb-11e7-9091-21dc79f84fb4.png)
https://addons.mozilla.org/en-US/firefox/tag/powerpoint%20viewer 
When searching for help to view online PPT on Firefox, the only item that comes up in search is the MS viewer, with the note that it does not conform with the new version. 
NO other options are shown whereby we may download and view an online PPT presentation.

It'd be great if you'd suggest alternatives.

**Comment by jvillalobos** [comment]
I tried the [link on your screenshots](http://www.theprovenplan.com/wp-content/uploads/2011/08/Pro-3-Plan.pps) and I can confirm that the file appears like a bunch of garbled text. That's probably a server configuration problem, since it should prompt a download instead.

As for the add-on, it's up to the developers to update them to support new versions of Firefox, if it's possible and they are willing to. I'm not aware of any add-ons that currently do this, so there's nothing to do here, I think.
