### ISSUE TITLE
Running FireFox 57, cant install addons.  Says Im running FF 50

### ISSUE THREAD

**Issue by ahdonah** [mozilla/addons#575]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Windows 7, 32GB Ram, SSD
I'm running FireFox 57.  Current updates as of today.
### What happened?
Went to add Addon New Tab Override (WebExtension) by Sören Hentzschel.  
Got rejected, said I was running FireFox 50
### What did you expect to happen?
Load an Addon
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
I run Bitdefender Total Security 2018  HitManPro.Alert 3.7.1 Build 723
Also using Anonymizer.com  VPN

**Comment by kumar303** [comment]
> I run Bitdefender Total Security 2018 HitManPro.Alert 3.7.1 Build 723
Also using Anonymizer.com VPN

There isn't much we can do here because it sounds like you have turned on all anti-fingerprinting prefs. One of these prefs will lock your browser's user agent on Firefox 50. You will need to use a separate add-on to set your user agent back to 57 when you use addons.mozilla.org.
