### ISSUE TITLE
Google analytics in http://addons.mozilla.org/

### ISSUE THREAD

**Issue by luffah** [mozilla/addons#585]
Hello, this is not a a bug.
Maybe it is a design problem for a company which support free software / privacy and is a reference for the Web.
In addons.mozilla.org, i found (thanks to ublock and web inspector - wappalyzer said nothing) the page use google analytics for its stat. 
There is many alternatives like Piwik, and i have some pain to understand why Mozilla use this Google service.
Maybe Mozilla don't care about free software and privacy. I'm confused.

**Comment by tofumatt** [comment]
Our agreement with GA has some provisions that help it preserve user privacy. You can read more about this issue here: https://github.com/mozilla/addons-frontend/issues/2785

I think there are a fair amount of links but it's a long issue to explain. The short version is that GA is the best product for us and we have agreements in place to respect privacy (you'll need to read through those links, it's a bit hard for me to find)–Piwik and others are simply not good enough for our needs at our scale.
