### ISSUE TITLE
Searching for 'eyes' fails to find 'decentraleyes'

### ISSUE THREAD

**Issue by ghost** [mozilla/addons#591]
Steps to reproduce:

Searched for an add-on using the interface provided by about:addons. However, the search on the add-ons webpage has the same problems.

Actual results:

I fail to find add-ons that have names similar to my search strings. For instance: 'privacybadger' fails to find the Privacy Badger extension, although 'privacy badger' finds it. Or: 'eyes' fails to find the addOn called 'decentraleyes'.

Expected results:

See above.

It seems to me that this is the sort of thing that may harm Firefox adoption.
PS: [It was suggested that I file this report here (rather than anywhere else)](https://bugzilla.mozilla.org/show_bug.cgi?id=1425375).

**Comment by diox** [comment]
Hi, I'm keeping this open for now, @EnTeQuAk will decide what to do, but we already have a ton of issues opened on the subject. See https://github.com/mozilla/addons-server/issues/2661 for more information.

**Comment by diox** [comment]
- "privacybadger" now does find "Privacy Badger" thanks to the recent changes to name matching.
- "eyes" still doesn't find "decentraleyes" because we don't decompose "decentraleyes" into 2 words and therefore "eyes" is not enough to match it.

Note that searching for "decentral" does return "eye" in the first ~ 15 results, thanks to our name prefix match rule. I'm downgrading priority to p4 since the main issue has been fixed, but keeping it around to see what we can do about the second one.

**Comment by diox** [comment]
Forgot to close this back in the day, but at some point we improved our fuzzy matching and fixed this. In fact, "Decentraleyes" is the first result returned for a search for "eyes" now.
