### ISSUE TITLE
Trying to update addon, but can't login to my account (says account doesn't exist)

### ISSUE THREAD

**Issue by dwtest1** [mozilla/addons#607]
### Describe the problem and steps to reproduce it:

I am the author of this extension: https://addons.mozilla.org/en-US/firefox/addon/remove-cookies-for-site/

It was created under my account "mail@dwipal.com". I have updated it to be compatible with firefox 57, but I am unable to login to the account anymore.

The login site says that there is no account with that email id, so can't reset password either.

I still get emails from the addons website on the above email id.

Thanks,
Dwipal

**Comment by jvillalobos** [comment]
We changed our authentication system since the last time you logged into AMO. In order to regain access to your account, you need to follow the new account registration flow instead of the log in flow, and just make sure you use the same email address. Once the Firefox Account is created, you'll have access to your AMO account and add-ons.
