### ISSUE TITLE
Ukrainian dictionary addon not returned in "Best match" search results

### ISSUE THREAD

**Issue by arysin** [mozilla/addons#608]
### Describe the problem and steps to reproduce it:
1) go to about:addons in Firefox
2) type "Ukrainian dictionary", "Ukrainian", "Український", "Український словник"

### What happened?
Ukrainian spellchecking dictionary is not in the best match list, but when you click on "See all XXX results" it appears at the top

### What did you expect to happen?
Ukrainian dictionary should appear in the "Best match" list

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/ukrainian-dictionary/

**Comment by jvillalobos** [comment]
The search in `about:addons` is a bit different from the one in the add-ons website. Fortunately, that will change soon, and searching on `about:addons` will effectively do the same as clicking on "See all results". Per [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1263313), it should be fixed in Firefox 59.

**Comment by arysin** [comment]
Thanks, but it may take a bit for the users to be on Firefox 59. Is there anything I can do from addon to make it in the best match list now?

**Comment by jvillalobos** [comment]
No, for what I see in the search results, dictionaries aren't being included at all, and I don't expect other changes to happen on that search since it's being discarded.
