### ISSUE TITLE
[Reviewer Tools] Content Approved should Clear Content Need Info

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#609]
Preamble:
I realise there is no separation of Content Need Info and Review Need Info (but would be good to be considered).

At the moment **Content approved** does not clear the **Need Info**.

Example:
```
https://reviewers.addons.mozilla.org/editors/review/810953/
https://reviewers.addons.mozilla.org/en-US/reviewers/review/sindup
https://reviewers.addons.mozilla.org/en-US/reviewers/review/jira-assign-to-reporter
https://reviewers.addons.mozilla.org/en-US/reviewers/review/dealsolymp
https://reviewers.addons.mozilla.org/en-US/reviewers/review/request-assistant
https://reviewers.addons.mozilla.org/en-US/reviewers/review/lapi-stream
https://reviewers.addons.mozilla.org/en-US/reviewers/review/tweetpane
https://reviewers.addons.mozilla.org/en-US/reviewers/review/icp-show
https://reviewers.addons.mozilla.org/en-US/reviewers/review/drum_screenshare
https://reviewers.addons.mozilla.org/en-US/reviewers/review/boxshooter-webextension
https://reviewers.addons.mozilla.org/en-US/reviewers/review/putcut

```

**Comment by wagnerand** [comment]
This is a good point, thank you for filing!

We probably would have to separate the two information-requests. Otherwise, content-approve would always clear the information-request even if it was a technical one.

**Comment by wagnerand** [comment]
@jvillalobos I could use your feedback here.

I believe separating the need-info's for code and content makes sense, but this adds some complexity on the backend. The only added complexity that is exposed to humans should be for admins, and I would be ok with that.

**Comment by jvillalobos** [comment]
Doesn't this also expose complexity for reviewers an developers? What happens when someone sends a code need info and later someone else sends a content need info? Can one be resolved and not the other?

I think the simpler approach here would be to give the option to clear a need info when content-approving an add-on. Thoughts?

**Comment by wagnerand** [comment]
Reviews pending need-info are hidden (by default) from regular reviewers. You're right, there is some added complexity for developers. I was thinking about exposing the two need-info's as one for developers, but that seems quite hacky.

I am not sure how clearing the need-info when content-approving solves the use-case you pictured:
1. Content-reviewer sends need-info about the content.
2. Add-on reviewer sends need-info about the code/functionality.
3. Content-reviewer approves the content.

If the content-reviewer clears the the flag after step 3, it's gone, even if the information requested in step 2 has not been provided. If they don't, well that would be a bit more "accurate", but I am not sure a developer would understand why their add-on would then still be flagged as "Information needed". (= added mental complexity, which I think might be worse than added UI complexity). Also the reviewer would have to identify that a second need-info was sent and try to evaluate whether the second one was solved or not. He will be in the same dilemma: Clear the flag or not?

All in all, I believe this is not a super common case (until proven wrong). I hope it will be even less of an issue once we went through the backlog of content-reviews.

I don't see a way to solve this for all use-cases unless we split the flag into two, like we did with the admin-flag and I am not sure we should go that way. Maybe your approach solves for 80% of the cases, but I'm not a fan of putting the burden on regular content-reviewers, especially because of the non-technical profile we defined for them.

**Comment by erosman** [comment]
As an Idea, for the time being, maybe allowing (senior) reviewers to unflag could be helpful so it is not left in the queue and up to Admins to unflag.

**Comment by jvillalobos** [comment]
I wasn't clear in my previous comment. Providing the option to unflag was meant as an *alternative* to having separate flags, rather than a solution on top of it. I think it's best to keep a single need info flag and avoid additional complexity. My suggestion came from looking at the examples and seeing that the resolution of the need info should happen when the following content approval happens.

If this is just a temporary situation that we'll adjust to, or rare enough, I'm okay with closing this for now and waiting to see how it evolves.

**Comment by erosman** [comment]
Actually .................. I am changing my mind about "Content Approved should Clear Content Need Info" !!

I have come across a 100s+ of add-ons today that have **Content approved** even though the request in **More information requested** is still outstanding and it is confusing!

**Comment by diox** [comment]
Is there a clear path for us to fixing this issue? Also, the new request for information system has an explicit checkbox for developers to check when they have address the request. Does that fix the issue ?

**Comment by jvillalobos** [comment]
The checkbox should fix the issue, yes. Also, this problem probably will be rare in the future, since content reviewers already caught up with the backlog and they'll be mostly reviewing very recent submissions. Closing this now.
