### ISSUE TITLE
On Firefox for Android, ('identity' in chrome) == false .

### ISSUE THREAD

**Issue by JRF-2018** [mozilla/addons#611]
### Describe the problem and steps to reproduce it:

I try to make an add-on to use "chrome.identity.getRedirectURL()". In the url blow, it is written that the 'identity' is supported on Firefox for Android from the version 53.

《identity - Mozilla | MDN》
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/identity

However, on Firefox for Android (Nightly 59.0a1), I got ('identity' in chrome) == false . I have set 'identity' permission in 'manifest.json'. On the same add-on for PC, I can get ('identity' in chrome) == true .

**Comment by andymckay** [comment]
I think the docs are incorrect, according to the source, identity is not available on Android.

/cc @wbamberg

**Comment by wbamberg** [comment]
Thanks @andymckay .

How is it indicated that this API is not available on Android? I was under the impression that:

* if the schema was in [mozilla-central/source/browser/components/extensions/schemas/](https://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/) then it was desktop-only

* if the schema was in [mozilla-central/source/toolkit/components/extensions/schemas](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/schemas), then it was common.

Since [identity.json is in `toolkit`](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/schemas/identity.json), I must have assumed it was common. Is there a more reliable way that this is indicated?

**Comment by andymckay** [comment]
Apparently by the files:

https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ext-toolkit.json
https://dxr.mozilla.org/mozilla-central/source/browser/components/extensions/ext-browser.json

Which I just found out about too :)

```
andym> browser.identity should be working on Android? its in toolkit and documented as working on MDN
<rpl> andym: it is currently only registered at browser level and so it should only be available on Firefox Desktop: https://searchfox.org/mozilla-central/rev/f42618c99dcb522fb674221acfbc68c2d92e7936/browser/components/extensions/ext-browser.json#92-99
<rpl> andym: also, which is also an additional confirmation, the related mochitest is currently disabled on Android: https://searchfox.org/mozilla-central/rev/f42618c99dcb522fb674221acfbc68c2d92e7936/toolkit/components/extensions/test/mochitest/mochitest-common.ini#96-97
<•andym> thanks rpl
<andym> do ext-toolkit.json and ext-browser.json outline whats available in android and desktop then?
<aswan> andym: things in ext-toolkit are available everywhere
<aswan> things in ext-browser.json are on the desktop
<andym> right, thanks
```

**Comment by wbamberg** [comment]
Thanks again, and ugh. I just filed https://github.com/mdn/browser-compat-data/pull/822 for this error, and https://github.com/mdn/browser-compat-data/issues/824 to check for other errors like this.

**Comment by andymckay** [comment]
Closing this, in favour of those bugs, thanks @wbamberg

**Comment by JRF-2018** [comment]
Thanks.

**Comment by diegodlh** [comment]
Sorry for resurfacing this old issue, but I thought it was better to post this here rather than opening a separate one. Let me know if I should do that instead.

Does anyone know if there are plans to have this Identity API in Firefox for Android? I was hoping that it would be supported in the new version, but apparently it isn't.

Thanks!
