### ISSUE TITLE
search for "countdown" but shown "downloader"

### ISSUE THREAD

**Issue by sharuzzaman** [mozilla/addons#613]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Click this link:
https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=countdown&sort=relevance

### What happened?

All add on shown have word "download", "downloader", "downthemall", and none is actually is a countdown add on

### What did you expect to happen?

I want add on that do countdown, similar like https://chrome.google.com/webstore/detail/calendar-and-countdown/caplfhpahpkhhckglldpmdmjclabckhc?utm_source=chrome-app-launcher-info-dialog , but being shown downloader instead

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Will try to attach screenshot to report if possible

**Comment by sharuzzaman** [comment]
screenshot: https://drive.google.com/file/d/1lxP6wWttrI44U0KcKj7rA3eN-fKs1k_x/view?usp=sharing

**Comment by tofumatt** [comment]
Is there an add-on you can link to that is not showing up on the page that you think should? Otherwise it could be such an add-on doesn’t exist and these are the best results available, which isn’t really a bug. Please re-open if there’s a specific add-on that exists on the site you think should be in the results.

**Comment by sharuzzaman** [comment]
https://addons.mozilla.org/en-US/firefox/addon/countdownclock/
https://addons.mozilla.org/en-US/firefox/addon/tea-timer/?src=search - "countdown" in description
https://addons.mozilla.org/en-US/firefox/addon/countdown-timer/
https://addons.mozilla.org/en-US/firefox/addon/sptimer/ - "countdown" in description

I cannot re-open this ticket because it is not closed by myself.

- you cannot re-open your own issues if a repo collaborator closed them -- see https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by tofumatt** [comment]
cc @diox I suppose, wonder why these add-ons aren't appearing in the search.

**Comment by diox** [comment]
Hi,

There are 2 problems here:
- None of these add-ons are compatible with Quantum (they are pretty old). They'd appear when searching from an older version of Firefox compatible with them.
- Because of various factors even when using an older version those add-ons show up very very far down in the results. 

There is an ongoing issue to improve relevancy of search results, mozilla/addons-server/issues/2661, so I'm going to close this.
