### ISSUE TITLE
Add support for two factor authentication, then require it

### ISSUE THREAD

**Issue by mlissner** [mozilla/addons#631]
### Describe the problem and steps to reproduce it:

Extensions have surreal amounts of access to people's private data, cookies, and browser. The top three extensions have a combined 20M users. Firefox's reputation is closely tied to the extensions ecosystem.

At the same time, unsolicited emails are pretty common from AMO. Imagine an email that says:

> Your add-on has been reviewed by Mozilla and we have identified 3 new issues. Please log in to review and resolve these issues.

> https://addons.mozillla.org/oauth/signin

I'd click the hell out of that link even though mozilla is spelled with an extra L, and if it made me sign in, I might think twice, but I doubt even then I'd catch it.

I also note that in issue #349, there's some discussion about reducing session length. That'd normalize random logins. (This is already an issue on the Chrome add-on store, which regularly requires a sign in.)

To fix these problems, we should begin supporting and encouraging two factor authentication keys for any account that can upload new versions of extensions. That will mitigate most phishing attacks. 

After a period of time, we should make two factor authentication a requirement. I'd suggest rolling out enforcement for it slowly, starting at popular extensions and then moving down the chain until it is required for all extension authors.

**Comment by tofumatt** [comment]
We don't handle our own authentication; it's handled by Firefox Accounts. You raise a good point and I think a 2FA solution for FxA would be cool, but it is a bug you'd need to file at https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Server%3A%20Firefox%20Accounts

I'm closing this because it's related to addons but not something the team can really work on/address. That said I think it's a good point and worth raising with the Firefox Accounts team, who handle our authentication.

**Comment by mlissner** [comment]
I guess this is the official bug for it:

https://bugzilla.mozilla.org/show_bug.cgi?id=1379677

There's also another dup (I guess?) here: 

https://github.com/mozilla/fxa-oauth-client/issues/8#issuecomment-316258116
