### ISSUE TITLE
Proposal: Publish API

### ISSUE THREAD

**Issue by heubergen** [mozilla/addons#643]
I think that Mozilla should think about writing and maintaining a Publish API like Chrome has it (https://developer.chrome.com/webstore/using_webstore_api).

As MVP it should allow developers to update there existing items through this API, later it should also support to create and modify items.

This API would save time for many developers and would help them to streamline there development process. There are examples of companies who don't publish there add-ons on AMO just because of this missing API.
If this is the wrong place to suggest something like this, please advise me where I should rather do it.

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file an issue. I agree! We almost have it but it's not ready for use yet.

Here are some notes:

- It is already possible to use the [signing API](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html) to publish an extension (see [web-ext sign](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Signing_your_extension_for_distribution)) but this only lets you self-host an extension rather than host it on addons.mozilla.org
- It is possible to use the signing API to [submit new versions](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-a-version) of *existing* add-ons in the `listed` channel which will let you keep hosting on addons.mozilla.org
  - The `sign-addon` library will be [patched](https://github.com/mozilla/sign-addon/issues/248) to support this soon.
- It is not yet possible to [submit a *new* add-on](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#uploading-without-an-id) through the API and have it be listed on addons.mozilla.org. This still requires work to make sure all metadata is captured for the new add-on.
- All of our terminology refers to "sign" when really we need something separate like "publish," as you mention

**Comment by heubergen** [comment]
Thank you for the clarification. I was just searching for an existing Publish API issue here and in some other repos and didn't found any. Shall I close this issue or do you wann use it as a Meta Bug for tracking?

**Comment by kumar303** [comment]
We should keep it open because I couldn't find a bug in [addons-server](https://github.com/mozilla/addons-server/) about it. Maybe there is one somewhere.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/7811 is the addons-server issue about adding full listed submission.
