### ISSUE TITLE
Message when Submission API throws an error

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons#654]
Related to issue [#1872](https://github.com/mozilla/addons-linter/issues/1872) on the add-ons linter repo.

We talked about this at today's [community meeting](https://docs.google.com/document/d/1cM9cPnMy_5E0UMIK63LFU4lIAJ7AqtRcZHVltyDr13Y/edit#heading=h.6hz4cywoeyww) and I wanted to open up a discussion for how we can better support developers who encounter errors with the submission API. 

One idea is that a validation error would trigger a message from the linter or from web-ext that would proactively encourage developers to file an issue if the error message is buggy.

**Comment by Marat-Tanalin** [comment]
It would probably make sense to first test new linter versions as _optional_ beta versions instead of blindly making the linter live thus preventing addon developers from updating their addons due to a possible linter bug.

For example, a beta version could be _suggested_ to be tested by addon developer during uploading his new addon version. This way this would be opt-in instead of forced and harmful.

**Comment by diox** [comment]
We are not pushing new linter versions blindly. QA does test linter issues, we should be (and are) finding regressions before they are pushed to production.
