### ISSUE TITLE
Change the "Add to Firefox" to "Added to Firefox" when an addon has been installed.

### ISSUE THREAD

**Issue by tipar** [mozilla/addons#655]
### Describe the problem and steps to reproduce it:
When I install an addon and I come back to the page of the addon, the "add to Firefox" is always unmarked. It is as if I did not install the addon and I can not tell whether an addon has been added or not to Firefox. It is annoying.

### What happened?
The "add to Firefox" is always unmarked even if I install the addon.
### What did you expect to happen?
I expected to find the blue color of "add to Firefox" in red or green or at least that I could read "added to Firefox".
### Anything else we should know?
![sin titulo](https://user-images.githubusercontent.com/28825525/36901060-972a26f2-1e1d-11e8-9eab-bb4a34f4bd0d.png)
As you can see on the right menu the addon is installed but I still see the "add to Firefox".

**Comment by tofumatt** [comment]
Thanks for filing this issue! 😄 

We're aware this feature is missing; we had to remove it when changing the install button implementation but are tracking it here: https://github.com/mozilla/addons-frontend/issues/3954

Once that issue is fixed the button will be aware of install states again, so I'm going to close this in place of that issue; please subscribe to https://github.com/mozilla/addons-frontend/issues/3954 if you want updates on the progress.
