### ISSUE TITLE
Firefox add-on update bug (Alitools)

### ISSUE THREAD

**Issue by IgorSlizen** [mozilla/addons#659]
Hello, Firefox AMO team. 

Hello, Rob, Andrew and Firefox team.
 
1. I back to you with a question about additional warnings prompts again.
We add warning prompt in our add-on that AliTools requires permission for access user data from all sites. (https://prnt.sc/im7xg3).
 
After every update of our addon, when we add new online stores in AliTools our users see warning that our add-on requires permission for access to user data from new sites. (https://prnt.sc/im7gib)
We have a problem again while updating the extension.
 
2. I made a small screen capture video to describe problem.
I Install 4.0.4 Version AliTools
Click Update extension from extension context menu
Here is the link to dropbox with video: https://www.dropbox.com/s/63wugzggwo4p6ae/Firefox.%20AliTools%20Upadate.mov?dl=0

3. Our extension requests permissions to access all sites:
"permissions": [
 "http://*/*",
 "https://*/*",
 "tabs",
 "contextMenus",
 "webNavigation",
 "notifications",
 "cookies"
],
 
Content scripts are used only on sites where necessary:
"content_scripts": [
{
 "matches": [
   "*://*.aliexpress.com/*",
   "*://*.banggood.com/*",
   ...
The problem is that when we add a new URL for content scripts, Firefox asks users to access new sites after updating. 
 
Will wait for your reply. 
 
Kind regards, Igor. 
Product manager in Big Data Technologies.
E-mail: igor.slizen@bdtech.by
Skype: igor_slizen
Telegram: @IgorSlizen
Site: alitools.io

**Comment by jvillalobos** [comment]
If an add-on requires additional permissions, Firefox prompts the user for those permissions. That is by design.

To reduce permission prompt, I would suggest grouping permission changes as much as you can, or include domains you anticipate you will be requiring permissions for.

This github repo is for the add-ons website. You can continue this discussion in any of [these other channels](https://developer.mozilla.org/en-US/Add-ons#Contact_us).
