### ISSUE TITLE
statistics dashboard only refreshes for 24 hours.

### ISSUE THREAD

**Issue by vamshi9666** [mozilla/addons#696]
presently in AMO developer hub . i can see changes in statistics dashboard after a day .  If some people added my addon , i can see increase in downloads only after a long time .
so it would be good , that statistics will be updated instantly.

**Comment by jvillalobos** [comment]
The way stats are processed right now doesn't allow for a shorter cadence. Also, since the dashboard groups numbers by day, it would require deeper changes to support it. I don't expect us to make these changes anytime in the future. A daily cadence seems sufficient for the majority of developers and is on par with what I see on similar websites.
