### ISSUE TITLE
Cannot install addons

### ISSUE THREAD

**Issue by kaiji0811** [mozilla/addons#703]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
Cannot install addons.
In spite of using newest version of Firefox(version 59.0.2 64 bit), but Firefox add-ons sight said me as above.
"このアドオンは より新しいバージョンの Firefox (48.0 以上) を必要とします。あなたは Firefox 33.0 をお使いです。"

### What did you expect to happen?

it will be able to install add-ons correctly.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
@kaiji0811 please can you provide the link of where you were when you saw this message?

**Comment by wagnerand** [comment]
Go to `about:config` and check if `privacy:resistFingerprinting` is set to `true`.

**Comment by closingin** [comment]
@wagnerand Do you know that's what I said just above ? :thinking:

**Comment by muffinresearch** [comment]
I've filed this issue to track the work to re-enable the button in this case: https://github.com/mozilla/addons-frontend/issues/4910 please follow along there.

**Comment by kaiji0811** [comment]
Thank you for your research.
In summary, was the problem happened cause of `privacy.resistFingerprinting` is set to `true`?
I tried to install add-ons(it's foxy proxy standard), installation is successfully.
in addition, my `privacy.resistFingerprinting` is set to `false`.

**Comment by closingin** [comment]
@kaiji0811 The message appeared because your User-Agent (which mozilla addons rely on to detect your Firefox version) has been changed by yourself or an addon you installed.

But whatever the reason for this is, it will get fixed as we'll surely be able to force the installation of an addon soon.  Follow the evolution here : https://github.com/mozilla/addons-frontend/issues/4910
