### ISSUE TITLE
Cannot delete add-on

### ISSUE THREAD

**Issue by evandrix** [mozilla/addons#705]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
1. https://addons.mozilla.org/en-US/developers/addons
2. https://addons.mozilla.org/en-US/developers/addon/ee6dd14500d549b1b054/edit
3. "Manage Status & Versions"
4. "Delete Add-on"
5. Confirm by entering Add-on ID ee6dd14500d549b1b054, as the dialog instructs
6. Error message in the next section below is displayed

### What happened?
Error message, e.g. https://addons.mozilla.org/en-US/developers/addon/ee6dd14500d549b1b054/delete

> Oops! We had an error.
> We'll get to fixing that soon.
> You can try refreshing the page, or head back to the Add-ons homepage.

### What did you expect to happen?
The add-on should be deleted, and the associated entry should be removed from my account listing

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
I want to get rid of the following Add-ons, but this error is preventing me from doing so:

1. https://addons.mozilla.org/en-US/developers/addon/ee6dd14500d549b1b054/delete
2. https://addons.mozilla.org/en-US/developers/addon/49991e30e11c439797b6/delete
3. https://addons.mozilla.org/en-US/developers/addon/0669557a5ef74c6baad6/delete
4. https://addons.mozilla.org/en-US/developers/addon/ebc5c1b1f8c5419a8767/delete

**Comment by wagnerand** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/4267868/

**Comment by eviljeff** [comment]
ops looked into it:

16:48 philipcristiano> 2018.04.12 had migrations 1009 and 1011
16:54 eviljeff: "Any migration file with a number greater than the current version will be applied to the database and the version tracker will be upgraded." -https://github.com/mozilla/schematic
16:55 So merging 1011 first updated the version to 1011, then 1010 wouldn't be run because it was lower than the current version

16:59 eviljeff> I added the 1011 migration, knowing there was going to be a 1010 migration in the other pull request. And then merged them in the wrong order.
17:00 And that wouldn't have been a problem for stage and dev if I also hadn't merged the pull that added the 1011 migration just before the tag, and the 1010 one after the tag.

**Comment by eviljeff** [comment]
QA: this needs to be an add-on that would be hard-deleted (i.e. all the records are cleared from the database).  We only do this for add-ons without any versions (included deleted versions) and the way devhub works should make this impossible, but for an upload via the signing API it is possible, if the version doesn't pass validation or is broken in some way. 

So STR:
* upload a new add-on via the signing API with a version that won't pass validation but has a valid manifest (e.g. a javascript syntax error)
* check in devhub that the add-on is incomplete and has no versions.
* delete the add-on via devhub

**Comment by AlexandraMoga** [comment]
I've submitted an add-on via the signing API that normally would not pass validation, made sure it had no versions listed in DevHub and then I've deleted the add-on from Manage Versions page.
There were no errors received and the add-on was successfully deleted.

Marking the issue as verified fixed on AMO-dev and stage with FF59, WIn10x64.

**Comment by evandrix** [comment]
i can now delete these addons from my account. thanks much~! ^_^
