### ISSUE TITLE
"Request was throttled" is annoying on developers replies to review

### ISSUE THREAD

**Issue by mi-g** [mozilla/addons#718]
As an add-on developer, reply several reviews. You quickly get a "Request was throttled" and are notified of a 30-60 seconds waiting period before being able to submit the answer.

For developer replies, this mechanism is unnecessary and very annoying. I got a large number of reviews everyday and often give up answering because of this.

**Comment by bobsilverberg** [comment]
This seems like a valid concern, but I think the issue needs to be with addons-server. What do you think @eviljeff?

**Comment by eviljeff** [comment]
It does need to be fixed on addons-server, yep. Its currently set to 1/minute.  We actually [added](https://github.com/mozilla/addons-server/pull/7048) it to work around a database race condition more than abuse.

**Comment by AlexandraMoga** [comment]
FYI, we also reported a concern with regards to the actual error message displayed in [frontend-issue#4007](https://github.com/mozilla/addons-frontend/issues/4007)

**Comment by diox** [comment]
This is clearly annoying and should be fixed. Sadly, just un-throttling developers would just expose the issue we were trying to work around by adding the throttling (https://github.com/mozilla/addons-server/issues/6952 as @eviljeff points out) so we need to be careful about changing this.

Maybe just make the throttling smarter, or fix once and for all the database constraint on this model (would require cleaning up old data, since previously we did allow multiple ratings from the same user on the same version).

**Comment by eviljeff** [comment]
We could drop the throttle time (at least for replies) down to a few seconds, which _should_ still be enough to stop DB issues while not being as annoying for developers.

The DB constraint alternative is probably changing both `is_latest` and `deleted` to be ints rather than bools like @diox suggested in [mozilla/addons-server#6952](https://github.com/mozilla/addons-server/issues/6952#issuecomment-346868497) but that migration will be unfun.

**Comment by diox** [comment]
I agree that dropping the throttling down to a few seconds would work, but we'd have to implement it completely ourselves, as DRF only gives you one second / one minute / one hour / etc granularity.

**Comment by AlexandraMoga** [comment]
The throttling time for developer replies has been significantly reduced. The maximum waiting time I've got when posting  really fast replies was 3.0 seconds.

![throttle](https://user-images.githubusercontent.com/31961530/40704761-c06dd6d4-63f1-11e8-8812-7b5a01775a08.gif)

Marking issue as verified fixed on AMO stage with FF60, Win10x64
