### ISSUE TITLE
Filtering functionality required for FF/AMO compat

### ISSUE THREAD

**Issue by mkleef** [mozilla/addons#72]
Downloaded the latest version of FF 45 and went to find complete themes. A significant portion of the themes are not compatible. Would be great to filter by only the themes that are compatible with my browser rather than having to wade through 400+ of not compatible ones. Side benefit is that it (marginally) should reduce web server load due to more efficient interaction.

**Comment by brampitoyo** [comment]
This would be an interesting feature to have. What if AMO search result is tailored to your version?

In one way, this is a bad thing. If your version is too old (or too new) to get certain well-known add-ons, you’re not going to see it and you might be confused or frustrated as to the reason why.

In another way, what we can do in that situation is say “Upgrade to the latest Firefox to ensure that you always see the latest add-ons”.

Thoughts?

**Comment by jvillalobos** [comment]
Search is filtered by compatibility for extensions, and I agree it's the most desirable way to do it. I think it's only broken for complete themes.

**Comment by brampitoyo** [comment]
I do remember seeing the search filters not selecting the version that matches my Nightly.

For example, I just did a search and took this screenshot:

<img width="200" alt="screen shot 2016-03-22 at 11 24 20" src="https://cloud.githubusercontent.com/assets/51007/13936182/c814680e-f020-11e5-9865-1e4b7c99480a.PNG">

I think this problem is isolated to Nightly, though. DevEdition, Beta and Release have the correct versions selected.

**Comment by andymckay** [comment]
Given the expected lifespan of complete themes, I don't think this is worth doing now.

**Comment by tofumatt** [comment]
Agreed, I already find them to be a mess of compatibility. I think we should close this. I don't think we should be pushing a feature when we've already announced a plan to remove it.
