### ISSUE TITLE
Search addon results are unrelated to search term "tablet"

### ISSUE THREAD

**Issue by mocking** [mozilla/addons#729]
### Describe the problem and steps to reproduce it:
I searched for "tablet" on the addons website:
https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=tablet

### What happened?
Most results are unrelated to "tablet". Clicking on a few of the results show that they don't even have the word "tablet" in the addon details.

### What did you expect to happen?
Only show results with the words "tablet" in the addon details.

### Anything else we should know?
There are 57 pages of results in the search and if the first page only has 2 out of 25 extensions that are related to "tablets", I probably won't page through the remaining 57 pages.

![tablet1](https://user-images.githubusercontent.com/1511818/40823666-c1ddd27c-65a3-11e8-9916-3536c9956d54.png)
![tablet2](https://user-images.githubusercontent.com/1511818/40823688-d9ccfcd2-65a3-11e8-90fe-69f25a79b9a9.png)

**Comment by diox** [comment]
This will never please everyone because we need to help people searching for "tabsomething" find add-ons about tabs, but it has gone better with https://github.com/mozilla/addons-server/issues/6898 : the first 2 extensions are about tablets (if including themes, the first themes shown also have "tablet" in their names).
