### ISSUE TITLE
Add ability to filter by author in language tools API

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/addons#730]
This it the last known issue blocking https://bugzilla.mozilla.org/show_bug.cgi?id=1429610

We need to filter langpacks/dictionaries to only include ones provided by Mozilla RelEng Team when selecting ones to show in Preferences.

aswan says that he's not very opinionated on how to do that - we can probably add an author ID to the query, or get list with authors and filter by it, either should work fine for us.

**Comment by diox** [comment]
I was hoping to avoid that, it makes the query worse... I guess we still have heavy caching to save us...

**Comment by zbraniecki** [comment]
I'm sorry to hear it causes issues.

Are language tools APIs used anywhere else? If not, maybe we could just limited them to Mozilla RelEng provided addons?

**Comment by diox** [comment]
We have no good way of identifying the add-ons besides the author (IIRC their `guid`s vary), and both fetching and filtering are an issue because of the way the tables are set up (and the fact that we fetch a lot of add-ons at once in this API).

However with the caching it's probably not entirely terrible, there will be a slight performance loss on cold cache but it should be bearable. I'll look into it and implement what's less worse :)

**Comment by zbraniecki** [comment]
Thank you!

**Comment by diox** [comment]
Fix will land on dev shortly and be in next week's tag. It adds support for passing `author=mozilla` query parameter in the language tools API to filter add-ons where the user with the username `mozilla` is a listed author.

**Comment by AlexandraMoga** [comment]
Verified on -dev by sending the following request:
```
https://addons-dev.allizom.org/api/v4/addons/language-tools/?type=language&app=firefox&author=mozilla
```
I've looked at some of the results and in all cases Mozilla was listed as author or one of the authors.
