### ISSUE TITLE
Submit button for review reply is labeled "Submit review"

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons#738]
### Describe the problem and steps to reproduce it:
 - Reply to review on AMO

### What happened?
Submit button was labeled "Submit review"

### What did you expect to happen?
Submit button should be labeled "Submit reply".

**Comment by muffinresearch** [comment]
@freaktechnik can you provide a URL + screenshot please?

**Comment by freaktechnik** [comment]
I've just tested this again, and it appears to only happen when editing a reply in the old single-review interface (that is linked from the new rating mails). When initially submitting it the button label is now just "Submit".

![image](https://user-images.githubusercontent.com/640949/42281854-0f55c7c4-7fa5-11e8-9050-6abbd19c7d82.png)
URL: https://addons.mozilla.org/en-US/firefox/addon/notification-sound/reviews/1142245/#review-reply-edit-form

**Comment by kumar303** [comment]
Hi @freaktechnik . We aren't really working on the legacy site anymore. Is there something specific that makes the new site hard to use for replying to reviews? If so, I'd recommend filing issues because we are making time in Q3 2018 to improve all things related to reviews/ratings. We know they are still rough around the edges.

**Comment by freaktechnik** [comment]
the reason I came across this is mainly because the mails still link to the old site to reply to reviews.

**Comment by freaktechnik** [comment]
I think the email no longer links to this page, so this is resolved in my eyes.
