### ISSUE TITLE
Can't use addon to render local markdown file

### ISSUE THREAD

**Issue by zqcc** [mozilla/addons#757]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
i try to open a local markdown file using an addon on linux.
### What happened?
Not a single addon can really work.Always firefox will ask me whether to save the file.
### What did you expect to happen?
the file should be handled by addon, then i can read markdown file
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
i have tried these addons : Markdown Viewer Webext  ,GitLab Markdown Viewer

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check (discourse.mozilla.org)[https://discourse.mozilla.org/] for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
