### ISSUE TITLE
 Add-ons: sorting by popularity DESC

### ISSUE THREAD

**Issue by agnieszkadab** [mozilla/addons#760]
### Describe the problem and steps to reproduce it:

1. visit https://addons.mozilla.org/en-GB/firefox/collections/mozilla/social-media-customization/?collection_sort=popularity&page=1 (or any other list of Firefox extensions except featured ones)
2. in field "Sort add-ons by" choose "Popularity"

### What happened?
The extensions with highest number of users, including featured extensions like Facebook Container, are at the bottom of the list. Seems like they are sorted descending, not ascending.

### What did you expect to happen?
Most popular extensions should be listed first.

### Anything else we should know?
https://screenshots.firefox.com/q33ZmzWpRY2L0b86/addons.mozilla.org
Browser: Firefox Nightly 63.0a1x32 (2018-07-23)

**Comment by diox** [comment]
Interesting. This is technically a frontend issue, but IMHO it's caused by an inconsistency in our API. [The collection API docs say the following](http://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-add-ons-list):

Parameter | Description
-- | --
added | Date the add-on was added to the collection, ascending.
popularity | Number of total weekly downloads of the add-on, ascending.
name | Add-on name, ascending.
> All sort parameters can be reversed, e.g. ‘-added’ for descending dates. The default sorting is by popularity, descending (‘-popularity’). There can only be one sort parameter, multiple orderings are not supported.

The frontend is sending `sort=popularity` and not `sort=-popularity`, causing the issue. However, this is inconsistent with the way the sort parameter works with the search API, which doesn't let you choose between descending and ascending order for its parameters.

I'm not sure what can be done about this on the server side, if anything. @eviljeff @EnTeQuAk any thoughts?

**Comment by AlexandraMoga** [comment]
I think a similar issue was already reported on addons-frontend - https://github.com/mozilla/addons-frontend/issues/5581

**Comment by eviljeff** [comment]
Yeah, it looks like the API is consistent. Assuming `sort=popularity` is a legacy supported thing then frontend can't just pass it along as is - it will have to be translated to the correct API value

**Comment by diox** [comment]
Having `sort=popularity` sort by popularity ascending in collection API and `sort={anything}` sort by `{anything}` *descending* in the search API is weird and inconsistent, though.

**Comment by eviljeff** [comment]
I don't know what a solution would be, exactly. 

Remove functionality from the collections endpoints to match the search api's sorting deficiency and change `popularity` to mean `-popularity? (Both breaking changes, and seem wrong)

**Comment by diox** [comment]
As I said above I don't know either, I was hoping someone would have a good suggestion... Maybe just making the difference more obvious in the docs ?

**Comment by eviljeff** [comment]
Change the search endpoint to match? :wink:?

**Comment by bobsilverberg** [comment]
Oops, I just noticed this is filed under addons, not addons-frontend, so I'll just use the already opened https://github.com/mozilla/addons-frontend/issues/5581 to fix the issue and this can probably be closed.
