### ISSUE TITLE
Archive legacy extensions after Firefox 62 (rather than deleting them permanently)

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/addons#766]
Right now, it seems the plan is to delete all legacy extension files after Firefox 62 rolls out, with only the extension IDs linked to the developer accounts remaining.

I’d much rather prefer if legacy extensions were instead archived and available for download for third party forks or those wishing to look into Firefox’s history.

**Comment by jvillalobos** [comment]
The current (tentative) plan is to disable all legacy versions in early October. We don't intend to archive the content, but others have shown interest in doing this (see https://mail.mozilla.org/pipermail/dev-addons/2017-August/003057.html).

**Comment by MikeRosoft** [comment]
Is "disable" an euphemism for "delete"?

**Comment by diox** [comment]
No. Developers still have access to the legacy versions of their add-ons, they are just not available for users anymore on addons.mozilla.org. That being said, eventually they'll be deleted for good, we have no intention of keeping them forever.

Before disabling them, we worked with [ArchiveTeam](https://archiveteam.org/) so that they'd be archived for posterity. You can find the archived content over here: https://archive.org/details/addons.mozilla.org_legacy_201810
