### ISSUE TITLE
Searching for "wordlist" finds results which don't even mention wordlists

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#779]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

go to addons.mozilla.org and search "wordlist"

### What happened?

most results are password managers, or are themes involving swords. few results even mention wordlists, let alone provide tools to block the things from search engines.

### What did you expect to happen?

I expected to find 1 page without anything relevant, not 26 pages without anything relevant.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
Searching for "word list" does yield some better results. What kind of add-on where you looking for?

**Comment by MarjaE2** [comment]
tools to block wordlists from search engine results, so I can find useful results without searching for a needle in a haystack.

**Comment by MarjaE2** [comment]
Example of wordlists:

![screen shot 2018-08-28 at 5 05 37 pm](https://user-images.githubusercontent.com/12875862/44751037-1583ec00-aae5-11e8-8e6e-ca7923a90e2c.png)

**Comment by diox** [comment]
Ultimately there isn't much we can do here - there simply aren't many add-ons relevant to your query (I'm not aware of any add-on providing the exact functionality you're looking for). Like pointed out in the first reply, changing the query to "word list" with a space helps - "wordlist" without a space is used by some add-ons like password managers, and that's why you get them in search results.

If you do find an add-on that does what you were looking for, add a comment and we'll look into why it was not appearing in your search results.

**Comment by MarjaE2** [comment]
changing the query to "word list" with a space helps

It gets some results which include the phrase, without helping, and some spurious "results" which do not. 29 pages to search through. For example, "tab list" on page 1 does not include the search phrase.
