### ISSUE TITLE
Test Akismet integration with Ratings on -dev and stage

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#781]
Once ops have added the API key to the env the ratings and admin work can be tested.

Basically all the closed issues in https://github.com/orgs/mozilla/projects/30, in particular mozilla/addons-server#8702 and mozilla/addons-server#8702

**Comment by eviljeff** [comment]
I've enabled the waffle on -dev.  Feel free to enable the `akismet-spam-check` waffle on stage for testing there too if -dev testing goes okay..

**Comment by eviljeff** [comment]
You'll need to use /admin to check the akismet reports are logged after ratings have been added or edited.  Once you have some reports in admin the report spam/ham actions will be testable.

**Comment by AlexandraMoga** [comment]
I have completed a round of testing on -dev and overall the functionality works fine.
I have a few observations with regards to how spam is detected: 
- there were quite a large number of reviews that should have been categorized as Spam but the tool did't see those as harmful.  Especially for reviews that contain suspicious URLs or email addresses, the tool should be more strict. 
Here are some examples that were not detected as spam:

[1]
![image](https://user-images.githubusercontent.com/31961530/45223249-6fdc3400-b2bf-11e8-82a9-14dc6a0e5433.png)
[2]
![image](https://user-images.githubusercontent.com/31961530/45223261-74a0e800-b2bf-11e8-8e33-d7648354ac2e.png)
[3]
![image](https://user-images.githubusercontent.com/31961530/45223276-808caa00-b2bf-11e8-9f1a-128655cb50de.png)

**Reviews Moderation Log**
- reviews detected as Spam are logged in the moderation queue
- reporter is Mozilla and the report date is correctly set (GMT time)
- flag reason is "Spam or otherwise non-review content"
- the user review is listed in all reviews page until the moderator decides to delete it 

**Akismet Report - Admin**
- each time a review is submitted a report is logged in Akismet reports
- so far, I have only seen 'Ham' and 'Maybe Spam' results. Nothing detected as 'Definite Spam' 
- Admins can change the report type to 'Ham' or 'Spam', depending on the case
- Admins can report a result only once. On a second attempt, the following message is received "0 Spam reports submitted as <Ham/Spam>; 1 reports ignored"
- filter are working as expected
- Search is working pretty well, and will keep count of the current filter applied

The 'user-review' link for each report doesn't load the page it is supposed to, so I've filed https://github.com/mozilla/addons-server/issues/9381 for that

I'm going to have a look at stage to see if everything looks fine there as well

**Comment by eviljeff** [comment]
> there were quite a large number of reviews that should have been categorized as Spam but the tool did't see those as harmful

On prod we should be able to train Akismet to see those as spam too by reporting them as spam.  That's the idea anyway.

**Comment by AlexandraMoga** [comment]
Verified fixed in -dev and stage.
The issues found so far have been reported separately.
