### ISSUE TITLE
A valid add-on is not brought up in TB search on relevant search terms

### ISSUE THREAD

**Issue by native-api** [mozilla/addons#80]
[Searching in TB 38.7.0 for "header tools"](https://services.addons.mozilla.org/en-GB/thunderbird/api/1.5/search/header%20tools/all/30/WINNT/38.7.0/normal?src=thunderbird) doesn't bring up [Header Tools Lite](https://addons.mozilla.org/ru/thunderbird/addon/header-tools-lite/) for some reason.

The add-on is compatible with this version, so this cannot be a reason to omit it.

(Just in case, I'm not affiliated with the add-on's authors)

**Comment by diox** [comment]
That add-on is *Preliminary Reviewed*. By design¹ the legacy search API, that Thunderbird's (and Firefox's) Add-ons Manager uses, is restricted to *Fully Reviewed* add-ons. You can see the Add-on in the regular search page on the site: https://addons.mozilla.org/en-US/thunderbird/search/?q=header+tools&appver=&platform=

¹ I don't know why, I just know [it's explicitly filtering in the code, with a comment explaining that it's done on purpose](https://github.com/mozilla/addons-server/blob/0635817f20389efd24303a7b8294a7e50dcb880c/src/olympia/legacy_api/views.py#L340). We could investigate more and possibly change it, but this has repercussions that would need to be discussed with the rest of the Add-ons team.

**Comment by wagnerand** [comment]
Yes, this is by design.
