### ISSUE TITLE
Gboard do not work

### ISSUE THREAD

**Issue by LookForPi** [mozilla/addons#808]
### Describe the problem and steps to reproduce it: It do not work to highlite some thing in Firefox
(Please include as many details as possible.)

### Anything else we should know? Make an own keyboard so we do not need Googles Gboard, please!
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
