### ISSUE TITLE
public reviewing stats or report

### ISSUE THREAD

**Issue by Jan02** [mozilla/addons#829]
i.e.    x reviewers approved y addons for q1 2018

x reviewers rejected y addons for q1 2018

etc

**Comment by wagnerand** [comment]
We don't publish review statistics anymore because we're using a different review model and review numbers would be misleading because they don't reflect the risk or impact (imagine the difference between 100 add-ons reviewed that have 10,000 users in total vs 60 add-ons reviewed that have 20 million users in total; numbers just for illustration).
