### ISSUE TITLE
Consider showing Update as an option for outdated and installed extensions

### ISSUE THREAD

**Issue by siffegh** [mozilla/addons#834]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
I went to addons. mozilla.org to update an extension that I know had been updated.

### What did you expect to happen?
I expected to see an Update button, but there's only a Remove button. 

### Anything else we should know?
I know I can remove and reinstall, but I'll lose my settings if I do that.
I also know I can go to the 'All versions' page and update from there. For various reasons including problems providing tech support for an extension, that option is way far from ideal.

Is this a (known) bug? If not, are there plans to make it work like I want?

**Comment by jvillalobos** [comment]
Extensions update automatically once a day. You don't need to go to the site to get the update. If it's really urgent for you to get the latest version you can Check for Updates in `about:addons`, or go to the All Versions page like you mentioned.

I don't think we'll add more options to support that use case, so I'm closing this issue.

> I know I can remove and reinstall, but I'll lose my settings if I do that.

This isn't necessarily true, but it varies from extension to extension.

**Comment by filbo** [comment]
We have users who know our extension has updated, so are eager to pick it up.  They're on version 22, AMO has version 23 but presents them only with a Remove button.  They don't know any better and apply the Remove button.  Our extension's settings are in localStorage and get vaporized on remove-reinstall.

This design of AMO is breaking our extension and our users.  This behavior is broken.

Yes it is **possible** for a user to dodge around this, if they know in advance that remove-reinstall is going to vaporize their settings.  Some manage to avoid the pitfall.  Some do not.  There is no possible way to educate all users sufficiently to avoid some losing their settings.  The site should not mislead and encourage them to destroy their settings.

Our extension can have a lot of complex state which it is unpleasant to lose & reconstruct.  We are not talking about a dozen checkboxes, but sometimes complex snippets of CSS, filter rules and other items which the user may have collected from various places or invented themselves.  Destroying state is a serious matter.

I see the logic of offering 'Remove' because what else are you going to do when the extension is already installed?  But there is a very clear and straightforward answer to that: if you're on a back-rev version of the extension, of **course** the most likely action you're looking for is _Update_, not _Remove_.  Most especially if it is less than 24 hours since the extension update was released, so there's a high chance that the user's browser has not yet had a chance to automatically update.

**Comment by jvillalobos** [comment]
Fair enough. I'm reopening for consideration.

**Comment by imcraymond** [comment]
@jvillalobos referenced an issue I opened, which is similar to this issue.  At work behind a firewall the automatic updates do not work.  Until recently I browsed AMO in recently updated order and when I saw an add-on I used updated, I would update it manually.  Later that didn't work, but going to the all versions page was a work around.  Now that is not possible, only removing the add-on and re-adding works.

This is a fringe case, and I'm not sure of your ui guidelines, but some method to enable updating a version manually would be desirable.  In my case it's a virtual necessity.

Thanks for considering a change for this case.

**Comment by siffegh** [comment]
Well, now it appears one can't even update on the 'See all versions' page :-(

**Comment by imcraymond** [comment]
This is still an issue for me behind a corporate firewall.  It is an outlier, but would appreciate some sort of work around being made available.  The "Uninstall - Reinstall" works, but does seem to lose settings.

**Comment by filbo** [comment]
We continue to have occasional encounters with this.  End users come to us complaining that they can't install or update our extension, and it has utterly zero to do with the extension, only the peculiar behavior of the site.

**Comment by jvillalobos** [comment]
It's possible that we'll end up removing the Remove feature in the future, in order to remove special privileges being given to AMO for this to work. In that case, we would also close this issue since it won't be possible to do that either. Just thought about pointing that out in case you're waiting for this to be fixed.

**Comment by jvillalobos** [comment]
You could use the [AMO API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html) to check for updates ([for example, AdBlock Plus](https://services.addons.mozilla.org/api/v4/addons/addon/adblock-plus/)). That'll get you direct URLs to the XPI files. Having said that, you might want to tell your network admins that you're spending a lot of time trying to keep your add-ons up to date manually...

**Comment by filbo** [comment]
I don't know about @imcraymond, but I'm talking about strictly individual end-users who have nothing to do with 'my network admins'.  I work on an extension which individuals use.  I'm not going to put in a bunch of code to jimmy around with Mozilla 'store' API to try to work around its bizarre user-hostile behaviors, only to have those behaviors change arbitrarily out from under it.

If a user's config happens to contain an extension which is not at the most current version, and they visit the 'store', they bloody well should see an obvious and not-user-hostile way to upgrade to the current version.  Without any special participation from the extension's code, or even a shred of knowledge about it by the extension author.  It should Just Work.

**Comment by filbo** [comment]
Perhaps you think these are theoretical issues which 'might happen' but do not occur in the real world.

Not so.  We have multiple users run into these problems, every single time we issue a release.  They're weird corner cases, but when you have tens or hundreds of thousands of users, you will hit corner cases.  I can only imagine what happens to extension authors who have tens of millions of users.

**Comment by filbo** [comment]
This 'stale' update is a particularly bad slap in the face after what the Mozilla 'store' did to our extension recently.  If you examine https://addons.mozilla.org/en-US/firefox/addon/socialfixer/versions -- it shows precisely one version.  This is because some automated system decided that some code in our extension was insecure, so dropped it out of the 'store'.  This was code which had previously been examined and agreed _by Mozilla_ that it was safe.  The eventual 'fix' was to reissue the **identical** extension, except repackaged so the manifest claimed it was version 24.1.1 rather than 24.1.0, and this was re-accepted into the 'store'.  At which point the extension is back in service, but its **entire** past history has been vanished.

... which means that the corner cases described in this issue pretty much cannot happen at the moment.  We won't really be able to know until we've released at least one further release, maybe 2.

If we're supposed to report on whether this is an ongoing problem, please **_fix_** the past history of our extension.  And then wait a while.

**Comment by dveditz** [comment]
There are many many people who don't get addon updates, lots of people with antivirus installed or working in corporate environments (see [bug 1308251](https://bugzilla.mozilla.org/show_bug.cgi?id=1308251)).

- AMO should warn people they have an out-of-date version
- AMO should not show the Remove button in this case. "Update" would be best (kinda accomplishes the previous item, too) but even the usual "Add" button would let people easily fix the problem.

The "See all versions" page is particularly bad because it seems to imply you have all the versions installed. All you can do is look (or "Remove"). Even if you don't want to change the main extension page, the /versions/ page could be a workaround if people were allowed to download/install any version at any time without regard to what they have.

**Comment by jvillalobos** [comment]
Another hitch here is that we're trying to minimize the access privileged AMO has, so we may remove the "Remove" feature in the future. That would change the button to the default "Add to Firefox", which would be better but wouldn't totally fix this.

**Comment by siffegh** [comment]
Would still like to see this implemented.

**Comment by filbo** [comment]
This area of FF's user experience is a whirlwind of bad.  If you aren't going to pay attention and actually fix issues which hurt users, what is the point of having a bug database, or indeed a product?

**Comment by filbo** [comment]
I guess user experience is verboten.  Please close this and all other bugs in the database.

**Comment by filbo** [comment]
So impressed at this bug handling method of 'ignore it until nobody can be bothered to reply to the auto-close'.

**Comment by siffegh** [comment]
> It's possible that we'll end up removing the Remove feature in the future, in order to remove special privileges being given to AMO for this to work. In that case, we would also close this issue since it won't be possible to do that either. Just thought about pointing that out in case you're waiting for this to be fixed.

Well, 'Remove' is still there. And to install a previous version - 'Download file' - what happened to 'Install'?? The two have entirely different meanings, usually.
