### ISSUE TITLE
What happened to hover translate

### ISSUE THREAD

**Issue by plaurits** [mozilla/addons#841]
Hi
I was using this translate add on in FF earlier on.
But now when following the link https://addons.mozilla.org/en-US/firefox/addon/hover-translate/ 
I am getting "page not found".
So where do I find it or similar hover translate addon?
br Peter

**Comment by willdurand** [comment]
Hi, this is an intended consequence of the [removal of legacy add-ons from AMO](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/).

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error.
