### ISSUE TITLE
Unable to install add-ons (Download failed. Please check your connection.)

### ISSUE THREAD

**Issue by ychen10** [mozilla/addons#851]
### - What happened?

New to firefox, I tried to install some cool add-ons but failed to install any except for one ([zotero](https://www.zotero.org/download/)). It seems that no add-ons coming from https://addons.mozilla.org/en-US/firefox/ can be installed, all due to the same issue ("Download failed. Please check your connection."). For instance,
![screen shot 2018-12-15 at 12 36 13 am](https://user-images.githubusercontent.com/38701648/50039504-b3061b80-0001-11e9-9773-9b5da7f73e47.png)

As you may see in the screenshot, images in this site cannot load properly as well. I checked the console and it seems that the `GET` request was responded with `404`.

---
### - What I've done trying to solve this issue
***I duckduckgo-ed this issue and tried all the following solutions:***

- I don't have any antivirus software in my Mac, at least not that I know of.
- Added **"xpinstall.enabled => true"** and **"xpinstall.signatures.required => false"** in about:config (doesn't do anything);
- Downloaded the **.xpi** file directly using other browsers, but when I tried to add it manually, the following showed up
![screen shot 2018-12-15 at 12 45 04 am](https://user-images.githubusercontent.com/38701648/50039587-adf59c00-0002-11e9-861d-54ca9ed820ce.png)
- I tried **InstallTrigger.install({URL: "https://addons.mozilla.org/firefox/downloads/file/1168281/adblock_plus-3.4.2-an+fx.xpi?src=search"})** in the console. I got this URL by inspecting the "Add to Firefox" button in the webpage (still getting "Download failed. Please check your connection.");
- Accessed the aforementioned link directly. `GET` requests were responded with `404` as well. Interestingly, when I click on the firefox download link at [adblockplus website](https://adblockplus.org/download), it comes back with
![screen shot 2018-12-15 at 1 00 59 am](https://user-images.githubusercontent.com/38701648/50039734-ec8c5600-0004-11e9-8821-248b849a12ba.png)
***I tried opening the link in other browsers (chrome, safari) and got the same result, which is super weird. I obtained several other URLs by inspecting buttons of other add-ons and got the same `404` result, regardless of the browser.***
- I probably have tried other methods along the way but cannot recall anything significant.
---

### - Extra info
- My Mac is connected to a secure university wi-fi.
- Security Certificate:
![screen shot 2018-12-15 at 12 57 01 am](https://user-images.githubusercontent.com/38701648/50039808-cc5d9680-0006-11e9-903d-194e1fc5078d.png)
- I enabled "allow site to install add-ons" and "allow pop-ups", etc.
- Console as I click on "add to firefox"
![screen shot 2018-12-15 at 1 30 58 am](https://user-images.githubusercontent.com/38701648/50039954-68889d00-0009-11e9-9577-fb990a330b93.png)

**Comment by willdurand** [comment]
According to your third screenshot, you are using Verizon as ISP or somewhere in the proxy chain between your laptop and our servers, and it is a Verizon proxy server that replies with a 404 for some reasons, not our servers.

The answer to "why does Verizon return a 404?" is a mystery though, but the fact that you cannot download the file with another browser makes me think that the problem is related to your Internet connection.

You should try to install an add-on from another Internet connection.

**Comment by grahamperrin** [comment]
I wonder, is this bug more likely to bite when a version of an add-on is fairly recent? 

For something that was published around twenty-eight hours ago, <https://addons.mozilla.org/en-US/firefox/addon/popup-tab/> version 0.2.0: 

[2019-02-12 16:57 screen recording.zip](https://github.com/mozilla/addons/files/2856794/2019-02-12.16.57.screen.recording.zip)

– that's Firefox 65.0 in Lubuntu Linux in a VirtualBox guest; the host computer is FreeBSD-CURRENT. 

----

https://redd.it/apee0o is, I think, a combination of issues but the primary observation from the opening poster was: 

> … I get an error telling me the internet is offline despite I am online. …

– reported 2019-02-11 for a version of a theme (appearance, persona) that was published on 2019-02-07.

**Comment by grahamperrin** [comment]
The previously zipped screen recording is now at <https://photos.app.goo.gl/PbBTZNLbBvfKK7KW6>.

----

Now, here's some weirdness that might involve user agent strings: 

`2019-02-12 17:17 screen recording.mp4` <https://photos.app.goo.gl/tDhShxeRZs3EgqkZ6>

- https://addons.mozilla.org/en-GB/firefox/addon/matte-black-theme/versions/
- Lubuntu in a VirtualBox guest VM
- Waterfox 56.2.7.1 and Firefox 65.0
- Firefox consistently successfully installs all versions
- for some of the versions – the 'uppermost' (remarkably, 1.2 is above 2.0) – AMO consistently, repeatedly behaves as if there's an Internet connection issue.

**Comment by grahamperrin** [comment]
A dictionary, Firefox 65.0.2 in safe mode on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/54075002-80329300-4291-11e9-81f3-c17b0445043c.png)

- https://addons.mozilla.org/firefox/downloads/file/378137/english_greek_spelling_dictionary-0.5.6-sm+tb+fx.xpi

The report of corruption appears in Firefox but not in Waterfox.

**Comment by rishabhmw** [comment]
I am experiencing the same problem. I can't download [my own addon](https://addons.mozilla.org/en-US/firefox/addon/sauron-dark-mode/). @grahamperrin 's speculation that it's more likely to bite when the version is fairly new seems to be correct as I released a new version few hours ago. The developer dashboard also doesn't show any users using the new version, in fact there is no field for the new version in the stats.

**Comment by eladkarako** [comment]
Same problem here, 
that 'bad certificate' previously noted above sounds reasonable, 
since I've messed with <a href="https://www.telerik.com/fiddler">Fiddler</a> quite a lot lately, 
but I've cleared the profile folder, and updated to latest nightly build (https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/firefox-68.0a1.en-GB.win64.zip) and it still seems to be showing that msg.
<br/>
<img src="https://i.imgur.com/geShBmvl.png"/>

**Comment by eladkarako** [comment]
Same problem here, 
that 'bad certificate' previously noted above sounds reasonable, 
since I've messed with <a href="https://www.telerik.com/fiddler">Fiddler</a> quite a lot lately, 
but I've cleared the profile folder, and updated to latest nightly build (https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/firefox-68.0a1.en-GB.win64.zip) and it still seems to be showing that msg.
<br/>
<img src="https://i.imgur.com/geShBmvl.png"/>
<hr/>
<strong>New information</strong>
if I right click the button, and saving it to a local XPI file on my desktop, 
and then I try to load the (web)extension through <code>about:addons</code> feature <code>install add-on from file</code> I get a message that the file is corrupt.
<br/>
<img src="https://i.imgur.com/SDh8nbYl.png" />

For the lack of a 'man in the middle' such as various proxies I've used lately I assume the problem is with the processing of the signature in Mozilla's servers <strong>and/or</strong> the server that serves that XPI file :)
<hr/>
I've also tried uploading the zip without hosting it on Mozilla servers, 
just signing it and downloading it, with same result.
<hr/>
both <code>sign-addon</code> and <code>web-ext</code> NodeJS clients (that seems to be working) are returning a corrupted-XPI file as well.

**Comment by EnTeQuAk** [comment]
Do you have a link to the add-on that gives you the error?

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  I believe this is the extension:

https://addons.mozilla.org/en-US/firefox/addon/spellcheck-enabler/

I can reproduce the error and the console says the extension is invalid:

`Error: Extension is invalid`

**Comment by MattD830** [comment]
I have this same issue.  I tried all the step changing xpinstall.enabled to true, I'm using Linux so I don't have any anti-virus(and the certificate looks normal to me(issued by digicert, inc)), and I have no idea what or where this manifest is?  I tried searching the profile folder for it, but as far as the information that is provided it is non-existant.

The only thing that works is going to about:debugging and installing the xpi file that way.  But then when I close Firefox I have to reinstall the addon again.

**Comment by eladkarako** [comment]
@MattD830 it's a file that is a part of the Firefox-Addon, named <code>manifest.json</code>, 
if you haven't developed (and packed and uploaded it to <a href="https://addons.mozilla.org/en-GB/developers/addon/submit/distribution">Mozilla yourself</a>), the solution above might not work for you.

You may download the XPI from Mozilla, unzip it to a folder, delete the <code>META-INF</code> folder, edit the manifest, changing the ID to something else and signing it with the Mozilla link above, 
you might be able to fix the issue if it was caused by an actual corrupt extension.

It seems that when you visit the addon-page, the page will actually try to silent install the addon, 
with a component of the browser, which will not very informative regarding errors back to the installation page, 
so if the extension is corrupted you'll get a (local) message that there is a download problem (which it hasn't), what it actually means is that the addon GOT downloaded by there was an error while INSTALLING it.

**Comment by grahamperrin** [comment]
Spun off from https://redd.it/bkf8s9

Bugging both Waterfox and Firefox: 

![image](https://user-images.githubusercontent.com/192271/57171524-ef011800-6e0c-11e9-86bb-5faa8593ea69.png)

https://addons.mozilla.org/en-GB/firefox/addon/wood-time/

**Comment by leycec** [comment]
@willdurand: **Please reopen this Mozilla-side issue,** which was erroneously closed in error several months but remains fundamentally unresolved. As [documented by @eladkarako](https://github.com/mozilla/addons/issues/851#issuecomment-480259306) and [confirmed by numerous other developers](https://github.com/eladkarako/chrome_extensions/commit/ba25222ac5dea01cc9280aa6a59ae30e830106cf), extensions containing a manifest fragment resembling `"edge": { "browser_action_next_to_addressbar": "true" }` reliably induce this error. Given the catastrophic nature of this widespread failure, it would have been helpful if you'd attempted to manually replicate it on your end *before* summarily closing it without evidence; at the least, you might have left it open until blame could be properly assigned.

I hit this today after upgrading to Firefox 60.6.1 on Gentoo Linux, which silently removed *all* of my previously installed plugins and now refuses to install any plugins. I have little recourse but to switch away from Firefox entirely, which saddens the Mozilla loyalist in me. WaterFox it is, I guess? `</sigh>`

**Comment by xicor333** [comment]
Same thing happened for me today. All add-ons I have disabled themselves and I can't download any. Not having abp isn't fun.

**Comment by dogboydog** [comment]
Same issue for me. Upgraded to Firefox 66 on Windows, all my addons are disabled and I can't download any

**Comment by grahamperrin** [comment]
> Waterfox it is, I guess?

No, as noted above there's the same problem with Waterfox. 

Given the posting frenzy under #978 I do wonder whether there's an additional issue at this time.

**Comment by brensurio** [comment]
This happened to me too without warnings. It's been working for the past months and this happens. I only use Windows Defender.

**Comment by leycec** [comment]
> No, as noted above there's the same problem with Waterfox.

:sob:

**Comment by XiiDraco** [comment]
Just lost all my add-ons too.

Welp given that nearly if not every add-on I have tried to install in the past 30 minutes has failed there is no way Mozilla can overlook this. I guess It's just a matter of time?

It's lovely trying to get around without uBlock...

**Comment by here-abarany** [comment]
One of my work machines (Mac) had all of its addons disabled and can't install any new addons. Another work machine (Linux) at least has its addons still enabled (for now), but I can't install any new ones.

This seems like a pretty catastrophic issue to me.

**Comment by thesacredpath** [comment]
This is ludicrous. I have over 200 passwords, personal and for work that I have to have, and now I find I have to open a browser window and log into LastPass in order to copy and paste the usernames and passwords. I dislike Chrome, but I may have to switch so that I can actually get into all the things that I have to for work.

This sucks much.

**Comment by Ytmndissue** [comment]
Absolutely not cool Firefox, I consider having my addons "unverified" due to some sort of outside required check absolutely asinine. You want people to stop using your browser? You do this.

Is there some sort of modification to stop this in the future?

**Comment by Tafoplaka** [comment]
This just happened to me now too. To be honest im glad it was just me (because i was messing around just before it happened). Hope they gonna fix that issue fast.

**Comment by VeryClassy** [comment]
All of my add-ons unverified but only on one of my computers. Tried restarting my computer and then un and reinstalling Firefox. Next step is Chrome, I guess.

**Comment by Kas1894** [comment]
I highly doubt that Mozilla planned this as a "feature", it's very much a bug, and a doozy at that.

RIP Mozilla devs this Friday (US Eastern time) night. Good luck on fixing the bug!

**Comment by Ytmndissue** [comment]
/g/ is saying disabling "xpinstall.signatures.required" might let you run the installed addons regardless of their status. You get to this via about:config

**Comment by afrothundaaaa** [comment]
> xpinstall

It should be mentioned this _is_ slightly dangerous.

**Comment by Ytmndissue** [comment]
> 
> 
> > xpinstall
> 
> It should be mentioned this _is_ slightly dangerous.

Right now I'm running Firefox without noscript. I'd consider that more than _slightly dangerous_.

**Comment by afrothundaaaa** [comment]
> 
> 
> > > xpinstall
> > 
> > 
> > It should be mentioned this _is_ slightly dangerous.
> 
> Right now I'm running Firefox without noscript. I'd consider that more than _slightly dangerous_.

So true.....

**Comment by wesm87** [comment]
@Ytmndissue I tried this and had no luck getting any extensions to install 🤷‍♂

**Comment by diox** [comment]
We're aware of the issue (which is actually not related to the original problem described here, it's just the same message so that's confusing) and are working on a fix.

**Comment by diox** [comment]
From [discourse](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/13):
> We rolled-out a fix for release, beta and nightly users on Desktop. The fix will be automatically applied in the background within the next few hours, you don’t need to take active steps.
>
> In order to be able to provide this fix on short notice, we are using the Studies system. You can check if you have studies enabled by going to Firefox Preferences -> Privacy & Security -> Allow Firefox to install and run studies.
>
> You can disable studies again after your add-ons have been re-enabled.
>
> We are working on a general fix that doesn’t need to rely on this and will keep you updated.
