### ISSUE TITLE
Firefox Addons site problem

### ISSUE THREAD

**Issue by azat11** [mozilla/addons#873]
I have an old PC and still using WinXP, and as a consequence an older versions of all browsers. When I open the Firefox Addons site it always opens the mobile version, instead of the destop version. This started a long time ago, but up until recently this was easily soved by clicking "Desktop version" at the bottom of the page. But now this option is gone.
Is this solvable? Obviously without changing my PC and operating system, that much I can guess myself.
Thanks.

**Comment by JonnyThree** [comment]
this change in mozilla addons website is really a disaster. the new layout is a total garbage. 
i was sure that the "desktop version" removing was already on the road at the same time they added the link on the bottom.
i really can't understand what is the motivation to transform a site that was almost ok for everyone, in a really uncomfortable website

**Comment by EnTeQuAk** [comment]
We launched the new site a long time ago and the previous "Desktop version" was the old site that we will remove gradually.

https://blog.mozilla.org/addons/2017/10/25/test-new-look-addons-mozilla-org/

The new site is mobile-first but should adapt to your system according to the resolution of your display so that on your desktop system it shouldn't look as much as a mobile site.

Given that this change was intended there isn't much we can do. If you have an actual problem or bug that we can fix feel very free to reply to this issue or open a new one on https://github.com/mozilla/addons-frontend/issues
