### ISSUE TITLE
Error message from Google drive 

### ISSUE THREAD

**Issue by cornfeld** [mozilla/addons#890]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I get this message from Google drive just below the note: 
Google Drive error: {"readyState":4,"responseText":"{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"global\",\n \"reason\": \"invalid\",\n \"message\": \"Invalid query\",\n \"locationType\": \"parameter\",\n \"location\": \"q\"\n }\n ],\n \"code\": 400,\n \"message\": \"Invalid query\"\n }\n}\n","responseJSON":{"error":{"errors":[{"domain":"global","reason":"invalid","message":"Invalid query","locationType":"parameter","location":"q"}],"code":400,"message":"Invalid query"}},"status":400,"statusText":"Bad Request"} 
### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for Questions/Discussions or the Add-ons author if you have any specific questions.

If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
