### ISSUE TITLE
Spanish statistics gone

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [mozilla/addons#891]
### Describe the problem and steps to reproduce it:
Spanish statistics from all add-ons are disable

### What happened?
Since last week all languages from different spanish countries has gone. This make statistics show wrong proportions

### What did you expect to happen?
Spanish languages should be restored

### Anything else we should know?
Take this addon as example: https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/statistics/usage/languages/?last=30 it doesn't appear languages from Spain, Argentina, Mexico, Chile...

**Comment by EnTeQuAk** [comment]
This could have been an accidental change because of our django-product-details removal, especially https://github.com/mozilla/addons-server/commit/04fe02162d13a06a1c382161dade39546d45a00b#diff-985121810cd4aeea2e6cc49cf63c61b1R290 may have contained many more languages than what we now have in our `core/languages.py`.

I'll take a look at that and restore these languages if possible. Good thing here is though that this is only the presentation layer, we still store the stats properly.

**Comment by AlexandraMoga** [comment]
I've tried to verify this with -dev and stage but the stats collected here are minimal. Most of the downloads are recorded under `en-US` and only a small proportion will display stats for other languages.

If there is another method to properly verify this in -dev or stage, that's be great. Otherwise, I will have to wait for this to land in prod. 

![image](https://user-images.githubusercontent.com/31961530/52333461-fa0efc80-2a05-11e9-994d-2996df135453.png)

**Comment by AlexandraMoga** [comment]
Verified fixed in prod:

![image](https://user-images.githubusercontent.com/31961530/52477930-5744b280-2bac-11e9-8940-ae47bbb2dfde.png)
