### ISSUE TITLE
Search still does not work

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons#905]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I tried to search for "no style" to see if any add-ons help users navigate most pages in "no style," set up a whitelist or blacklist for page styles, etc.

### What happened?

I got a bunch of irrelevant results. I have rsi, I am in pain, I can't search through the search results to see if there are any relevant results buried in there.

### What did you expect to happen?

Officially search is "verified fixed" and is supposed to work:

https://github.com/mozilla/addons-server/issues/6837

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by diox** [comment]
https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=no%20style does return add-ons about page restyling etc. Note that "no" is largely ignored unless it did appear specifically in an add-on name. I have no idea if better add-ons exist for what you're looking for - if you had specific add-ons in mind then we could look into why they do not appear at the top of the results. Otherwise I'm afraid we'll have to close this issue as I can't figure out rules to improve search without knowing what they should match.

**Comment by MarjaE2** [comment]
They should match "no style."

As in the accessibility option under view > page style > no style.

**Comment by MarjaE2** [comment]
And yes, I used quotes, to search for an exact phrase.

I haven't been able to test these due to compatibility issues, but possible options include: "No-script suite lite" (which can block styles as well as scripts), "Fixed-width and css annihilator," and "Decreased Productivity."

**Comment by MarjaE2** [comment]
Also, the search is turning up results where the header contains the term-- like Explore Extensions Themes More-- but the extension-specific info does not contain the term.
