### ISSUE TITLE
/users/unsubscribe/ (the unsubscribe link in emails) missing 

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#930]
Our automated emails have a link to  `https://addons.mozilla.org/users/unsubscribe/<token>/<hash>/<setting>` in the footer but that was served by addons-server.  Now nginx routes to addons-frontend by default the link is broken.  The page shown was a legacy frontend confirmation page anyway, which needs to be rewritten in addons-frontend.

**Comment by muffinresearch** [comment]
As mentioned on irc I think re-instating serving this from the legacy app would probably make sense to get this working, and we can then setup the necessary API to be able to run this from the addons-frontend separately and then switch it out.

Upgrading to p1 since I think it's pretty bad to have no way to unsubscribe, this should be fixed as quickly as possible.

**Comment by willdurand** [comment]
Temporarily fixed by @autrilla at the nginx level today :)

We will implement a long-term fix in https://github.com/mozilla/addons-frontend/issues/7656

**Comment by willdurand** [comment]
> Temporarily fixed by @autrilla at the nginx level today :)

The fix is part of https://github.com/mozilla-services/cloudops-deployment/pull/2924/files.
