### ISSUE TITLE
Provider for Google Calendar

### ISSUE THREAD

**Issue by myviolinsings** [mozilla/addons#961]
This add-on has not been working since the beginning of the year. I used to be able to add calendar events in lightning and this add-on would write it to google calendar also since I can't have Thunderbird/Lightning on my phone. When I add one now, it never syncs with Google calendar. I tried clicking the link on the add-on page and it said:

We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly. 

So is this no longer supported? Any other add-on that could work for this issue?

Thanks,
Sheila Flanagan
GutterMasters Plus
guttermastersplus@gmail.com

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please file issues about addons.thunderbird.net at https://github.com/thundernest/addons-server/issues.

If you think this issue has been closed erroneously please re-open or comment on the issue and provide as much information as possible so that we can assist you.
