### ISSUE TITLE
Link to extra dictionaries no longer working in the Dutch Thunderbird

### ISSUE THREAD

**Issue by Eddy-Pinson** [mozilla/addons#968]
### What did you expect to happen? I 
![Clipboard01](https://user-images.githubusercontent.com/49186794/55388000-c26a8f80-5532-11e9-8235-4fc6efaa4c21.jpg)
![niet gevonden](https://user-images.githubusercontent.com/49186794/55388001-c26a8f80-5532-11e9-8f46-70097e99b2eb.jpg)

should get a list of install-able languages

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by EnTeQuAk** [comment]
This issue tracker is only for issues related to the addons.mozilla.org (AMO) website and related services. Please file issues about addons.thunderbird.net at https://github.com/thundernest/addons-server/issues.

If you think this issue has been closed erroneously please re-open or comment on the issue and provide as much information as possible so that we can assist you.
