### ISSUE TITLE
I can't download any addons

### ISSUE THREAD

**Issue by Myon14** [mozilla/addons#994]
I got a notification saying my adblock was out of date or not supported anymore so I tried to download a new adblocker from your website and i'm getting an error that says download failed. please check your connection. My internet is fine I don't know why I can't download anything. Please help

**Comment by Spangler16** [comment]
There is an active bug Mozilla is working on that relates to the expiration (or perceived expiration) of certificates for numerous add-ons.  I read on another GitHub thread about a temporary workaround and applied it.  Close Firefox, then access your date and time settings.  Turn off "automatic" and manually set your date back one day.  I then went in and successfully reloaded all my extensions/add-ons.  I then went back in and re-set time to automatic .  They seem to be holding so far, about 30 minutes into the test.  If they disable again, I'll simply run a day earlier (or so) until the bug is fixed.  Hope this helps.

**Comment by Myon14** [comment]
thanks fore responding what you said worked for me

**Comment by nenaAdoctrinada** [comment]
[https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047](url)

**Comment by smayer97** [comment]
link is no good.

**Comment by Myon14** [comment]
Yeah that link didn't do anything

**Comment by Myon14** [comment]
Spangler16's idea worked for me it might for you

**Comment by willdurand** [comment]
This is being handled right now, sorry for the inconvenience. Please see: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
