### ISSUE TITLE
Mozilla addons disabled suddenly and just marking issues as spam

### ISSUE THREAD

**Issue by neri4488** [mozilla/addons#997]
I were using https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/ all of a sudden, it disabled by firefox and I can not reinstall it.

I use Windows machine, running Windows 10 

Firefox Quantum v66.0.3 (64-bit)

Mozilla just locked #851 as "spam." Expect similar treatment here shortly.

_Originally posted by @leycec in https://github.com/mozilla/addons/issues/978#issuecomment-489281783_

**Comment by wagnerand** [comment]
This is due to a certificate issue. Our team is currently working on a fix and we'll be providing updates on this thread: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/4

There is nothing we can do here and therefore no reason to keep this issue open.
